import type { JSX } from "preact";
import type { ContentFieldDefinition } from "../../content";
import type { ContentAuthoringController, ContentAuthoringState } from "./controller";
import { FieldKindPicker } from "./field-kind-picker";
import { MarkdownEditor } from "./markdown-editor";

export function ContentSchemaAuthor({ state, controller, run, onRemove }: { state: ContentAuthoringState; controller: ContentAuthoringController; run(action: () => void | Promise<void>): void; onRemove(field: ContentFieldDefinition): void }): JSX.Element {
  const model = state.model!;
  return <div class="sg-content-form"><label>Model name<input value={model.document.name} onInput={(event) => controller.renameModel(event.currentTarget.value)} /></label><label>Model kind<select value={model.document.kind} disabled aria-describedby="kind-help"><option value="collection">Collection</option><option value="single">Single</option></select></label><p id="kind-help" class="sg-content-help">Model kind is immutable after creation to protect Entry cardinality.</p><div class="sg-content-section-heading"><div><h3>Model fields</h3><p class="sg-content-help">Choose types by meaning; stored identifiers are shown for reference.</p></div><button type="button" onClick={() => controller.addField()}>Add field</button></div>
    {model.document.fields.map((field, index) => { const kindLocked = state.usedFieldIds.includes(field.id); const kindHelpId = `content-kind-help-${field.id}`; return <fieldset key={field.id} class="sg-content-field"><legend>{field.label}</legend><label>Label<input value={field.label} onInput={(event) => controller.updateField(field.id, { label: event.currentTarget.value })} /></label><label>Key<input value={field.key} pattern="[a-z][A-Za-z0-9]{0,63}" onInput={(event) => controller.updateField(field.id, { key: event.currentTarget.value })} /></label><FieldKindPicker value={field.kind} locked={kindLocked} label={`Type for ${field.label}`} onChange={(kind) => run(() => controller.updateField(field.id, { kind }))} />{kindLocked && <p id={kindHelpId} class="sg-content-help">Type is immutable because stored Entries use this field. Remove those values or add a new field to use another type.</p>}<label class="sg-content-check"><input type="checkbox" checked={field.required} onChange={(event) => controller.updateField(field.id, { required: event.currentTarget.checked })} />Required</label><div class="sg-content-actions"><button type="button" disabled={index === 0} onClick={() => controller.moveField(field.id, -1)}>Move up</button><button type="button" disabled={index === model.document.fields.length - 1} onClick={() => controller.moveField(field.id, 1)}>Move down</button><button type="button" onClick={() => onRemove(field)}>Remove…</button></div></fieldset>; })}</div>;
}

export function ContentEntryAuthor({ state, controller }: { state: ContentAuthoringState; controller: ContentAuthoringController }): JSX.Element {
  const entry = state.entry!; const diagnostics = controller.completeness();
  return <div class="sg-content-form"><div class="sg-content-completeness" role="status"><strong>{diagnostics.length ? "Incomplete draft" : "Complete"}</strong><span>{diagnostics.length ? `${diagnostics.length} required value${diagnostics.length === 1 ? "" : "s"} missing. Draft changes still save.` : "All required values are present."}</span></div>{state.model!.document.fields.map((field) => { const id = `content-entry-${field.id}`; const value = entry.values[field.id]; if (field.kind === "markdown") return <MarkdownEditor key={field.id} identity={`${entry.id}/${field.id}`} value={typeof value === "string" ? value : ""} label={field.label} required={field.required} onChange={(next) => controller.updateEntryValue(field.id, next)} />; if (field.kind === "boolean") return <label key={field.id} class="sg-content-check"><input id={id} type="checkbox" checked={value === true} onChange={(event) => controller.updateEntryValue(field.id, event.currentTarget.checked)} />{field.label}{field.required ? " (required)" : ""}</label>; if (field.kind === "long-text") return <label key={field.id}>{field.label}{field.required ? " (required)" : ""}<textarea id={id} value={typeof value === "string" ? value : ""} onInput={(event) => controller.updateEntryValue(field.id, event.currentTarget.value)} /></label>; return <label key={field.id}>{field.label}{field.required ? " (required)" : ""}<input id={id} type={field.kind === "number" ? "number" : field.kind === "date" ? "date" : field.kind === "color" ? "color" : field.kind === "url" ? "url" : "text"} value={typeof value === "string" || typeof value === "number" ? value : ""} onInput={(event) => { const numeric = event.currentTarget.valueAsNumber; controller.updateEntryValue(field.id, field.kind === "number" ? (event.currentTarget.value === "" || !Number.isFinite(numeric) ? undefined : numeric) : event.currentTarget.value); }} /></label>; })}</div>;
}
