// `site-project.ts` → `site-project.json`.
//
// The TypeScript source is the authored truth and the JSON is the committed
// aggregate consumed by the tool. The host source is evaluated through the
// caller's Vite module runner so host JSX settings cannot select React when the
// tool is installed under node_modules.

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { ComponentPackManifest } from "@zudo-composer/component-contract";
import { canonicalStringifyJson } from "../../src/site-project/model/canonical";
import type { SiteProject, SiteProjectDiagnostic } from "../../src/site-project/model/types";
import type { Site } from "../../src/site-project/authoring";
import { validateSiteProject } from "../../src/site-project/model/validation";

export const SITE_SOURCE_FILE = "site-project.ts";
export const SITE_OUTPUT_FILE = "site-project.json";

export type ComposerModuleEvaluator = (modulePath: string) => Promise<Record<string, unknown>>;

export interface GenerateSiteProjectOptions {
  /** Absolute host root containing the authored source and generated output. */
  packageRoot: string;
  /** The resolved host component pack's manifest, used as validation context. */
  componentPack: ComponentPackManifest;
  /** Evaluator rooted at the host project, with the tool's Preact JSX policy. */
  evaluate: ComposerModuleEvaluator;
  /** Compare the generated bytes without writing them. */
  check?: boolean;
}

export interface GenerateSiteProjectResult {
  outputPath: string;
  changed: boolean;
}

export class SiteProjectGenerationError extends Error {
  constructor(message: string, readonly diagnostics: readonly SiteProjectDiagnostic[] = []) {
    super(diagnostics.length
      ? `${message}\n${diagnostics.map((item) => `  ${item.path}: ${item.message} [${item.code}]`).join("\n")}`
      : message);
  }
}

function isSite(value: unknown): value is Site {
  return typeof value === "object" && value !== null && typeof (value as Site).toSiteProject === "function";
}

/** Evaluate a host's default-exported `site-project.ts`. */
export async function loadSite(packageRoot: string, evaluate: ComposerModuleEvaluator): Promise<Site> {
  const sourcePath = resolve(packageRoot, SITE_SOURCE_FILE);
  const module = await evaluate(sourcePath);
  if (!isSite(module.default)) {
    throw new SiteProjectGenerationError(`${SITE_SOURCE_FILE} must default-export a site built with defineSite().`);
  }
  return module.default;
}

/** Validate against the resolved host pack and return canonical JSON text. */
export function renderSiteProject(site: Site, componentPack: ComponentPackManifest = site.manifest): { project: SiteProject; text: string } {
  const validation = validateSiteProject(site.toSiteProject(), { componentPack });
  if (!validation.ok) {
    throw new SiteProjectGenerationError(`Site "${site.id}" is not a valid SiteProject.`, validation.diagnostics);
  }
  return { project: validation.project, text: canonicalStringifyJson(validation.project as never) };
}

async function readExisting(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined;
    throw error;
  }
}

/** Generate the aggregate, or check that the committed bytes are current. */
export async function generateSiteProject(options: GenerateSiteProjectOptions): Promise<GenerateSiteProjectResult> {
  const site = await loadSite(options.packageRoot, options.evaluate);
  const { text } = renderSiteProject(site, options.componentPack);
  const outputPath = resolve(options.packageRoot, SITE_OUTPUT_FILE);
  const previous = await readExisting(outputPath);

  if (options.check) {
    if (previous === undefined) {
      throw new SiteProjectGenerationError(`${SITE_OUTPUT_FILE} is missing in ${options.packageRoot}: generate it from ${SITE_SOURCE_FILE} with \`zudo-composer generate\`.`);
    }
    if (previous !== text) {
      throw new SiteProjectGenerationError(`${SITE_OUTPUT_FILE} in ${options.packageRoot} is stale: generated content from ${SITE_SOURCE_FILE} differs. Run \`zudo-composer generate\`.`);
    }
    return { outputPath, changed: false };
  }

  if (previous !== text) await writeFile(outputPath, text);
  return { outputPath, changed: previous !== text };
}
