import { AUTHORING_PERSISTENCE_CHANNELS } from "../../../app/persistence-channels";
import { notifyPersistenceChange, subscribePersistenceChanges } from "../../../shared/persistence-generation";
import { describe, expect, it, vi } from "vitest";
import type { ProductionProviderIntegration } from "../../../app/provider-integration";
import { createWorkspaceSaveRegistry } from "../../../app/workspace-sessions";
import { project } from "../../../site-project/compiler/__tests__/fixtures";
import type { ReleasePlan, SiteProjectApiRequest, SiteProjectApiResponse, StagedRelease, SiteProjectActiveSelection } from "../../../site-project/api/types";
import { createReleaseController } from "../controller";
import type { ReleaseTransport } from "../transport";
import { createApplicationOperationGate } from "../../../app/operation-gate";

function harness() {
  let working = project(), generation = 0, listener = () => {}, releaseListener = () => {};
  let staged: StagedRelease | null = null, active: SiteProjectActiveSelection | null = null, built = false;
  let fail: string | null = null, uncertain = false;
  const requests: SiteProjectApiRequest[] = [];
  const sessions = createWorkspaceSaveRegistry();
  const integration = { workspace: { id: "release-test" }, sessions, contentProviders: [],
    captureWorkspace: vi.fn(async () => ({ status: "ready", project: structuredClone(working), capture: { workspaceId: "release-test", sessionGeneration: generation, tokens: { workspace: generation }, values: {} } })),
    getCurrentSiteProject: async () => ({ status: "ready", project: working }),
    isCaptureCurrent: async (capture: { sessionGeneration: number }) => capture.sessionGeneration === generation,
    subscribeChanges: (next: () => void) => { listener = next; return subscribePersistenceChanges(next); },
  } as unknown as ProductionProviderIntegration;
  let guard!: (payload: unknown) => Promise<unknown>;
  const transport: ReleaseTransport = { available: true, dispose: vi.fn(), subscribe(next) { releaseListener = next; return () => {}; }, async request(request, verify) {
    requests.push(request); if (verify) guard = verify;
    if (fail === request.operation) return { ok: false, error: { code: uncertain ? "commit-uncertain" : "conflict", message: "injected failure" } };
    let result: unknown;
    if (request.operation === "list") result = { projects: staged ? [{ projectId: staged.projectId, head: staged.revision, stages: [staged.buildId] }] : [], active, generation: staged ? 1 : 0, stageGenerations: staged ? { [staged.buildId]: 1 } : {} };
    if (request.operation === "get") result = { project: working };
    if (request.operation === "stage") result = { stage: staged, stageGeneration: 1 };
    if (request.operation === "plan") result = { schemaVersion: 2, workingProject: structuredClone(working), workingPrecondition: request.workingPrecondition, candidate: structuredClone(working), selection: request.selection, expectedRevision: null, expectedActive: active, storeGeneration: 0, projectRevision: "a".repeat(64), buildId: "b".repeat(64), mediaLock: null, toolchain: { compiler: "test", componentPack: { packId: "test", packVersion: "1", contractVersion: 1 }, packSpecifier: "@fixture/pack/composer-pack", packSource: "workspace:*", installedPackDigest: "c".repeat(64), contractDigest: "d".repeat(64) }, changes: [], checks: [{ severity: "info", code: "ready", message: "Ready", path: "$" }], affected: [], publication: [], planDigest: "c".repeat(64) } satisfies ReleasePlan;
    if (request.operation === "apply") { if (!await verify!({ kind: "current", project: request.plan.workingProject, precondition: request.plan.workingPrecondition })) return { ok: false, error: { code: "conflict", message: "stale" } }; const p = request.plan; staged = { schemaVersion: 2, projectId: p.candidate.id, revision: p.projectRevision, buildId: p.buildId, mediaLock: p.mediaLock, toolchain: p.toolchain, planDigest: p.planDigest, publication: p.publication }; result = { staged, stageGeneration: 1 }; }
    if (request.operation === "build" || request.operation === "completed") { if (request.operation === "completed" && !built) return { ok: false, error: { code: "not-found", message: "Not built" } }; built = true; result = { identity: { projectId: staged!.projectId, revision: staged!.revision, buildId: staged!.buildId }, stage: staged, files: {}, completionDigest: "d".repeat(64), build: {} }; }
    if (request.operation === "activate") { active = { projectId: request.projectId, revision: request.revision, buildId: request.buildId }; const reconciliation = await verify?.({ kind: "reconcile", active, changes: staged!.publication, activationGeneration: 1 }); result = { active, activationGeneration: 1, reconciliation }; }
    if (request.operation === "discard") { staged = null; result = { active }; }
    return { ok: true, result } as SiteProjectApiResponse;
  } };
  const gate = createApplicationOperationGate();
  const controller = createReleaseController(integration, transport, gate);
  const edit = () => { working = { ...working, name: "B" }; generation++; listener(); };
  const ready = async () => { await controller.inspect(); await controller.review(); controller.approve(); };
  return { controller, integration, transport, gate, requests, ready, edit, guard: (payload: unknown) => guard(payload), releaseChanged: () => releaseListener(), fail(operation: string | null, unknown = false) { fail = operation; uncertain = unknown; }, working: () => working };
}
describe("review and release state machine", () => {
  it.each([...AUTHORING_PERSISTENCE_CHANNELS, "media"])("invalidates an approved release on %s writes", async (channel) => {
    const h = harness(); await h.ready(); notifyPersistenceChange(channel);
    await h.controller.apply();
    expect(h.requests.some(({ operation }) => operation === "apply")).toBe(false);
    expect(h.controller.getSnapshot().phase).toBe("inspect"); h.controller.dispose();
  });
  it("keeps the exact staged identity visible when an acknowledgement is lost", async () => { const h = harness(); await h.ready(); const approved = h.controller.getSnapshot().plan!; h.fail("apply", true); await h.controller.apply(); expect(h.controller.getSnapshot().phase).toBe("uncertain"); expect(h.controller.getSnapshot().staged).toMatchObject({ projectId: approved.candidate.id, revision: approved.projectRevision, buildId: approved.buildId, planDigest: approved.planDigest }); h.controller.dispose(); });
  it("resolves a lost acknowledgement through the idempotent server stage", async () => { const h = harness(); await h.ready(); const request = h.transport.request; let dropped = false; h.transport.request = async (value, verify) => { const result = await request(value, verify); if (value.operation === "apply" && !dropped) { dropped = true; return { ok: false, error: { code: "commit-uncertain", message: "acknowledgement lost" } }; } return result; }; await h.controller.apply(); const staged = h.controller.getSnapshot().staged!; expect(h.controller.getSnapshot().phase).toBe("uncertain"); await h.controller.inspect(); expect(h.controller.getSnapshot()).toMatchObject({ phase: "staged", staged }); h.controller.dispose(); });
  it.each([["new", "publish"], ["changed", "publish"], ["deleted", "delete"], ["unpublish", "unpublish"]] as const)("sends explicit %s selection as %s without changing working lifecycle", async (kind, action) => { const h = harness(); await h.controller.inspect(); const before = structuredClone(h.working()); const ref = { providerId: "content-filesystem", modelId: "articles", recordId: "entry" }; h.controller.select({ ref, kind }, true); await h.controller.review(); expect(h.requests.find(({ operation }) => operation === "plan")).toMatchObject({ selection: [{ ref, action }] }); expect(h.working()).toEqual(before); h.controller.dispose(); });
  it("invalidates unstaged approval for a working/provider change", async () => { const h = harness(); await h.ready(); h.edit(); await h.controller.apply(); expect(h.requests.some(({ operation }) => operation === "apply")).toBe(false); expect(h.controller.getSnapshot().phase).toBe("inspect"); h.controller.dispose(); });
  it("stages A then retains edited B through exact build/activation and reload inspection", async () => {
    const h = harness(); await h.ready(); await h.controller.apply(); const a = h.controller.getSnapshot().staged; h.edit();
    await h.controller.build(); await h.controller.activate(); expect(h.controller.getSnapshot()).toMatchObject({ phase: "activated", staged: a }); expect(h.working().name).toBe("B");
    h.controller.dispose(); const reloaded = createReleaseController(h.integration, h.transport); await reloaded.inspect(); await reloaded.selectStage(reloaded.getSnapshot().retainedStages[0]!); expect(reloaded.getSnapshot()).toMatchObject({ phase: "activated", staged: a, working: { name: "B" } }); reloaded.dispose();
  });
  it("rejects cross-workspace and altered candidate challenges", async () => { const h = harness(); await h.ready(); const plan = h.controller.getSnapshot().plan!; expect(await h.guard({ kind: "current", project: plan.workingProject, precondition: { ...plan.workingPrecondition as object, workspaceId: "other" } })).toBe(false); expect(await h.guard({ kind: "current", project: { ...plan.workingProject, name: "changed" }, precondition: plan.workingPrecondition })).toBe(false); h.controller.dispose(); });
  it("blocks plan on save/capture failure", async () => { const h = harness(); vi.mocked(h.integration.captureWorkspace).mockResolvedValue({ status: "save-failed", failures: [{ feature: "Content", providerId: "db", error: new Error("disk full") }] }); await h.controller.review(); expect(h.controller.getSnapshot().error).toContain("disk full"); expect(h.requests).toHaveLength(0); h.controller.dispose(); });
  it("retains exact stage across build failure and forbids blind retry after uncertainty", async () => { const h = harness(); await h.ready(); await h.controller.apply(); h.fail("build", true); await h.controller.build(); expect(h.controller.getSnapshot().phase).toBe("uncertain"); h.fail(null); await h.controller.build(); expect(h.requests.filter(({ operation }) => operation === "build")).toHaveLength(1); await h.controller.inspect(); expect(h.controller.getSnapshot().phase).toBe("staged"); await h.controller.build(); expect(h.controller.getSnapshot().phase).toBe("built"); h.controller.dispose(); });
  it("discards with exact inspected stage incarnation and active precondition", async () => { const h = harness(); await h.ready(); await h.controller.apply(); await h.controller.discard(); expect(h.requests.find(({ operation }) => operation === "discard")).toMatchObject({ operation: "discard", expectedStageGeneration: 1, expectedActive: null }); h.controller.dispose(); });
  it("recovers exact staged A even when newer B cannot be captured", async () => { const h = harness(); await h.ready(); await h.controller.apply(); h.controller.dispose(); vi.mocked(h.integration.captureWorkspace).mockResolvedValue({ status: "save-failed", failures: [{ feature: "Content", providerId: "db", error: new Error("invalid B") }] }); const reloaded = createReleaseController(h.integration, h.transport); await reloaded.inspect(); expect(reloaded.getSnapshot().error).toBe("invalid B"); await reloaded.selectStage(reloaded.getSnapshot().retainedStages[0]!); await reloaded.build(); expect(reloaded.getSnapshot().phase).toBe("built"); reloaded.dispose(); });
  it("selects server-only catalog stages without a valid newer draft", async () => { const h = harness(); await h.ready(); await h.controller.apply(); h.controller.dispose(); vi.mocked(h.integration.captureWorkspace).mockResolvedValue({ status: "changed", sources: ["B"] }); const other = createReleaseController(h.integration, h.transport); await other.inspect(); expect(other.getSnapshot().retainedStages).toHaveLength(1); expect(other.getSnapshot().staged).toBeNull(); await other.selectStage(other.getSnapshot().retainedStages[0]!); await other.build(); expect(other.getSnapshot().phase).toBe("built"); other.dispose(); });
  it("performs activation reconciliation without nested privileged requests", async () => { const h = harness(), request = h.transport.request; let active = 0, peak = 0; h.transport.request = async (...args) => { active++; peak = Math.max(peak, active); try { return await request(...args); } finally { active--; } }; await h.ready(); await h.controller.apply(); await h.controller.build(); await h.controller.activate(); expect(h.controller.getSnapshot().phase).toBe("activated"); expect(peak).toBe(1); expect(h.controller.getSnapshot().message).toContain("Publication reconciliation: applied"); h.controller.dispose(); });
  it("rejects every release action while replacement owns the application gate", async () => { const h = harness(); await h.ready(); const before = h.requests.length, release = h.gate.claim("replacement")!; expect(h.controller.getSnapshot().gateBlocked).toBe(true); await h.controller.apply(); await h.controller.inspect(); h.controller.approve(); h.controller.newReview(); expect(h.requests).toHaveLength(before); expect(h.controller.getSnapshot().phase).toBe("approved"); release(); await h.controller.apply(); expect(h.controller.getSnapshot().phase).toBe("staged"); h.controller.dispose(); });
  it("blocks replacement during a release and does not free its claim on premature dispose", async () => { const h = harness(); let finish!: (value: Awaited<ReturnType<ProductionProviderIntegration["captureWorkspace"]>>) => void; const capture = await h.integration.captureWorkspace(); vi.mocked(h.integration.captureWorkspace).mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; })); const pending = h.controller.inspect(); expect(h.gate.claim("replacement")).toBeNull(); await vi.waitFor(() => expect(finish).toBeTypeOf("function")); h.controller.dispose(); expect(h.gate.busy).toBe(true); finish(capture); await pending; expect(h.gate.busy).toBe(false); const count = h.requests.length; await h.controller.review(); expect(h.requests).toHaveLength(count); });
  it("static mode inspects without pretending Media or write capability exists", async () => { const h = harness(); const transport = { ...h.transport, available: false, request: vi.fn(h.transport.request) }; const controller = createReleaseController(h.integration, transport); await controller.inspect(); await controller.review(); expect(controller.exportProject()).toContain(h.working().name); expect(transport.request).not.toHaveBeenCalled(); controller.dispose(); h.controller.dispose(); });
});
