// Generated by pnpm build:public. Edit server/public and its source dependencies.
import { B as assetMimeTypeForExtension, F as assetAuthoringUrl, _ as canonicalStringifyJson, t as validateSiteProject, x as createFilesystemAssetStore } from "./generated/validation-QzJyDWFx.mjs";
import { readFileSync } from "node:fs";
import { join } from "node:path";
//#region src/site-project/authoring.ts
var COMPOSITION_PROVIDER_ID = "files";
var CONTENT_PROVIDER_ID = "content-filesystem";
var MAPPING_PROVIDER_ID = "mapping-filesystem";
var SITEMAP_PROVIDER_ID = "sitemap-filesystem";
/** Every generated record carries one fixed timestamp so regeneration is byte-stable. */
var DEFAULT_TIMESTAMP = "2026-09-12T00:00:00.000Z";
/** `Product card` → `product-card`; matches the tool's safe record-id pattern. */
function slugify(name) {
	const slug = name.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
	if (slug === "") throw new Error(`Cannot derive a record id from "${name}".`);
	return slug;
}
/** One composition node. Omitted ids are derived per composition from the component id and position. */
function node(componentId, props = {}, slots = {}, id) {
	return {
		...id === void 0 ? {} : { id },
		componentId,
		props,
		slots
	};
}
function assertNew(registry, id, kind) {
	if (registry.has(id)) throw new Error(`Duplicate ${kind} id "${id}".`);
}
function buildNodes(context, inputs) {
	return inputs.map((input) => {
		const componentVersion = context.componentVersions.get(input.componentId);
		if (componentVersion === void 0) throw new Error(`Component "${input.componentId}" is not in pack "${context.packId}".`);
		const id = input.id ?? `${context.compositionId}-${slugify(input.componentId)}-${context.next++}`;
		if (context.seen.has(id)) throw new Error(`Duplicate node id "${id}" in composition "${context.compositionId}".`);
		context.seen.add(id);
		const slots = {};
		for (const [slotId, children] of Object.entries(input.slots ?? {})) slots[slotId] = buildNodes(context, children);
		return {
			id,
			componentId: input.componentId,
			componentVersion,
			props: { ...input.props ?? {} },
			slots
		};
	});
}
/** `publishedOn` → `published-on`, so derived field ids keep the key's word boundaries. */
function kebabFromKey(key) {
	return slugify(key.replace(/([a-z0-9])([A-Z])/g, "$1-$2"));
}
function buildField(modelId, input) {
	const base = {
		id: `${modelId}-${kebabFromKey(input.key)}`,
		key: input.key,
		label: input.label ?? labelFromKey(input.key),
		required: input.required ?? true
	};
	switch (input.kind) {
		case "choice": return {
			...base,
			kind: "choice",
			options: input.options
		};
		case "reference": return {
			...base,
			kind: "reference",
			target: {
				providerId: CONTENT_PROVIDER_ID,
				recordId: input.target.id
			}
		};
		case "reference-list": return {
			...base,
			kind: "reference-list",
			target: {
				providerId: CONTENT_PROVIDER_ID,
				recordId: input.target.id
			},
			ordered: input.ordered ?? true
		};
		case "object": return {
			...base,
			kind: "object",
			fields: input.fields.map((field) => buildField(base.id, field))
		};
		case "list": return {
			...base,
			kind: "list",
			item: input.item
		};
		case "asset-use": return {
			...base,
			kind: "asset-use",
			use: input.use
		};
		default: return {
			...base,
			kind: input.kind
		};
	}
}
function labelFromKey(key) {
	const spaced = key.replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase();
	return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}
function defineSite(options) {
	const timestamp = options.timestamp ?? "2026-09-12T00:00:00.000Z";
	const manifest = options.componentPack.manifest;
	const compositions = /* @__PURE__ */ new Map();
	const models = /* @__PURE__ */ new Map();
	const entries = /* @__PURE__ */ new Map();
	const mappings = /* @__PURE__ */ new Map();
	const attachments = /* @__PURE__ */ new Map();
	let sitemap;
	const envelope = {
		createdAt: timestamp,
		updatedAt: timestamp
	};
	const componentVersions = new Map(manifest.components.map((component) => [component.id, component.schemaVersion]));
	const composition = (id, root) => {
		assertNew(compositions, id, "composition");
		return buildNodes({
			compositionId: id,
			packId: manifest.packId,
			componentVersions,
			seen: /* @__PURE__ */ new Set(),
			next: 1
		}, root);
	};
	return {
		id: options.id,
		name: options.name,
		manifest,
		template(input) {
			const id = input.id ?? slugify(input.name);
			const root = composition(id, input.root);
			const outlet = {
				id: input.outlet.id ?? `${id}-outlet`,
				label: input.outlet.label ?? "Main content",
				target: input.outlet.target
			};
			const record = {
				id,
				...envelope,
				document: {
					schemaVersion: 2,
					id,
					name: input.name,
					root,
					publication: {
						kind: "global-template",
						outlet
					}
				}
			};
			compositions.set(id, record);
			return {
				id,
				outlet,
				record
			};
		},
		page(input) {
			const id = input.id ?? slugify(input.name);
			const root = composition(id, input.root);
			const record = {
				id,
				...envelope,
				document: {
					schemaVersion: 2,
					id,
					name: input.name,
					root,
					...input.template ? { binding: {
						sourceRecordId: input.template.id,
						outletId: input.template.outlet.id
					} } : {}
				}
			};
			compositions.set(id, record);
			return {
				id,
				record
			};
		},
		model(input) {
			const id = input.id ?? slugify(input.name);
			assertNew(models, id, "content model");
			const fields = input.fields.map((field) => buildField(id, field));
			const byKey = new Map(fields.map((field) => [field.key, field.id]));
			if (byKey.size !== fields.length || new Set(byKey.values()).size !== fields.length) throw new Error(`Model "${id}" declares a duplicate field key.`);
			const record = {
				id,
				...envelope,
				document: {
					schemaVersion: 1,
					id,
					name: input.name,
					description: input.description ?? "",
					kind: input.kind,
					fields
				}
			};
			models.set(id, record);
			return {
				id,
				record,
				fieldId(key) {
					const fieldId = byKey.get(key);
					if (fieldId === void 0) throw new Error(`Model "${id}" has no field "${key}".`);
					return fieldId;
				}
			};
		},
		entry(model, input) {
			const id = input.id ?? deriveEntryId(model, input.values);
			assertNew(entries, id, "content entry");
			const values = {};
			const fields = model.record.document.fields;
			for (const [key, value] of Object.entries(input.values)) values[model.fieldId(key)] = valueByFieldId(fields.find((field) => field.key === key), value);
			const record = {
				schemaVersion: 1,
				id,
				modelId: model.id,
				...envelope,
				values,
				lifecycle: input.lifecycle ?? "published",
				generation: 0
			};
			entries.set(id, record);
			return {
				id,
				modelId: model.id,
				record
			};
		},
		mapping(input) {
			const id = input.id ?? slugify(input.name);
			assertNew(mappings, id, "mapping");
			const bindings = input.bindings.map((binding) => ({
				id: binding.id ?? `${id}-${slugify(binding.field)}-${slugify(binding.prop)}`,
				sourceFieldId: input.model.fieldId(binding.field),
				projection: binding.projection ?? { kind: "value" },
				target: {
					nodeId: binding.nodeId,
					prop: binding.prop
				},
				transform: binding.transform ?? { kind: "identity" }
			}));
			const mode = input.mode ?? { kind: "single" };
			const record = {
				id,
				...envelope,
				document: {
					schemaVersion: 2,
					id,
					name: input.name,
					contentModel: {
						providerId: CONTENT_PROVIDER_ID,
						recordId: input.model.id
					},
					composition: {
						providerId: COMPOSITION_PROVIDER_ID,
						recordId: input.composition.id
					},
					mode: mode.kind === "single" ? { kind: "single" } : {
						kind: "collection",
						query: {
							publication: mode.publication ?? "published-only",
							conditions: (mode.conditions ?? []).map((condition) => ({
								fieldId: input.model.fieldId(condition.field),
								operator: condition.operator,
								...condition.value === void 0 ? {} : { value: condition.value }
							})),
							sort: (mode.sort ?? []).map((sort) => ({
								fieldId: input.model.fieldId(sort.field),
								direction: sort.direction
							})),
							pins: [],
							limit: mode.limit ?? 100
						}
					},
					bindings
				}
			};
			mappings.set(id, record);
			return {
				id,
				model: input.model,
				composition: input.composition,
				record
			};
		},
		attach(mapping, target, id) {
			const attachmentId = id ?? `${mapping.id}-${slugify(target.nodeId)}-${slugify(target.slotId)}`;
			assertNew(attachments, attachmentId, "collection attachment");
			const owner = target.composition?.id ?? ownerOfNode(compositions, target.nodeId);
			const record = {
				id: attachmentId,
				order: attachments.size,
				composition: {
					providerId: COMPOSITION_PROVIDER_ID,
					recordId: owner
				},
				target: {
					nodeId: target.nodeId,
					slotId: target.slotId
				},
				mapping: {
					providerId: MAPPING_PROVIDER_ID,
					recordId: mapping.id
				}
			};
			attachments.set(attachmentId, record);
			return {
				id: attachmentId,
				record
			};
		},
		sitemap(input) {
			if (sitemap) throw new Error("A site has exactly one sitemap.");
			const id = input.id ?? slugify(input.name);
			const nodeIds = /* @__PURE__ */ new Map();
			const seen = /* @__PURE__ */ new Set();
			const buildRoute = (route) => {
				const nodeId = route.id ?? `${slugify(route.title)}-node`;
				if (seen.has(nodeId)) throw new Error(`Duplicate sitemap node id "${nodeId}".`);
				seen.add(nodeId);
				nodeIds.set(route, nodeId);
				return {
					id: nodeId,
					title: route.title,
					...route.slug === void 0 ? {} : { slug: route.slug },
					...route.notes === void 0 ? {} : { notes: route.notes },
					source: routeSource(route),
					children: (route.children ?? []).map(buildRoute)
				};
			};
			const root = buildRoute(input.root);
			const navigationItems = (refs = []) => refs.map((ref) => {
				const nodeId = nodeIds.get(ref.route);
				if (nodeId === void 0) throw new Error(`Navigation item "${ref.route.title}" is not in the sitemap tree.`);
				return {
					id: ref.id ?? `nav-${nodeId}`,
					label: ref.label ?? ref.route.title,
					visible: ref.visible ?? true,
					destination: {
						kind: "route",
						nodeId
					}
				};
			});
			sitemap = {
				id,
				...envelope,
				document: {
					schemaVersion: 3,
					id,
					name: input.name,
					navigation: {
						primary: navigationItems(input.navigation?.primary),
						footer: navigationItems(input.navigation?.footer)
					},
					root: [root]
				}
			};
			return sitemap;
		},
		toSiteProject() {
			if (!sitemap) throw new Error(`Site "${options.id}" has no sitemap.`);
			return {
				schemaVersion: 2,
				id: options.id,
				name: options.name,
				componentPack: {
					contractVersion: manifest.contractVersion,
					packId: manifest.packId,
					packVersion: manifest.packVersion
				},
				providers: {
					compositions: [{
						id: COMPOSITION_PROVIDER_ID,
						records: [...compositions.values()]
					}],
					content: [{
						id: CONTENT_PROVIDER_ID,
						models: [...models.values()],
						entries: [...entries.values()]
					}],
					mappings: [{
						id: MAPPING_PROVIDER_ID,
						records: [...mappings.values()]
					}],
					sitemaps: [{
						id: SITEMAP_PROVIDER_ID,
						records: [sitemap]
					}]
				},
				activeSitemap: {
					providerId: SITEMAP_PROVIDER_ID,
					recordId: sitemap.id
				},
				collectionAttachments: [...attachments.values()]
			};
		}
	};
}
function containsNode(nodes, nodeId) {
	return nodes.some((item) => item.id === nodeId || Object.values(item.slots).some((children) => containsNode(children, nodeId)));
}
function ownerOfNode(compositions, nodeId) {
	const owners = [...compositions.values()].filter((record) => containsNode(record.document.root, nodeId)).map((record) => record.id);
	if (owners.length === 1) return owners[0];
	if (owners.length === 0) throw new Error(`No declared composition contains node "${nodeId}"; declare the page before attaching to it.`);
	throw new Error(`Node "${nodeId}" exists in compositions ${owners.join(", ")}; pass the owner as target.composition.`);
}
/** Object values are stored keyed by nested field id; authors write them keyed by nested field key. */
function valueByFieldId(schema, value) {
	if (schema.kind === "list" && Array.isArray(value)) return value.map((item) => valueByFieldId(schema.item, item));
	if (schema.kind !== "object" || value === null || typeof value !== "object" || Array.isArray(value)) return value;
	const stored = {};
	for (const [key, item] of Object.entries(value)) {
		const field = schema.fields.find((candidate) => candidate.key === key);
		if (!field) throw new Error(`Object field has no nested field "${key}".`);
		stored[field.id] = valueByFieldId(field, item);
	}
	return stored;
}
/** The provider-qualified value a `reference` field stores (a `reference-list` stores an array of them). */
function entryRef(entry) {
	return {
		providerId: CONTENT_PROVIDER_ID,
		modelId: entry.modelId,
		recordId: entry.id
	};
}
/** An entry id from its first slug/text value; explicit ids are preferred in real content. */
function deriveEntryId(model, values) {
	for (const field of model.record.document.fields) {
		const value = values[field.key];
		if ((field.kind === "slug" || field.kind === "text") && typeof value === "string" && value.trim() !== "") return `${model.id}-${slugify(value)}`;
	}
	throw new Error(`Entry of model "${model.id}" needs an explicit id or a slug/text value.`);
}
function routeSource(route) {
	if ("page" in route) return {
		kind: "composition",
		ref: {
			providerId: COMPOSITION_PROVIDER_ID,
			recordId: route.page.id
		}
	};
	const ref = {
		providerId: MAPPING_PROVIDER_ID,
		recordId: route.mapping.id
	};
	if (route.route === "entry-field") {
		const titleField = route.titleField ?? route.mapping.model.record.document.fields.find((field) => field.kind === "text")?.key;
		return {
			kind: "mapping",
			ref,
			route: {
				kind: "entry-field",
				fieldId: route.mapping.model.fieldId(route.field),
				...titleField === void 0 ? {} : { titleFieldId: route.mapping.model.fieldId(titleField) }
			}
		};
	}
	return {
		kind: "mapping",
		ref,
		route: { kind: "single" }
	};
}
//#endregion
//#region server/authoring/assets.ts
/**
* File name → canonical authoring URL for the active assets in a resolved host
* config. Use `loadHostContext()` from `zudo-composer/vite` to resolve that config.
* Asset ids are minted at upload, so authored sites look them up by file name.
*/
function readAssetUrls(config) {
	const catalog = JSON.parse(readFileSync(join(config.paths.assets, "catalog.json"), "utf8"));
	const urls = /* @__PURE__ */ new Map();
	for (const record of catalog.records) {
		if (record.document.state !== "active") continue;
		if (urls.has(record.document.fileName)) throw new Error(`Two active assets are named ${record.document.fileName}.`);
		urls.set(record.document.fileName, assetAuthoringUrl(record.id));
	}
	return Object.fromEntries(urls);
}
//#endregion
export { COMPOSITION_PROVIDER_ID, CONTENT_PROVIDER_ID, DEFAULT_TIMESTAMP, MAPPING_PROVIDER_ID, SITEMAP_PROVIDER_ID, assetAuthoringUrl, assetMimeTypeForExtension, canonicalStringifyJson, createFilesystemAssetStore, defineSite, entryRef, node, readAssetUrls, slugify, validateSiteProject };
