// Generated by pnpm build:public. Edit server/public and its source dependencies.
import { JsonValue, ComponentPackManifest, TrustedComponentPack } from '@zudo-composer/component-contract';
import { Stats, Dirent } from 'node:fs';
import { FileHandle, link } from 'node:fs/promises';

/** A persisted record id in its provider's namespace. */
type RecordId = string;

/** A JSON object — the shape of a node's `props`. */
type JsonObject = {
    [key: string]: JsonValue;
};
/** The only Composition document schema version this build understands. */
declare const COMPOSITION_SCHEMA_VERSION: 2;
type CompositionSchemaVersion = typeof COMPOSITION_SCHEMA_VERSION;
/** A single persisted node in a Composition tree. */
interface CompositionNode {
    /** Stable, unique node id (persisted document key). */
    id: string;
    /** Stable component id — looked up in the manifest. */
    componentId: string;
    /** Component schema version this node was authored against. */
    componentVersion: number;
    /** JSON-safe scalar props. */
    props: JsonObject;
    /** Stable slot id → ordered child nodes. */
    slots: Record<string, CompositionNode[]>;
}
/** The real component slot a Global template exposes to its consumers. */
interface GlobalTemplateOutletTarget {
    /** Id of the component node that owns the exposed slot. Never the virtual root. */
    parentId: string;
    /** Stable manifest slot id on `parentId`. */
    slotId: string;
}
/**
 * The single named projection point a Global template exposes in schema v2.
 * `id` is machine-stable; changing the human label or target never reissues it.
 */
interface GlobalTemplateOutlet {
    id: string;
    label: string;
    target: GlobalTemplateOutletTarget;
}
/** Publish this Composition as a live, one-outlet Global template. */
interface GlobalTemplatePublication {
    kind: "global-template";
    outlet: GlobalTemplateOutlet;
}
/** Publish this Composition as a detached-clone Pattern. */
interface PatternPublication {
    kind: "pattern";
}
/**
 * Reuse role persisted on a Composition. Absence means an ordinary local-only
 * Composition. The union deliberately contains no generic reference node.
 */
type CompositionPublication = GlobalTemplatePublication | PatternPublication;
/**
 * A consumer's stable link to one source outlet. Provider identity is omitted:
 * the containing record's active provider supplies that at resolution time.
 */
interface CompositionBinding {
    sourceRecordId: RecordId;
    outletId: string;
}
/** The full persisted Composition document in the current schema. */
interface CompositionDocument {
    schemaVersion: CompositionSchemaVersion;
    id: string;
    name: string;
    /**
     * The virtual root's children. `root` is an insertion slot only — the array
     * itself is NOT a node and has no id/props/component.
     */
    root: CompositionNode[];
    /** Optional reusable-source role. Mutually exclusive with `binding` semantically. */
    publication?: CompositionPublication;
    /** Optional live source binding. The local `root` remains canonical. */
    binding?: CompositionBinding;
}

/** A persisted composition and its storage metadata. */
interface CompositionRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: CompositionDocument;
}
declare const COMPOSITION_PROVIDER_IDS: {
    readonly files: "files";
};
type CompositionProviderId = (typeof COMPOSITION_PROVIDER_IDS)[keyof typeof COMPOSITION_PROVIDER_IDS];
/** A provider-qualified identity. Record ids are unique only inside a provider. */
interface CompositionRecordRef {
    providerId: CompositionProviderId;
    recordId: RecordId;
}

/** Produces a fresh, unique node or record id on each call. */
type IdFactory = (hint?: string) => string;

declare const CONTENT_MODEL_SCHEMA_VERSION: 1;
declare const CONTENT_ENTRY_SCHEMA_VERSION: 1;
type ContentModelKind = "collection" | "single";
interface ContentRecordRef {
    providerId: string;
    recordId: RecordId;
}
/**
 * Stable authoring identity for a managed asset.
 *
 * Content deliberately does not persist a versionId: the current Asset head
 * may change while a draft is being edited. The provider-qualified shape is
 * shared structurally with AssetAssetRef so release can add an exact version
 * without losing which Asset provider owns the asset.
 */
type ContentAssetRef = {
    providerId: string;
    assetId: string;
};
type ContentAssetUse = {
    kind: "image";
    asset: ContentAssetRef;
    alt: string;
    decorative: boolean;
    caption: string;
} | {
    kind: "link";
    asset: ContentAssetRef;
    label: string;
} | {
    kind: "download";
    asset: ContentAssetRef;
    label: string;
    showSize: boolean;
    showType: boolean;
} | {
    kind: "card";
    asset: ContentAssetRef;
    title: string;
    description: string;
};
type ContentValueSchema = {
    kind: "text" | "long-text" | "markdown" | "number" | "boolean" | "date" | "slug" | "color" | "url";
} | {
    kind: "choice";
    options: {
        value: string;
        label: string;
    }[];
} | {
    kind: "reference";
    target: ContentRecordRef;
} | {
    kind: "reference-list";
    target: ContentRecordRef;
    ordered: boolean;
} | {
    kind: "object";
    fields: ContentFieldDefinition[];
} | {
    kind: "list";
    item: ContentValueSchema;
} | {
    kind: "asset-use";
    use: ContentAssetUse["kind"];
};
type ContentFieldDefinition = {
    id: RecordId;
    key: string;
    label: string;
    required: boolean;
} & ContentValueSchema;
/** Inverses are presentation metadata. Only the named owning field stores edges. */
interface ContentInverseDefinition {
    id: string;
    label: string;
    source: ContentRecordRef;
    fieldId: string;
}
interface ContentPresentation {
    groups: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    views: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    inverses: ContentInverseDefinition[];
}
interface ContentModelDocument {
    schemaVersion: typeof CONTENT_MODEL_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    description: string;
    kind: ContentModelKind;
    fields: ContentFieldDefinition[];
    presentation?: ContentPresentation;
}
interface ContentModelRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: ContentModelDocument;
}
interface ContentEntryRecord {
    schemaVersion: typeof CONTENT_ENTRY_SCHEMA_VERSION;
    id: RecordId;
    modelId: RecordId;
    createdAt: string;
    updatedAt: string;
    values: Record<RecordId, JsonValue>;
    lifecycle: "draft" | "published";
    /** Storage assigns a new generation atomically for every entry mutation. */
    generation: number;
}

interface ContentModelRef {
    providerId: string;
    recordId: string;
}

declare const MAPPING_SCHEMA_VERSION: 2;
type MappingMode = {
    kind: "single";
} | {
    kind: "collection";
    query: MappingCollectionQuery;
};
type MappingCollectionConditionOperator = "equals" | "not-equals" | "contains" | "exists";
interface MappingCollectionCondition {
    fieldId: RecordId;
    operator: MappingCollectionConditionOperator;
    value?: JsonValue;
}
interface MappingCollectionSort {
    fieldId: RecordId;
    direction: "asc" | "desc";
}
interface MappingCollectionPin {
    providerId: string;
    modelId: RecordId;
    recordId: RecordId;
}
interface MappingCollectionQuery {
    publication: "published-only" | "include-drafts";
    conditions: MappingCollectionCondition[];
    sort: MappingCollectionSort[];
    pins: MappingCollectionPin[];
    limit: number;
}
interface MappingTarget {
    nodeId: string;
    prop: string;
}
type MappingSourceProjection = {
    kind: "value";
} | {
    kind: "object-field";
    fieldIds: readonly RecordId[];
} | {
    kind: "asset-ref";
} | {
    kind: "asset-download";
} | {
    kind: "asset-text";
    field: "alt" | "caption" | "label" | "title" | "description";
} | {
    kind: "reference-id";
} | {
    kind: "reference-list-ids";
} | {
    kind: "route-link";
};
type MappingTransform =
/** Preserve the scalar value exactly when the source and target domains agree. */
{
    kind: "identity";
}
/** Format a canonical Content date string as a medium, UTC-stable display date. */
 | {
    kind: "date-medium";
}
/** Keep 160 Unicode code points from longer Content, then append an ellipsis. */
 | {
    kind: "truncate-160";
}
/** Add a configured label/decorator before string-producing Content. */
 | {
    kind: "prefix";
    prefix: string;
};
interface MappingBinding {
    id: RecordId;
    sourceFieldId: RecordId;
    projection: MappingSourceProjection;
    target: MappingTarget;
    transform: MappingTransform;
}
interface MappingDocument {
    schemaVersion: typeof MAPPING_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    contentModel: ContentModelRef;
    composition: CompositionRecordRef;
    mode: MappingMode;
    bindings: MappingBinding[];
}
interface MappingRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: MappingDocument;
}

/** The only Sitemap document schema version understood by this build. */
declare const SITEMAP_SCHEMA_VERSION: 3;
type SitemapSchemaVersion = typeof SITEMAP_SCHEMA_VERSION;
/** A stable reference to a saved Composer composition. */
interface CompositionRef {
    providerId: string;
    recordId: RecordId;
}
/** A stable reference to a saved Mapping. */
interface MappingRef {
    providerId: string;
    recordId: RecordId;
}
type MappingRoute = {
    kind: "single";
} | {
    kind: "selected-entry";
    entry: SitemapEntryRef;
} | {
    kind: "entry-field";
    fieldId: RecordId;
    titleFieldId?: RecordId;
};
interface SitemapEntryRef {
    providerId: string;
    modelId: string;
    recordId: RecordId;
}
interface SitemapAncestorSelection {
    nodeId: string;
    entry: SitemapEntryRef;
}
type SitemapNavigationDestination = {
    kind: "route";
    nodeId: string;
    entry?: SitemapEntryRef;
    ancestors?: SitemapAncestorSelection[];
} | {
    kind: "external";
    url: string;
};
interface SitemapNavigationItem {
    id: string;
    label: string;
    visible: boolean;
    destination: SitemapNavigationDestination;
}
interface SitemapNavigation {
    primary: SitemapNavigationItem[];
    footer: SitemapNavigationItem[];
}
/** Every authored page has one explicit, persisted source. */
type SitemapPageSource = {
    kind: "unassigned";
} | {
    kind: "composition";
    ref: CompositionRef;
} | {
    kind: "mapping";
    ref: MappingRef;
    route: MappingRoute;
};
/** One authored page in the sitemap tree. Mapping Entries are never persisted here. */
interface SitemapNode {
    id: string;
    title: string;
    slug?: string;
    source: SitemapPageSource;
    notes?: string;
    children: SitemapNode[];
}
/** The complete persisted Sitemap document. */
interface SitemapDocument {
    schemaVersion: SitemapSchemaVersion;
    id: string;
    name: string;
    navigation: SitemapNavigation;
    /** Virtual insertion slot. The array itself is never a page node. */
    root: SitemapNode[];
}

/** A persisted sitemap and its storage metadata. */
interface SitemapRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: SitemapDocument;
}

/**
 * Stable SiteProject provider ids and their current browser-provider ids.
 *
 * Authoring persists to the host project's files, so every domain names its
 * filesystem provider. Keeping the mapping explicit prevents adapters from
 * accepting arbitrary provider strings and leaves the portable contract
 * independent of browser provider construction; the two identities happen to
 * match again today.
 */
declare const SITE_PROJECT_PROVIDER_REGISTRY: Readonly<{
    readonly compositions: Readonly<{
        files: Readonly<{
            logicalId: "files";
            browserProviderId: "files";
        }>;
    }>;
    readonly content: Readonly<{
        "content-filesystem": Readonly<{
            logicalId: "content-filesystem";
            browserProviderId: "content-filesystem";
        }>;
    }>;
    readonly mappings: Readonly<{
        "mapping-filesystem": Readonly<{
            logicalId: "mapping-filesystem";
            browserProviderId: "mapping-filesystem";
        }>;
    }>;
    readonly sitemaps: Readonly<{
        "sitemap-filesystem": Readonly<{
            logicalId: "sitemap-filesystem";
            browserProviderId: "sitemap-filesystem";
        }>;
    }>;
}>;
type SiteProjectDomain = keyof typeof SITE_PROJECT_PROVIDER_REGISTRY;
type SiteProjectProviderId<TDomain extends SiteProjectDomain> = keyof (typeof SITE_PROJECT_PROVIDER_REGISTRY)[TDomain] & string;

declare const SITE_PROJECT_SCHEMA_VERSION: 2;
interface SiteProjectCollectionAttachment {
    id: RecordId;
    /** Deterministic authored ordering across distinct target slots. */
    order: number;
    composition: SiteProjectRecordRef<SiteProjectProviderId<"compositions">>;
    target: {
        nodeId: string;
        slotId: string;
    };
    mapping: SiteProjectRecordRef<SiteProjectProviderId<"mappings">>;
}
interface SiteProjectComponentPackRequirement {
    contractVersion: ComponentPackManifest["contractVersion"];
    packId: string;
    packVersion: string;
}
interface SiteProjectRecordRef<TProviderId extends string = string> {
    providerId: TProviderId;
    recordId: RecordId;
}
interface SiteProjectCompositionProvider {
    id: SiteProjectProviderId<"compositions">;
    records: CompositionRecord[];
}
interface SiteProjectContentProvider {
    id: SiteProjectProviderId<"content">;
    models: ContentModelRecord[];
    entries: ContentEntryRecord[];
}
interface SiteProjectMappingProvider {
    id: SiteProjectProviderId<"mappings">;
    records: MappingRecord[];
}
interface SiteProjectSitemapProvider {
    id: SiteProjectProviderId<"sitemaps">;
    records: SitemapRecord[];
}
interface SiteProjectProviders {
    compositions: SiteProjectCompositionProvider[];
    content: SiteProjectContentProvider[];
    mappings: SiteProjectMappingProvider[];
    sitemaps: SiteProjectSitemapProvider[];
}
/** The portable, JSON-safe whole-site aggregate. */
interface SiteProject {
    schemaVersion: typeof SITE_PROJECT_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    componentPack: SiteProjectComponentPackRequirement;
    providers: SiteProjectProviders;
    activeSitemap: SiteProjectRecordRef<SiteProjectProviderId<"sitemaps">>;
    collectionAttachments: SiteProjectCollectionAttachment[];
}
type SiteProjectDiagnosticSeverity = "error";
type SiteProjectDiagnosticCode = "invalid-project" | "invalid-keys" | "not-json-safe" | "future-schema" | "invalid-schema-version" | "unsafe-id" | "invalid-name" | "invalid-component-pack" | "component-pack-mismatch" | "invalid-provider" | "unknown-provider" | "duplicate-provider" | "duplicate-record" | "malformed-record" | "component-pack-incompatible" | "dangling-composition-binding" | "invalid-composition-binding" | "invalid-active-sitemap" | "dangling-content-model" | "wrong-content-provider" | "dangling-entry-field" | "invalid-entry-value" | "single-content-cardinality" | "dangling-mapping-reference" | "wrong-mapping-provider" | "dangling-mapping-field" | "dangling-mapping-target" | "dangling-sitemap-reference" | "wrong-sitemap-provider" | "dangling-sitemap-route-field" | "dangling-sitemap-title-field" | "invalid-sitemap-title-field" | "invalid-sitemap-selected-entry" | "invalid-collection-attachment" | "duplicate-collection-attachment" | "attachment-composition-not-found" | "attachment-mapping-not-found" | "attachment-mapping-not-collection" | "attachment-target-not-found" | "attachment-slot-not-found" | "attachment-slot-conflict";
interface SiteProjectDiagnostic {
    severity: SiteProjectDiagnosticSeverity;
    code: SiteProjectDiagnosticCode;
    message: string;
    /** Canonical JSONPath into the SiteProject input. */
    path: string;
}
interface SiteProjectValidationContext {
    /** Manifest-only public component-pack data. Runtime component functions are never accepted. */
    componentPack: ComponentPackManifest;
}
type SiteProjectValidation = {
    ok: true;
    project: SiteProject;
    diagnostics: readonly [];
} | {
    ok: false;
    diagnostics: readonly SiteProjectDiagnostic[];
};

declare const COMPOSITION_PROVIDER_ID = "files";
declare const CONTENT_PROVIDER_ID = "content-filesystem";
declare const MAPPING_PROVIDER_ID = "mapping-filesystem";
declare const SITEMAP_PROVIDER_ID = "sitemap-filesystem";
/** Every generated record carries one fixed timestamp so regeneration is byte-stable. */
declare const DEFAULT_TIMESTAMP = "2026-09-12T00:00:00.000Z";
/** `Product card` → `product-card`; matches the tool's safe record-id pattern. */
declare function slugify(name: string): string;
interface NodeInput {
    id?: string;
    componentId: string;
    props?: JsonObject;
    slots?: Record<string, NodeInput[]>;
}
/** One composition node. Omitted ids are derived per composition from the component id and position. */
declare function node(componentId: string, props?: JsonObject, slots?: Record<string, NodeInput[]>, id?: string): NodeInput;
interface TemplateInput {
    id?: string;
    name: string;
    root: NodeInput[];
    outlet: {
        id?: string;
        label?: string;
        target: {
            parentId: string;
            slotId: string;
        };
    };
}
interface Template {
    id: string;
    outlet: GlobalTemplateOutlet;
    record: CompositionRecord;
}
interface PageInput {
    id?: string;
    name: string;
    root: NodeInput[];
    /** Bind this page into a global template's outlet. A detached page (no template) is what a collection mapping needs. */
    template?: Template;
}
interface Page {
    id: string;
    record: CompositionRecord;
}
type FieldInput = {
    /** Stable persisted identity; omitted ids derive from the model and field key. */
    id?: string;
    key: string;
    label?: string;
    required?: boolean;
} & ({
    kind: "text" | "long-text" | "markdown" | "number" | "boolean" | "date" | "slug" | "color" | "url";
} | {
    kind: "choice";
    options: {
        value: string;
        label: string;
    }[];
} | {
    kind: "reference";
    target: Model;
} | {
    kind: "reference-list";
    target: Model;
    ordered?: boolean;
} | {
    kind: "object";
    fields: FieldInput[];
} | {
    kind: "list";
    item: ContentValueSchema;
} | {
    kind: "asset-use";
    use: "image" | "link" | "download" | "card";
});
interface ModelInput {
    id?: string;
    name: string;
    kind: "single" | "collection";
    description?: string;
    fields: FieldInput[];
}
interface Model {
    id: string;
    record: ContentModelRecord;
    /** Field key → field id, the lookup every entry, mapping and sitemap route uses. */
    fieldId(key: string): string;
}
interface EntryInput {
    id?: string;
    /** Values keyed by field KEY. `reference` / `reference-list` values are `entryRef(...)` objects. */
    values: Record<string, JsonValue>;
    lifecycle?: "draft" | "published";
}
interface Entry {
    id: string;
    modelId: string;
    record: ContentEntryRecord;
}
interface BindingInput {
    field: string;
    nodeId: string;
    prop: string;
    projection?: MappingSourceProjection;
    transform?: MappingTransform;
    id?: string;
}
interface CollectionModeInput {
    kind: "collection";
    sort?: {
        field: string;
        direction: "asc" | "desc";
    }[];
    limit?: number;
    publication?: MappingCollectionQuery["publication"];
    conditions?: {
        field: string;
        operator: MappingCollectionQuery["conditions"][number]["operator"];
        value?: JsonValue;
    }[];
}
interface MappingInput {
    id?: string;
    name: string;
    model: Model;
    composition: Page;
    mode?: {
        kind: "single";
    } | CollectionModeInput;
    bindings: BindingInput[];
}
interface Mapping {
    id: string;
    model: Model;
    composition: Page;
    record: MappingRecord;
}
interface Attachment {
    id: string;
    record: SiteProjectCollectionAttachment;
}
type RouteSource = {
    page: Page;
} | {
    mapping: Mapping;
    route?: "single";
} | {
    mapping: Mapping;
    route: "entry-field";
    field: string;
    titleField?: string;
};
type RouteInput = {
    id?: string;
    title: string;
    slug?: string;
    notes?: string;
    children?: RouteInput[];
} & RouteSource;
interface NavigationRef {
    route: RouteInput;
    label?: string;
    visible?: boolean;
    id?: string;
}
interface SitemapInput {
    id?: string;
    name: string;
    root: RouteInput;
    navigation?: {
        primary?: NavigationRef[];
        footer?: NavigationRef[];
    };
}
interface SiteOptions {
    id: string;
    name: string;
    componentPack: TrustedComponentPack | {
        manifest: ComponentPackManifest;
    };
    timestamp?: string;
    /**
     * Order only the aggregate's composition records by ID; defaults to declaration
     * order. Other record collections and all document sequences keep their order.
     */
    compositionOrder?: "id";
}
interface Site {
    readonly id: string;
    readonly name: string;
    readonly manifest: ComponentPackManifest;
    template(input: TemplateInput): Template;
    page(input: PageInput): Page;
    model(input: ModelInput): Model;
    entry(model: Model, input: EntryInput): Entry;
    mapping(input: MappingInput): Mapping;
    /**
     * Materialise a collection mapping's composition once per entry into a named
     * slot of `target.nodeId`. The node's owner composition is found among the
     * pages and templates declared so far; pass `composition` when the node id
     * appears in more than one.
     */
    attach(mapping: Mapping, target: {
        nodeId: string;
        slotId: string;
        composition?: Page | Template;
    }, id?: string): Attachment;
    sitemap(input: SitemapInput): SitemapRecord;
    toSiteProject(): SiteProject;
}
declare function defineSite(options: SiteOptions): Site;
/** The provider-qualified value a `reference` field stores (a `reference-list` stores an array of them). */
declare function entryRef(entry: Entry): {
    providerId: string;
    modelId: string;
    recordId: string;
};

/**
 * File name → canonical authoring URL for the active assets in a resolved host
 * config. Use `loadHostContext()` from `zudo-composer/vite` to resolve that config.
 * Asset ids are minted at upload, so authored sites look them up by file name.
 */
declare function readAssetUrls(config: {
    paths: {
        assets: string;
    };
}): Record<string, string>;

declare const ASSET_TYPES: readonly ["image/png", "image/jpeg", "image/gif", "image/webp", "application/pdf", "application/zip", "text/plain", "text/csv", "application/json"];
declare function assetMimeTypeForExtension(extension: string): string | undefined;

/** The only Assets document schema understood by this build. */
declare const ASSET_SCHEMA_VERSION: 1;
type AssetSchemaVersion = typeof ASSET_SCHEMA_VERSION;
type AssetType = (typeof ASSET_TYPES)[number];
/** Persisted Assets metadata. Binary bytes are stored by providers separately. */
interface AssetDocument {
    schemaVersion: AssetSchemaVersion;
    id: RecordId;
    fileName: string;
    folderId: string | null;
    note: string;
    state: "active" | "trash";
    currentVersionId: string;
    versions: AssetVersion[];
}
interface AssetVersion {
    /** SHA-256 identifies immutable bytes, independently of the mutable head. */
    id: string;
    mimeType: AssetType;
    byteLength: number;
    checksum: string;
    url: string;
    createdAt: string;
}
/** The canonical record envelope persisted by a Assets provider. */
interface AssetRecord {
    id: RecordId;
    revision: number;
    createdAt: string;
    updatedAt: string;
    document: AssetDocument;
}
interface AssetFolder {
    id: string;
    parentId: string | null;
    name: string;
    state: "active" | "trash";
    revision: number;
    createdAt: string;
    updatedAt: string;
}
/** One atomic global metadata snapshot, separate from SiteProject providers. */
interface AssetSnapshot {
    schemaVersion: AssetSchemaVersion;
    mutationToken: string;
    records: AssetRecord[];
    folders: AssetFolder[];
}
/** Stable provider-qualified identity used by authoring references. */
interface AssetAssetRef {
    providerId: string;
    assetId: string;
}
/** Exact immutable version identity used by release/pin operations. */
interface AssetVersionRef extends AssetAssetRef {
    versionId: string;
}
interface AssetVersionPin extends AssetVersionRef {
    checksum: string;
    byteLength: number;
    mimeType: AssetType;
    url: string;
}
interface AssetPinManifest {
    schemaVersion: 1;
    pins: AssetVersionPin[];
}
/** Authoring references retain asset identity; release uses exact version URLs. */
declare function assetAuthoringUrl(assetId: string): string;

type AssetValidationCode = "invalid-record" | "unsafe-id" | "id-mismatch" | "invalid-timestamp" | "invalid-timestamp-order" | "not-json-safe" | "malformed-document" | "future-schema" | "invalid-file-name" | "invalid-mime-type" | "invalid-byte-length" | "invalid-checksum";
interface AssetValidationIssue {
    code: AssetValidationCode;
    message: string;
    path?: string;
    foundSchemaVersion?: number;
}

type AssetBytesMissingReason = "missing" | "checksum-mismatch";
type AssetLoadOutcome<T = AssetRecord> = {
    status: "loaded";
    record: T;
} | {
    status: "not-found";
    id: string;
} | {
    status: "invalid";
    issue: AssetValidationIssue;
    raw: unknown;
} | {
    status: "future-schema";
    foundSchemaVersion: number;
    raw: unknown;
} | {
    status: "bytes-missing";
    record: T;
    reason?: AssetBytesMissingReason;
};

/** Provider identities are data, not application-layer implementations. */
interface AssetProviderDescriptor {
    readonly id: string;
    readonly label: string;
}
/** The inexpensive representation used by library listings. */
interface AssetSummary {
    id: RecordId;
    fileName: string;
    mimeType: AssetType;
    byteLength: number;
    checksum: string;
    createdAt: string;
    updatedAt: string;
    revision: number;
    folderId: string | null;
    note: string;
    state: "active" | "trash";
    versionId: string;
    url: string;
    authoringUrl: string;
}
/** Bytes never travel through a persisted AssetRecord. */
type AssetByteSource = Uint8Array | ArrayBuffer | ReadableStream<Uint8Array> | AsyncIterable<Uint8Array>;
type AssetPersistenceOperation = "initialize" | "list" | "get" | "put" | "delete" | "seed" | "snapshot" | "replace" | "metadata" | "folder" | "trash" | "restore" | "pin" | "clear";
type AssetPersistenceErrorCode = "unavailable" | "blocked" | "versionchange" | "unsupported-version" | "validation" | "conflict" | "recovery-required" | "commit-uncertain" | "not-found" | "bytes-missing" | "read-failed" | "write-failed" | "transaction-failed" | "unknown";
/** Provider-neutral persistence failure. */
declare class AssetPersistenceError extends Error {
    readonly operation: AssetPersistenceOperation;
    readonly code: AssetPersistenceErrorCode;
    readonly retryable: boolean;
    readonly name = "AssetPersistenceError";
    constructor(operation: AssetPersistenceOperation, code: AssetPersistenceErrorCode, message: string, retryable: boolean, options?: {
        cause?: unknown;
    });
}
interface AssetStore {
    readonly provider: AssetProviderDescriptor;
    list(): Promise<readonly AssetSummary[]>;
    get(id: string): Promise<AssetLoadOutcome>;
    /** `bytes` is separate from JSON metadata and may be a streaming source. */
    put(record: AssetRecord, bytes: AssetByteSource): Promise<void>;
    /** Soft trash only. Missing preconditions are rejected, never guessed. */
    delete(id: string, precondition?: AssetMutationPrecondition): Promise<boolean>;
    /** Optional fixture convenience; filesystem providers need not implement it. */
    seed?(seed: AssetSeed): Promise<void>;
    clear(): Promise<void>;
}
interface AssetMutationPrecondition {
    expectedRevision: number;
    /** Optional provider-wide CAS in addition to mandatory record/folder CAS. */
    expectedMutationToken?: string;
}
interface AssetMetadataPatch {
    fileName?: string;
    folderId?: string | null;
    note?: string;
}
interface AssetFolderPatch {
    name?: string;
    parentId?: string | null;
    index?: number;
}
interface AssetListOptions {
    state?: "active" | "trash" | "all";
    folderId?: string | null;
}
declare const ASSET_VERSIONED_CAPABILITIES: Readonly<{
    readonly folders: true;
    readonly metadata: true;
    readonly replace: true;
    readonly trash: true;
    readonly restore: true;
    readonly exactVersions: true;
    readonly snapshot: true;
    readonly permanentDelete: false;
}>;
interface VersionedAssetStore extends AssetStore {
    readonly capabilities: typeof ASSET_VERSIONED_CAPABILITIES;
    list(options?: AssetListOptions): Promise<readonly AssetSummary[]>;
    snapshot(): Promise<AssetSnapshot>;
    mutationToken(): Promise<string>;
    updateMetadata(id: string, patch: AssetMetadataPatch, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    trash(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    restore(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    createFolder(input: {
        name: string;
        parentId: string | null;
        index?: number;
    }, expectedMutationToken: string): Promise<AssetFolder>;
    updateFolder(id: string, patch: AssetFolderPatch, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    trashFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    restoreFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    /** Reads and verifies retained bytes even when the asset is in trash. */
    resolveVersion(ref: AssetVersionRef): Promise<AssetVersionPin>;
    pinManifest(refs: readonly AssetVersionRef[]): Promise<AssetPinManifest>;
}
interface AssetSeed {
    readonly records: readonly AssetRecord[];
    /** Optional fixture/provider byte payloads keyed by record id. */
    readonly bytes?: Readonly<Record<string, AssetByteSource>>;
}
type AssetRecoveryReason = "invalid" | "future-schema";
interface AssetRecoveryOutcome {
    kind: "quarantined";
    reason: AssetRecoveryReason;
    sourcePreserved: true;
    affectedRecordIds: readonly string[];
    foundSchemaVersion?: number;
    message: string;
}
type AssetInitializationOutcome = {
    status: "ready";
    summaries: readonly AssetSummary[];
} | {
    status: "recovery-required";
    summaries: readonly AssetSummary[];
    recovery: AssetRecoveryOutcome;
} | {
    status: "error";
    error: AssetPersistenceError;
};

interface SafeRootFilesystemOperations {
    mkdir(path: string, options: {
        recursive: true;
    }): Promise<unknown>;
    lstat(path: string): Promise<Stats>;
    realpath(path: string): Promise<string>;
    readdir(path: string, options: {
        withFileTypes: true;
    }): Promise<Dirent[]>;
    open(path: string, flags: number, mode?: number): Promise<FileHandle>;
    rename(oldPath: string, newPath: string): Promise<void>;
    unlink(path: string): Promise<void>;
    rmdir(path: string): Promise<void>;
}

interface FilesystemAssetStoreOperations extends SafeRootFilesystemOperations {
    link: typeof link;
}
interface FilesystemAssetStoreOptions {
    /** The host's configured assets directory: `catalog.json` plus private `versions/`. */
    assetsStoreRoot: string;
    /** Test/fault-injection seam. Omitted methods use Node's filesystem. */
    operations?: Partial<FilesystemAssetStoreOperations>;
    /** Used for exclusive temporary names. */
    randomToken?: () => string;
    /** Server-side record-id source. */
    idFactory?: IdFactory;
    /** Clock used for server-created records. */
    now?: () => string;
}
interface AssetUploadInput {
    fileName: string;
    /** Binary signatures determine the persisted type; this is the explicit fallback for supported text kinds. */
    declaredMimeType: string;
    bytes: AssetByteSource;
    signal?: AbortSignal;
    folderId?: string | null;
    note?: string;
    expectedMutationToken?: string;
}
interface AssetReplaceInput {
    bytes: AssetByteSource;
    signal?: AbortSignal;
    declaredMimeType?: string;
}

declare class FilesystemAssetStore implements VersionedAssetStore {
    private readonly filesystem;
    private readonly bytesDirectory;
    private readonly idFactory;
    private readonly now;
    private readonly publishVersion;
    readonly provider: {
        readonly id: "asset-files";
        readonly label: "Project files";
    };
    readonly capabilities: Readonly<{
        readonly folders: true;
        readonly metadata: true;
        readonly replace: true;
        readonly trash: true;
        readonly restore: true;
        readonly exactVersions: true;
        readonly snapshot: true;
        readonly permanentDelete: false;
    }>;
    private constructor();
    static create(options: FilesystemAssetStoreOptions): Promise<FilesystemAssetStore>;
    initialize(): Promise<AssetInitializationOutcome>;
    snapshot(): Promise<AssetSnapshot>;
    mutationToken(): Promise<string>;
    list(options?: AssetListOptions): Promise<readonly AssetSummary[]>;
    get(id: string): Promise<AssetLoadOutcome>;
    upload(input: AssetUploadInput): Promise<AssetRecord>;
    replace(id: string, input: AssetReplaceInput, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    /** Import is create-only, never a replacement bypass. */
    put(record: AssetRecord, bytes: AssetByteSource): Promise<void>;
    updateMetadata(id: string, patch: AssetMetadataPatch, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    trash(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    restore(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    delete(id: string, precondition?: AssetMutationPrecondition): Promise<boolean>;
    clear(): Promise<void>;
    createFolder(input: {
        name: string;
        parentId: string | null;
        index?: number;
    }, expectedMutationToken: string): Promise<AssetFolder>;
    updateFolder(id: string, patch: AssetFolderPatch, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    private placeFolder;
    trashFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    restoreFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    resolveVersion(ref: AssetVersionRef): Promise<AssetVersionPin>;
    pinManifest(refs: readonly AssetVersionRef[]): Promise<AssetPinManifest>;
    private resolveFromSnapshot;
    private editRecord;
    private editFolder;
    private assertPrecondition;
    private requireRecord;
    private timestamp;
    private bump;
    private mintId;
    private catalogPath;
    private versionPath;
    private assertCatalog;
    private readCatalog;
    /** Kernel O_EXCL serializes cooperating writers across processes. Never steal
     * an existing lock: after a crash verify no writer is running before manual
     * .mutation.lock removal. Reads remain available during lock recovery.
     *
     * The whole catalog is one document, so a mutation touching several records
     * commits with the single rename inside commitDocument or not at all. */
    private mutate;
    private syncDirectory;
    private stageBytes;
    private commitBytes;
    private removeStage;
    private assertDirectories;
    private assertSafeId;
    private verifyBytes;
}
declare function createFilesystemAssetStore(options: FilesystemAssetStoreOptions): Promise<FilesystemAssetStore>;

/** Canonical JSON text for any already validated JSON-safe value. */
declare function canonicalStringifyJson(value: JsonValue): string;

/** Strictly validates a SiteProject and every cross-domain graph edge. */
declare function validateSiteProject(value: unknown, context: SiteProjectValidationContext): SiteProjectValidation;

export { COMPOSITION_PROVIDER_ID, CONTENT_PROVIDER_ID, DEFAULT_TIMESTAMP, MAPPING_PROVIDER_ID, SITEMAP_PROVIDER_ID, assetAuthoringUrl, assetMimeTypeForExtension, canonicalStringifyJson, createFilesystemAssetStore, defineSite, entryRef, node, readAssetUrls, slugify, validateSiteProject };
