// Generated by pnpm build:public. Edit server/public and its source dependencies.
/**
 * Every setting a host may declare. Path settings are relative to the host
 * project root; `pack` is a module specifier.
 *
 * All fields are required. A resolved config always carries the complete table,
 * which is what makes the shallow top-level merge in `composer()` safe: a
 * supplied object replaces the default wholesale rather than leaving holes.
 */
interface ComposerSettings {
    /**
     * Root for the CMS data domains. Changing it re-bases every domain directory
     * below that has not been set explicitly, so a host can move all CMS data
     * with one setting.
     *
     * @default "cms"
     */
    dataDir: string;
    /**
     * Composition JSON, including global templates.
     *
     * @default "cms/compositions"
     */
    compositionsDir: string;
    /**
     * Content-domain JSON.
     *
     * @default "cms/content"
     */
    contentDir: string;
    /**
     * Mapping-domain JSON.
     *
     * @default "cms/mappings"
     */
    mappingsDir: string;
    /**
     * Sitemapper-domain JSON.
     *
     * @default "cms/sitemaps"
     */
    sitemapsDir: string;
    /**
     * Assets content-addressed store: `catalog.json` plus `versions/`.
     *
     * @default "cms/assets"
     */
    assetsDir: string;
    /**
     * Published assets bytes the host commits and serves. Not re-based by
     * `dataDir` — it lives under the host's public directory, not its CMS data.
     *
     * @default "public/uploaded-assets"
     */
    publicAssetsDir: string;
    /**
     * The host's base CSS entry. It is the sole importer of the component pack's
     * CSS and the host's Tailwind `@source` declaration point.
     *
     * @default "styles/base.css"
     */
    styles: string;
    /**
     * Component-pack module specifier — a themeset package
     * (`"@acme/themeset/composer-pack"`) or a host self-reference
     * (`"my-site/components"`, backed by the host's own `exports` map).
     *
     * Required, with no default. zudo-composer never falls back to a bundled
     * provider pack.
     */
    pack: string;
}
/** The settings that carry a default. `pack` is required and has none. */
type ComposerSettingDefaults = Omit<ComposerSettings, "pack">;

/**
 * Values a caller may supply that are not settings. They are absolute machine
 * paths, so they are peeled off before the merge and never reach `settings`.
 */
interface ComposerConfigOverrides {
    /** Absolute host project root. Defaults to `process.cwd()`. */
    workspaceRoot?: string;
    /** Absolute path of the config file, used in resolution error messages. */
    configPath?: string;
}
/**
 * What a host writes inside `defineComposerConfig({ … })`. Every path setting
 * is optional and falls back to its documented default; `pack` is required.
 */
type ComposerConfig = Partial<Omit<ComposerSettings, "pack">> & Pick<ComposerSettings, "pack"> & ComposerConfigOverrides;
/**
 * What `composer()` accepts. Looser than `ComposerConfig` because it also has
 * to describe the absent-config-file case and the `ZUDO_COMPOSER_PACK`
 * override; `pack` is enforced at resolution instead, with a loud error.
 */
type ComposerConfigInput = Partial<ComposerSettings> & ComposerConfigOverrides;
/** Absolute paths derived from the settings. Node-side only, never serialized. */
interface ComposerPaths {
    workspaceRoot: string;
    data: string;
    compositions: string;
    content: string;
    mappings: string;
    sitemaps: string;
    assets: string;
    publicAssets: string;
    styles: string;
}
interface ResolvedComposerConfig {
    /** Absolute host project root. Every relative setting resolves against it. */
    workspaceRoot: string;
    /** Absolute path of the host config file, whether or not it exists. */
    configPath: string;
    /** The complete, host-root-relative settings table. Safe to serialize. */
    settings: ComposerSettings;
    /** The same table resolved to absolute paths. */
    paths: ComposerPaths;
}
/** Options that are a test seam rather than host configuration. */
interface ComposerRuntime {
    /** Environment the per-setting overrides are read from. */
    env?: Record<string, string | undefined>;
}

declare function defineComposerConfig(config: ComposerConfig): ComposerConfig;

export { defineComposerConfig };
export type { ComposerConfig, ComposerConfigInput, ComposerConfigOverrides, ComposerPaths, ComposerRuntime, ComposerSettingDefaults, ComposerSettings, ResolvedComposerConfig };
