// Generated by pnpm build:public. Edit server/public and its source dependencies.
import { ComponentPackManifest, ComponentManifest, JsonValue, SlotCardinality, TrustedComponentPack } from '@zudo-composer/component-contract';
import { Stats, Dirent } from 'node:fs';
import { FileHandle, link } from 'node:fs/promises';
import { z } from 'zod';

/** A persisted record id in its provider's namespace. */
type RecordId = string;

/** A JSON object — the shape of a node's `props`. */
type JsonObject = {
    [key: string]: JsonValue;
};
/** The only Composition document schema version this build understands. */
declare const COMPOSITION_SCHEMA_VERSION: 2;
type CompositionSchemaVersion = typeof COMPOSITION_SCHEMA_VERSION;
/** A single persisted node in a Composition tree. */
interface CompositionNode {
    /** Stable, unique node id (persisted document key). */
    id: string;
    /** Stable component id — looked up in the manifest. */
    componentId: string;
    /** Component schema version this node was authored against. */
    componentVersion: number;
    /** JSON-safe scalar props. */
    props: JsonObject;
    /** Stable slot id → ordered child nodes. */
    slots: Record<string, CompositionNode[]>;
}
/** The real component slot a Global template exposes to its consumers. */
interface GlobalTemplateOutletTarget {
    /** Id of the component node that owns the exposed slot. Never the virtual root. */
    parentId: string;
    /** Stable manifest slot id on `parentId`. */
    slotId: string;
}
/**
 * The single named projection point a Global template exposes in schema v2.
 * `id` is machine-stable; changing the human label or target never reissues it.
 */
interface GlobalTemplateOutlet {
    id: string;
    label: string;
    target: GlobalTemplateOutletTarget;
}
/** Publish this Composition as a live, one-outlet Global template. */
interface GlobalTemplatePublication {
    kind: "global-template";
    outlet: GlobalTemplateOutlet;
}
/** Publish this Composition as a detached-clone Pattern. */
interface PatternPublication {
    kind: "pattern";
}
/**
 * Reuse role persisted on a Composition. Absence means an ordinary local-only
 * Composition. The union deliberately contains no generic reference node.
 */
type CompositionPublication = GlobalTemplatePublication | PatternPublication;
/**
 * A consumer's stable link to one source outlet. Provider identity is omitted:
 * the containing record's active provider supplies that at resolution time.
 */
interface CompositionBinding {
    sourceRecordId: RecordId;
    outletId: string;
}
/**
 * Ephemeral constraints for the virtual consumer root.
 *
 * This deliberately contains no provider, record, or source-document data.
 * A later resolver derives the `resolved` variant from the actual exposed
 * source slot, then hands it to the same pure commands used for ordinary
 * local edits. It is never persisted in `CompositionDocument`.
 */
type RootPolicy = {
    kind: "unrestricted";
} | {
    kind: "unresolved";
} | {
    kind: "resolved";
    /** Omitted means the exposed slot accepts every available component. */
    accepts?: readonly string[];
    cardinality: SlotCardinality;
    /** Completeness requirement copied from the outlet slot; never blocks edits or export. */
    min?: number;
    /** Hard cap on consumer roots copied from the outlet slot. */
    max?: number;
    /** Where the rule comes from, for display only. */
    origin?: RootPolicyOrigin;
};
/** Display provenance of a resolved root policy: the owning container slot and template. */
interface RootPolicyOrigin {
    componentId: string;
    componentTitle: string;
    slotId: string;
    slotLabel: string;
    viaTemplate?: {
        sourceName: string;
        outletLabel: string;
    };
}
/** The full persisted Composition document in the current schema. */
interface CompositionDocument {
    schemaVersion: CompositionSchemaVersion;
    id: string;
    name: string;
    /**
     * The virtual root's children. `root` is an insertion slot only — the array
     * itself is NOT a node and has no id/props/component.
     */
    root: CompositionNode[];
    /** Optional reusable-source role. Mutually exclusive with `binding` semantically. */
    publication?: CompositionPublication;
    /** Optional live source binding. The local `root` remains canonical. */
    binding?: CompositionBinding;
}
/**
 * The provider-independent contract definition used by model commands.
 */
type ComponentDefinition = ComponentManifest;
/** Fast, read-only lookup over a set of manifest entries. */
interface ComponentCatalog {
    readonly pack: ComponentPackManifest;
    get(componentId: string): ComponentDefinition | undefined;
    has(componentId: string): boolean;
    ids(): string[];
}

/** One component kind a region accepts, with its own children rule (if any). */
interface GrammarAcceptedKind {
    id: string;
    title: string;
    description: string;
    /** `null` when the kind has no slot of its own that narrows its children. */
    accepts: string[] | null;
}
/** The container slot rule backing one template's page-kind outlet. */
interface GrammarRegion {
    outletLabel: string;
    componentId: string;
    componentTitle: string;
    slotId: string;
    slotLabel: string;
    cardinality: SlotCardinality;
    min?: number;
    max?: number;
    accepts: GrammarAcceptedKind[] | "any";
}
/** One page kind: a Global template whose outlet targets a container slot. */
interface GrammarTemplate {
    id: string;
    name: string;
    /** `null` when the outlet's target slot declares no `accepts` and no cardinality/min/max bound — any component, any count. */
    region: GrammarRegion | null;
    open: boolean;
}
/** A published Global template left out because its outlet does not resolve against the manifest. */
interface GrammarUnavailableTemplate {
    id: string;
    name: string;
    reason: string;
}
interface Grammar {
    pack: {
        id: string;
        version: string;
    };
    templates: GrammarTemplate[];
    /** Skipped templates, mirroring the resolver treating an unresolvable template as unavailable. */
    unavailableTemplates: GrammarUnavailableTemplate[];
    /** Pages bound to no template use the ordinary unrestricted virtual root. */
    openRoot: {
        accepts: "any";
    };
}

/** Produces a fresh, unique node or record id on each call. */
type IdFactory = (hint?: string) => string;

declare const ASSET_TYPES: readonly ["image/png", "image/jpeg", "image/gif", "image/webp", "application/pdf", "application/zip", "text/plain", "text/csv", "application/json"];

/** The only Assets document schema understood by this build. */
declare const ASSET_SCHEMA_VERSION: 1;
type AssetSchemaVersion = typeof ASSET_SCHEMA_VERSION;
type AssetType = (typeof ASSET_TYPES)[number];
/** Persisted Assets metadata. Binary bytes are stored by providers separately. */
interface AssetDocument {
    schemaVersion: AssetSchemaVersion;
    id: RecordId;
    fileName: string;
    folderId: string | null;
    note: string;
    state: "active" | "trash";
    currentVersionId: string;
    versions: AssetVersion[];
}
interface AssetVersion {
    /** SHA-256 identifies immutable bytes, independently of the mutable head. */
    id: string;
    mimeType: AssetType;
    byteLength: number;
    checksum: string;
    url: string;
    createdAt: string;
}
/** The canonical record envelope persisted by a Assets provider. */
interface AssetRecord {
    id: RecordId;
    revision: number;
    createdAt: string;
    updatedAt: string;
    document: AssetDocument;
}
interface AssetFolder {
    id: string;
    parentId: string | null;
    name: string;
    state: "active" | "trash";
    revision: number;
    createdAt: string;
    updatedAt: string;
}
/** One atomic global metadata snapshot, separate from SiteProject providers. */
interface AssetSnapshot {
    schemaVersion: AssetSchemaVersion;
    mutationToken: string;
    records: AssetRecord[];
    folders: AssetFolder[];
}
/** Stable provider-qualified identity used by authoring references. */
interface AssetAssetRef {
    providerId: string;
    assetId: string;
}
/** Exact immutable version identity used by release/pin operations. */
interface AssetVersionRef extends AssetAssetRef {
    versionId: string;
}
interface AssetVersionPin extends AssetVersionRef {
    checksum: string;
    byteLength: number;
    mimeType: AssetType;
    url: string;
}
interface AssetPinManifest {
    schemaVersion: 1;
    pins: AssetVersionPin[];
}

type AssetValidationCode = "invalid-record" | "unsafe-id" | "id-mismatch" | "invalid-timestamp" | "invalid-timestamp-order" | "not-json-safe" | "malformed-document" | "future-schema" | "invalid-file-name" | "invalid-mime-type" | "invalid-byte-length" | "invalid-checksum";
interface AssetValidationIssue {
    code: AssetValidationCode;
    message: string;
    path?: string;
    foundSchemaVersion?: number;
}

type AssetBytesMissingReason = "missing" | "checksum-mismatch";
type AssetLoadOutcome<T = AssetRecord> = {
    status: "loaded";
    record: T;
} | {
    status: "not-found";
    id: string;
} | {
    status: "invalid";
    issue: AssetValidationIssue;
    raw: unknown;
} | {
    status: "future-schema";
    foundSchemaVersion: number;
    raw: unknown;
} | {
    status: "bytes-missing";
    record: T;
    reason?: AssetBytesMissingReason;
};

interface PersistedSnapshot<T> {
    mutationToken: number | string;
    records: readonly T[];
}

/** A persisted composition and its storage metadata. */
interface CompositionRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: CompositionDocument;
}
/** The inexpensive representation returned by collection listings. */
interface CompositionSummary {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    nodeCount: number;
    /**
     * Reuse-list metadata. It is optional while reading a summary written by an
     * older provider; current provider summary builders populate it.
     */
    publicationKind?: "global-template" | "pattern";
    /** Stable source-scoped outlet identity for a Global template. */
    outletId?: string;
    /** Current human label for the stable Global-template outlet. */
    outletLabel?: string;
    /** Direct children of the virtual root (distinct from the recursive node count). */
    rootCount?: number;
    /**
     * Provider-list eligibility known without loading the full source. Missing
     * values are excluded conservatively by the reusable-source catalog.
     */
    reuseStatus?: "eligible" | "empty-pattern" | "invalid";
    /**
     * Files providers may report the current generated-artifact state without
     * changing the canonical document. Other providers omit it.
     */
    derivedOutput?: CompositionDerivedOutputRecordOutcome;
}
/** One generated artifact's state after a canonical record was read or saved. */
type CompositionDerivedOutputRecordOutcome = {
    recordId: RecordId;
    status: "current";
} | {
    recordId: RecordId;
    status: "repaired";
} | {
    recordId: RecordId;
    status: "blocked";
    /** Actionable, provider-sanitized explanation; never stored in canonical JSON. */
    reason: string;
    /** A stale generated artifact could not be removed and is not valid output. */
    staleArtifact?: string;
};
/**
 * A batch outcome is needed when a source change also re-evaluates its linked
 * consumers. `status` summarizes the records: blocked outranks repaired,
 * repaired outranks current.
 */
interface CompositionDerivedOutputOutcome {
    status: "current" | "repaired" | "blocked";
    records: readonly CompositionDerivedOutputRecordOutcome[];
}
/**
 * Successful persistence has two independent truths. Canonical JSON can be
 * durably saved while a generated development artifact is blocked. Providers
 * without derived artifacts return an empty current derived-output set.
 */
interface CompositionSaveOutcome {
    canonical: {
        status: "saved";
    };
    derived: CompositionDerivedOutputOutcome;
}
type CompositionPutResult = CompositionSaveOutcome;
/**
 * A current canonical consumer reported by a dependency-safe source mutation.
 * It deliberately contains only display metadata and the persisted binding;
 * callers must open a consumer before deciding whether to detach it.
 */
interface CompositionDependent {
    summary: CompositionSummary;
    binding: CompositionBinding;
}
/** A source record was either removed, absent, or kept intact for its consumers. */
type CompositionDeleteOutcome = {
    status: "deleted";
} | {
    status: "not-found";
} | {
    status: "blocked";
    dependents: readonly CompositionDependent[];
};
/** Result of removing a publication role through the provider-owned check. */
type CompositionUnpublishOutcome = {
    status: "unpublished";
} | {
    status: "not-found";
} | {
    status: "not-published";
} | {
    status: "blocked";
    dependents: readonly CompositionDependent[];
};
declare const COMPOSITION_PROVIDER_IDS: {
    readonly files: "files";
};
type CompositionProviderId = (typeof COMPOSITION_PROVIDER_IDS)[keyof typeof COMPOSITION_PROVIDER_IDS];
interface CompositionProviderDescriptor {
    id: CompositionProviderId;
    label: string;
    /** Human-readable identity for diagnostics and storage inspection. */
    storageLabel: string;
}
/** A provider-qualified identity. Record ids are unique only inside a provider. */
interface CompositionRecordRef {
    providerId: CompositionProviderId;
    recordId: RecordId;
}
type CompositionRecordValidationCode = "invalid-record" | "unsafe-id" | "record-document-id-mismatch" | "invalid-created-at" | "invalid-updated-at" | "invalid-timestamp-order" | "not-json-safe" | "malformed-document" | "future-schema";
interface CompositionRecordValidationIssue {
    code: CompositionRecordValidationCode;
    message: string;
    foundSchemaVersion?: number;
}
/** Result of decoding provider data. Storage failures are represented separately. */
type CompositionLoadOutcome = {
    status: "loaded";
    record: CompositionRecord;
    /** Present for file-provider reads; canonical loading remains successful when blocked. */
    derivedOutput?: CompositionDerivedOutputRecordOutcome;
} | {
    status: "not-found";
    id: string;
} | {
    status: "invalid";
    issue: CompositionRecordValidationIssue;
    raw: unknown;
} | {
    status: "future-schema";
    foundSchemaVersion: number;
    raw: unknown;
};
/**
 * Minimal async collection contract. Implementations must validate records at
 * their boundary and reject operational failures with
 * `CompositionPersistenceError`.
 */
interface CompositionStore {
    snapshot?(): Promise<PersistedSnapshot<CompositionRecord>>;
    mutationToken?(): Promise<number | string>;
    readonly provider: CompositionProviderDescriptor;
    list(): Promise<readonly CompositionSummary[]>;
    get(id: string): Promise<CompositionLoadOutcome>;
    put(record: CompositionRecord): Promise<CompositionPutResult>;
    delete(id: string): Promise<boolean>;
    clear(): Promise<void>;
}
/**
 * Optional capability implemented by providers that can make the dependency
 * scan and source mutation one provider-owned operation. Do not emulate this
 * from `list`/`get`/`put`: that check-then-write sequence races new consumers.
 *
 * `CompositionStore.delete` is the ordinary CRUD method for non-template
 * callers. Reuse UI must use this capability so a Global template never has a
 * blind deletion path.
 */
interface CompositionLifecycleStore extends CompositionStore {
    deleteWithDependencyCheck(id: string): Promise<CompositionDeleteOutcome>;
    unpublishWithDependencyCheck(id: string): Promise<CompositionUnpublishOutcome>;
    /**
     * Persist one lifecycle-produced record without exposing a partially saved
     * canonical document if derived-output work fails. This is intentionally not
     * a multi-record transaction and must never detach any other consumer.
     */
    saveLifecycleRecord(record: CompositionRecord): Promise<void>;
}

declare const CONTENT_MODEL_SCHEMA_VERSION: 1;
declare const CONTENT_ENTRY_SCHEMA_VERSION: 1;
type ContentModelKind = "collection" | "single";
interface ContentRecordRef {
    providerId: string;
    recordId: RecordId;
}
interface ContentEntryRef extends ContentRecordRef {
    modelId: RecordId;
}
/**
 * Stable authoring identity for a managed asset.
 *
 * Content deliberately does not persist a versionId: the current Asset head
 * may change while a draft is being edited. The provider-qualified shape is
 * shared structurally with AssetAssetRef so release can add an exact version
 * without losing which Asset provider owns the asset.
 */
type ContentAssetRef = {
    providerId: string;
    assetId: string;
};
type ContentAssetUse = {
    kind: "image";
    asset: ContentAssetRef;
    alt: string;
    decorative: boolean;
    caption: string;
} | {
    kind: "link";
    asset: ContentAssetRef;
    label: string;
} | {
    kind: "download";
    asset: ContentAssetRef;
    label: string;
    showSize: boolean;
    showType: boolean;
} | {
    kind: "card";
    asset: ContentAssetRef;
    title: string;
    description: string;
};
type ContentValueSchema = {
    kind: "text" | "long-text" | "markdown" | "number" | "boolean" | "date" | "slug" | "color" | "url";
} | {
    kind: "choice";
    options: {
        value: string;
        label: string;
    }[];
} | {
    kind: "reference";
    target: ContentRecordRef;
} | {
    kind: "reference-list";
    target: ContentRecordRef;
    ordered: boolean;
} | {
    kind: "object";
    fields: ContentFieldDefinition[];
} | {
    kind: "list";
    item: ContentValueSchema;
} | {
    kind: "asset-use";
    use: ContentAssetUse["kind"];
};
type ContentFieldDefinition = {
    id: RecordId;
    key: string;
    label: string;
    required: boolean;
} & ContentValueSchema;
/** Inverses are presentation metadata. Only the named owning field stores edges. */
interface ContentInverseDefinition {
    id: string;
    label: string;
    source: ContentRecordRef;
    fieldId: string;
}
interface ContentPresentation {
    groups: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    views: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    inverses: ContentInverseDefinition[];
}
interface ContentModelDocument {
    schemaVersion: typeof CONTENT_MODEL_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    description: string;
    kind: ContentModelKind;
    fields: ContentFieldDefinition[];
    presentation?: ContentPresentation;
}
interface ContentModelRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: ContentModelDocument;
}
interface ContentEntryRecord {
    schemaVersion: typeof CONTENT_ENTRY_SCHEMA_VERSION;
    id: RecordId;
    modelId: RecordId;
    createdAt: string;
    updatedAt: string;
    values: Record<RecordId, JsonValue>;
    lifecycle: "draft" | "published";
    /** Storage assigns a new generation atomically for every entry mutation. */
    generation: number;
}
interface ContentCompletenessDiagnostic {
    code: "required-value-missing" | "semantic-value-incomplete";
    modelId: RecordId;
    entryId: RecordId;
    fieldId: RecordId;
    fieldKey: string;
    message: string;
    path?: readonly (string | number)[];
}

type ContentValidationCode = "invalid-record" | "invalid-keys" | "unsafe-id" | "id-mismatch" | "invalid-timestamp" | "invalid-timestamp-order" | "not-json-safe" | "malformed-document" | "future-schema" | "invalid-field" | "duplicate-field-id" | "duplicate-field-key" | "invalid-value";
interface ContentValidationIssue {
    code: ContentValidationCode;
    message: string;
    path?: string;
    foundSchemaVersion?: number;
}

type ContentLoadOutcome<T> = {
    status: "loaded";
    record: T;
} | {
    status: "not-found";
    id: string;
} | {
    status: "invalid";
    issue: ContentValidationIssue;
    raw: unknown;
} | {
    status: "future-schema";
    foundSchemaVersion: number;
    raw: unknown;
};

interface ContentModelSummary {
    id: RecordId;
    name: string;
    kind: "collection" | "single";
    fieldCount: number;
    createdAt: string;
    updatedAt: string;
}
interface ContentPageOptions {
    limit?: number;
    cursor?: string;
}
interface ContentEntryPage {
    entries: readonly ContentEntryRecord[];
    nextCursor?: string;
}
interface ContentEntrySnapshot {
    model: ContentModelRecord;
    count: number;
    entries: readonly ContentEntryRecord[];
    diagnostics: readonly ContentCompletenessDiagnostic[];
}
declare const CONTENT_PERSISTENCE_OPERATIONS: readonly ["read-all", "transact", "reconcile-publication", "initialize", "list-models", "get-model", "put-model", "delete-model", "count-entries", "get-entry", "page-entries", "scan-entries", "put-entry", "delete-entry", "remove-field", "seed", "clear"];
type ContentPersistenceOperation = (typeof CONTENT_PERSISTENCE_OPERATIONS)[number];
declare const CONTENT_PERSISTENCE_ERROR_CODES: readonly ["conflict", "reference-in-use", "dependency-in-use", "unsupported-transaction", "unavailable", "blocked", "versionchange", "unsupported-version", "validation", "not-found", "immutable-kind", "field-in-use", "field-removal-required", "single-cardinality", "read-failed", "write-failed", "transaction-failed", "invalid-cursor", "commit-uncertain", "unknown"];
type ContentPersistenceErrorCode = (typeof CONTENT_PERSISTENCE_ERROR_CODES)[number];
declare class ContentPersistenceError extends Error {
    readonly operation: ContentPersistenceOperation;
    readonly code: ContentPersistenceErrorCode;
    readonly retryable: boolean;
    readonly name = "ContentPersistenceError";
    constructor(operation: ContentPersistenceOperation, code: ContentPersistenceErrorCode, message: string, retryable: boolean, options?: {
        cause?: unknown;
    });
    /**
     * Structured context the shared file-provider transport forwards verbatim.
     * `retryable` is not derivable from the code alone, so it has to cross the
     * wire rather than be re-guessed browser-side.
     */
    get details(): {
        retryable: boolean;
    };
}
interface ContentSeed {
    models: readonly ContentModelRecord[];
    entries: readonly ContentEntryRecord[];
}
interface ContentStore {
    readonly provider: {
        readonly id: string;
        readonly label: string;
    };
    readonly transactionScope: "provider" | "unsupported";
    readAll(): Promise<ContentSnapshot>;
    transact(mutation: ContentMutation): Promise<ContentSnapshot>;
    reconcilePublication(reconciliations: readonly ContentPublicationReconciliation[], activationGeneration: number, signal?: AbortSignal): Promise<ContentSnapshot & {
        activationGeneration: number;
    }>;
    listModels(): Promise<readonly ContentModelSummary[]>;
    getModel(id: string): Promise<ContentLoadOutcome<ContentModelRecord>>;
    putModel(record: ContentModelRecord): Promise<void>;
    deleteModel(id: string): Promise<boolean>;
    countEntries(modelId: string): Promise<number>;
    getEntry(id: string): Promise<ContentLoadOutcome<ContentEntryRecord>>;
    pageEntries(modelId: string, options?: ContentPageOptions): Promise<ContentEntryPage>;
    scanEntries(modelId: string): Promise<ContentEntrySnapshot>;
    putEntry(record: ContentEntryRecord): Promise<void>;
    deleteEntry(id: string): Promise<boolean>;
    removeField(modelId: string, fieldId: string): Promise<void>;
    seed(seed: ContentSeed): Promise<void>;
    clear(): Promise<void>;
}
interface ContentSnapshot extends ContentSeed {
    providerId: string;
    mutationToken: number;
}
type ContentMutationOperation = {
    kind: "put-model";
    record: ContentModelRecord;
} | {
    kind: "put-entry";
    record: ContentEntryRecord;
} | {
    kind: "delete-entry";
    id: string;
} | {
    kind: "unpublish-entry";
    id: string;
} | {
    kind: "delete-model";
    id: string;
} | {
    kind: "remove-field";
    modelId: string;
    fieldId: string;
};
interface ContentMutation {
    expectedMutationToken: number;
    operations: readonly ContentMutationOperation[];
}
interface ContentPublicationReconciliation {
    ref: ContentEntryRef;
    expectedGeneration: number;
    expectedDigest: string;
    lifecycle: ContentEntryRecord["lifecycle"];
}
type ContentRecoveryReason = "invalid" | "future-schema";
interface ContentRecoveryOutcome {
    kind: "quarantined";
    reason: ContentRecoveryReason;
    sourcePreserved: true;
    affectedRecordIds: readonly string[];
    foundSchemaVersion?: number;
    message: string;
}
type ContentInitializationOutcome = {
    status: "ready";
    models: readonly ContentModelSummary[];
} | {
    status: "recovery-required";
    models: readonly ContentModelSummary[];
    recovery: ContentRecoveryOutcome;
} | {
    status: "error";
    error: ContentPersistenceError;
};

interface ContentModelRef {
    providerId: string;
    recordId: string;
}

declare const MAPPING_SCHEMA_VERSION: 2;
type MappingMode = {
    kind: "single";
} | {
    kind: "collection";
    query: MappingCollectionQuery;
};
type MappingCollectionConditionOperator = "equals" | "not-equals" | "contains" | "exists";
interface MappingCollectionCondition {
    fieldId: RecordId;
    operator: MappingCollectionConditionOperator;
    value?: JsonValue;
}
interface MappingCollectionSort {
    fieldId: RecordId;
    direction: "asc" | "desc";
}
interface MappingCollectionPin {
    providerId: string;
    modelId: RecordId;
    recordId: RecordId;
}
interface MappingCollectionQuery {
    publication: "published-only" | "include-drafts";
    conditions: MappingCollectionCondition[];
    sort: MappingCollectionSort[];
    pins: MappingCollectionPin[];
    limit: number;
}
interface MappingTarget {
    nodeId: string;
    prop: string;
}
type MappingSourceProjection = {
    kind: "value";
} | {
    kind: "object-field";
    fieldIds: readonly RecordId[];
} | {
    kind: "asset-url";
} | {
    kind: "asset-download";
} | {
    kind: "asset-text";
    field: "alt" | "caption" | "label" | "title" | "description";
} | {
    kind: "reference-id";
} | {
    kind: "route-link";
};
type MappingTransform =
/** Preserve the scalar value exactly when the source and target domains agree. */
{
    kind: "identity";
}
/** Format a canonical Content date string as a medium, UTC-stable display date. */
 | {
    kind: "date-medium";
}
/** Keep 160 Unicode code points from longer Content, then append an ellipsis. */
 | {
    kind: "truncate-160";
}
/** Add a configured label/decorator before string-producing Content. */
 | {
    kind: "prefix";
    prefix: string;
};
interface MappingBinding {
    id: RecordId;
    sourceFieldId: RecordId;
    projection: MappingSourceProjection;
    target: MappingTarget;
    transform: MappingTransform;
}
interface MappingDocument {
    schemaVersion: typeof MAPPING_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    contentModel: ContentModelRef;
    composition: CompositionRecordRef;
    mode: MappingMode;
    bindings: MappingBinding[];
}
interface MappingRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: MappingDocument;
}
type MappingLoadOutcome = {
    status: "loaded";
    record: MappingRecord;
} | {
    status: "not-found";
    id: string;
} | {
    status: "invalid";
    issue: MappingValidationIssue;
    raw: unknown;
} | {
    status: "future-schema";
    foundSchemaVersion: number;
    raw: unknown;
};
type MappingValidationCode = "invalid-record" | "invalid-keys" | "unsafe-id" | "id-mismatch" | "invalid-timestamp" | "invalid-timestamp-order" | "not-json-safe" | "malformed-document" | "future-schema" | "invalid-ref" | "invalid-binding" | "duplicate-binding-id" | "malformed-transform";
interface MappingValidationIssue {
    code: MappingValidationCode;
    message: string;
    path?: string;
    foundSchemaVersion?: number;
}
declare const MAPPING_PERSISTENCE_OPERATIONS: readonly ["initialize", "list", "get", "put", "delete", "seed", "clear", "transact"];
type MappingPersistenceOperation = (typeof MAPPING_PERSISTENCE_OPERATIONS)[number];
declare const MAPPING_PERSISTENCE_ERROR_CODES: readonly ["unavailable", "blocked", "versionchange", "unsupported-version", "validation", "conflict", "read-failed", "write-failed", "transaction-failed", "commit-uncertain", "unknown"];
type MappingPersistenceErrorCode = (typeof MAPPING_PERSISTENCE_ERROR_CODES)[number];
declare class MappingPersistenceError extends Error {
    readonly operation: MappingPersistenceOperation;
    readonly code: MappingPersistenceErrorCode;
    readonly retryable: boolean;
    readonly name = "MappingPersistenceError";
    constructor(operation: MappingPersistenceOperation, code: MappingPersistenceErrorCode, message: string, retryable: boolean, options?: {
        cause?: unknown;
    });
    /**
     * Structured context the shared file-provider transport forwards verbatim.
     * `retryable` is not derivable from the code alone, so it has to cross the
     * wire rather than be re-guessed browser-side.
     */
    get details(): {
        retryable: boolean;
    };
}
interface MappingSummary {
    id: RecordId;
    name: string;
    createdAt: string;
    updatedAt: string;
    bindingCount: number;
}
interface MappingStore {
    snapshot?(): Promise<PersistedSnapshot<MappingRecord>>;
    mutationToken?(): Promise<number | string>;
    readonly provider: MappingProviderDescriptor;
    list(): Promise<readonly MappingSummary[]>;
    get(id: string): Promise<MappingLoadOutcome>;
    put(record: MappingRecord): Promise<void>;
    delete(id: string): Promise<boolean>;
    seed(seed: MappingSeed): Promise<void>;
    clear(): Promise<void>;
}
interface MappingSeed {
    mappings: readonly MappingRecord[];
}
interface MappingRecoveryOutcome {
    kind: "quarantined";
    reason: "invalid" | "future-schema";
    sourcePreserved: true;
    affectedRecordIds: readonly string[];
    foundSchemaVersion?: number;
    message: string;
}
type MappingInitializationOutcome = {
    status: "ready";
    summaries: readonly MappingSummary[];
} | {
    status: "recovery-required";
    summaries: readonly MappingSummary[];
    recovery: MappingRecoveryOutcome;
} | {
    status: "error";
    error: MappingPersistenceError;
};
declare const MAPPING_PROVIDERS: {
    readonly filesystem: {
        readonly id: "mapping-filesystem";
        readonly label: "Project files";
    };
};
type MappingProviderDescriptor = Omit<(typeof MAPPING_PROVIDERS)[keyof typeof MAPPING_PROVIDERS], "label"> & {
    readonly label: string;
};

/** The only Sitemap document schema version understood by this build. */
declare const SITEMAP_SCHEMA_VERSION: 3;
type SitemapSchemaVersion = typeof SITEMAP_SCHEMA_VERSION;
/** A stable reference to a saved Composer composition. */
interface CompositionRef {
    providerId: string;
    recordId: RecordId;
}
/** A stable reference to a saved Mapping. */
interface MappingRef {
    providerId: string;
    recordId: RecordId;
}
type MappingRoute = {
    kind: "single";
} | {
    kind: "selected-entry";
    entry: SitemapEntryRef;
} | {
    kind: "entry-field";
    fieldId: RecordId;
    titleFieldId?: RecordId;
};
interface SitemapEntryRef {
    providerId: string;
    modelId: string;
    recordId: RecordId;
}
interface SitemapAncestorSelection {
    nodeId: string;
    entry: SitemapEntryRef;
}
type SitemapNavigationDestination = {
    kind: "route";
    nodeId: string;
    entry?: SitemapEntryRef;
    ancestors?: SitemapAncestorSelection[];
} | {
    kind: "external";
    url: string;
};
interface SitemapNavigationItem {
    id: string;
    label: string;
    visible: boolean;
    destination: SitemapNavigationDestination;
}
interface SitemapNavigation {
    primary: SitemapNavigationItem[];
    footer: SitemapNavigationItem[];
}
/** Every authored page has one explicit, persisted source. */
type SitemapPageSource = {
    kind: "unassigned";
} | {
    kind: "composition";
    ref: CompositionRef;
} | {
    kind: "mapping";
    ref: MappingRef;
    route: MappingRoute;
};
/** One authored page in the sitemap tree. Mapping Entries are never persisted here. */
interface SitemapNode {
    id: string;
    title: string;
    slug?: string;
    source: SitemapPageSource;
    notes?: string;
    children: SitemapNode[];
}
/** The complete persisted Sitemap document. */
interface SitemapDocument {
    schemaVersion: SitemapSchemaVersion;
    id: string;
    name: string;
    navigation: SitemapNavigation;
    /** Virtual insertion slot. The array itself is never a page node. */
    root: SitemapNode[];
}

/** A persisted sitemap and its storage metadata. */
interface SitemapRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: SitemapDocument;
}
/** The inexpensive representation returned by collection listings. */
interface SitemapSummary {
    id: RecordId;
    name: string;
    createdAt: string;
    updatedAt: string;
    pageCount: number;
    /** Pages with no Composition and no Mapping — the library's assignment chip. */
    unassignedCount: number;
}
type SitemapRecordValidationCode = "invalid-record" | "invalid-record-keys" | "unsafe-id" | "record-document-id-mismatch" | "invalid-created-at" | "invalid-updated-at" | "invalid-timestamp-order" | "not-json-safe" | "malformed-document" | "future-schema";
interface SitemapRecordValidationIssue {
    code: SitemapRecordValidationCode;
    message: string;
    foundSchemaVersion?: number;
}
/** Decode failures preserve the exact provider value for recovery. */
type SitemapRecordLoadOutcome = {
    status: "loaded";
    record: SitemapRecord;
} | {
    status: "not-found";
    id: string;
} | {
    status: "invalid";
    issue: SitemapRecordValidationIssue;
    raw: unknown;
} | {
    status: "future-schema";
    foundSchemaVersion: number;
    raw: unknown;
};
declare const SITEMAP_PERSISTENCE_OPERATIONS: readonly ["initialize", "list", "get", "put", "delete", "clear", "transact"];
type SitemapPersistenceOperation = (typeof SITEMAP_PERSISTENCE_OPERATIONS)[number];
declare const SITEMAP_PERSISTENCE_ERROR_CODES: readonly ["unavailable", "blocked", "versionchange", "unsupported-version", "validation", "conflict", "read-failed", "write-failed", "transaction-failed", "commit-uncertain", "unknown"];
type SitemapPersistenceErrorCode = (typeof SITEMAP_PERSISTENCE_ERROR_CODES)[number];
/** Operational provider failure. Decode and record validation use outcomes. */
declare class SitemapPersistenceError extends Error {
    readonly operation: SitemapPersistenceOperation;
    readonly code: SitemapPersistenceErrorCode;
    readonly retryable: boolean;
    readonly name = "SitemapPersistenceError";
    constructor(operation: SitemapPersistenceOperation, code: SitemapPersistenceErrorCode, message: string, retryable: boolean, options?: {
        cause?: unknown;
    });
    /**
     * Structured context the shared file-provider transport forwards verbatim.
     * `retryable` is not derivable from the code alone, so it has to cross the
     * wire rather than be re-guessed browser-side.
     */
    get details(): {
        retryable: boolean;
    };
}
interface SitemapStore {
    snapshot?(): Promise<PersistedSnapshot<SitemapRecord>>;
    mutationToken?(): Promise<number | string>;
    list(): Promise<readonly SitemapSummary[]>;
    get(id: string): Promise<SitemapRecordLoadOutcome>;
    put(record: SitemapRecord): Promise<void>;
    delete(id: string): Promise<boolean>;
    clear(): Promise<void>;
}
interface SitemapCollectionStore extends SitemapStore {
    seed(records: readonly SitemapRecord[]): Promise<void>;
    readAll(): Promise<readonly SitemapRecord[]>;
}
declare const SITEMAP_PROVIDERS: {
    readonly filesystem: {
        readonly id: "sitemap-filesystem";
        readonly label: "Project files";
    };
};
type SitemapProviderDescriptor = Omit<(typeof SITEMAP_PROVIDERS)[keyof typeof SITEMAP_PROVIDERS], "label"> & {
    readonly label: string;
};
type SitemapLibraryRecoveryReason = "invalid" | "future-schema";
interface SitemapRecoveryOutcome {
    kind: "quarantined";
    reason: SitemapLibraryRecoveryReason;
    sourcePreserved: true;
    affectedRecordIds: readonly string[];
    foundSchemaVersion?: number;
    message: string;
}
type SitemapInitializationOutcome = {
    status: "ready";
    summaries: readonly SitemapSummary[];
} | {
    status: "recovery-required";
    summaries: readonly SitemapSummary[];
    recovery: SitemapRecoveryOutcome;
} | {
    status: "error";
    error: SitemapPersistenceError;
};

/**
 * Stable SiteProject provider ids and their current browser-provider ids.
 *
 * Authoring persists to the host project's files, so every domain names its
 * filesystem provider. Keeping the mapping explicit prevents adapters from
 * accepting arbitrary provider strings and leaves the portable contract
 * independent of browser provider construction; the two identities happen to
 * match again today.
 */
declare const SITE_PROJECT_PROVIDER_REGISTRY: Readonly<{
    readonly compositions: Readonly<{
        files: Readonly<{
            logicalId: "files";
            browserProviderId: "files";
        }>;
    }>;
    readonly content: Readonly<{
        "content-filesystem": Readonly<{
            logicalId: "content-filesystem";
            browserProviderId: "content-filesystem";
        }>;
    }>;
    readonly mappings: Readonly<{
        "mapping-filesystem": Readonly<{
            logicalId: "mapping-filesystem";
            browserProviderId: "mapping-filesystem";
        }>;
    }>;
    readonly sitemaps: Readonly<{
        "sitemap-filesystem": Readonly<{
            logicalId: "sitemap-filesystem";
            browserProviderId: "sitemap-filesystem";
        }>;
    }>;
}>;
type SiteProjectDomain = keyof typeof SITE_PROJECT_PROVIDER_REGISTRY;
type SiteProjectProviderId<TDomain extends SiteProjectDomain> = keyof (typeof SITE_PROJECT_PROVIDER_REGISTRY)[TDomain] & string;

declare const SITE_PROJECT_SCHEMA_VERSION: 2;
interface SiteProjectCollectionAttachment {
    id: RecordId;
    /** Deterministic authored ordering across distinct target slots. */
    order: number;
    composition: SiteProjectRecordRef<SiteProjectProviderId<"compositions">>;
    target: {
        nodeId: string;
        slotId: string;
    };
    mapping: SiteProjectRecordRef<SiteProjectProviderId<"mappings">>;
}
interface SiteProjectComponentPackRequirement {
    contractVersion: ComponentPackManifest["contractVersion"];
    packId: string;
    packVersion: string;
}
interface SiteProjectRecordRef<TProviderId extends string = string> {
    providerId: TProviderId;
    recordId: RecordId;
}
interface SiteProjectCompositionProvider {
    id: SiteProjectProviderId<"compositions">;
    records: CompositionRecord[];
}
interface SiteProjectContentProvider {
    id: SiteProjectProviderId<"content">;
    models: ContentModelRecord[];
    entries: ContentEntryRecord[];
}
interface SiteProjectMappingProvider {
    id: SiteProjectProviderId<"mappings">;
    records: MappingRecord[];
}
interface SiteProjectSitemapProvider {
    id: SiteProjectProviderId<"sitemaps">;
    records: SitemapRecord[];
}
interface SiteProjectProviders {
    compositions: SiteProjectCompositionProvider[];
    content: SiteProjectContentProvider[];
    mappings: SiteProjectMappingProvider[];
    sitemaps: SiteProjectSitemapProvider[];
}
/** The portable, JSON-safe whole-site aggregate. */
interface SiteProject {
    schemaVersion: typeof SITE_PROJECT_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    componentPack: SiteProjectComponentPackRequirement;
    providers: SiteProjectProviders;
    activeSitemap: SiteProjectRecordRef<SiteProjectProviderId<"sitemaps">>;
    collectionAttachments: SiteProjectCollectionAttachment[];
}

/** Provider identities are data, not application-layer implementations. */
interface AssetProviderDescriptor {
    readonly id: string;
    readonly label: string;
}
/** The inexpensive representation used by library listings. */
interface AssetSummary {
    id: RecordId;
    fileName: string;
    mimeType: AssetType;
    byteLength: number;
    checksum: string;
    createdAt: string;
    updatedAt: string;
    revision: number;
    folderId: string | null;
    note: string;
    state: "active" | "trash";
    versionId: string;
    url: string;
    authoringUrl: string;
}
/** Bytes never travel through a persisted AssetRecord. */
type AssetByteSource = Uint8Array | ArrayBuffer | ReadableStream<Uint8Array> | AsyncIterable<Uint8Array>;
type AssetPersistenceOperation = "initialize" | "list" | "get" | "put" | "delete" | "seed" | "snapshot" | "replace" | "metadata" | "folder" | "trash" | "restore" | "pin" | "clear";
type AssetPersistenceErrorCode = "unavailable" | "blocked" | "versionchange" | "unsupported-version" | "validation" | "conflict" | "recovery-required" | "commit-uncertain" | "not-found" | "bytes-missing" | "read-failed" | "write-failed" | "transaction-failed" | "unknown";
/** Provider-neutral persistence failure. */
declare class AssetPersistenceError extends Error {
    readonly operation: AssetPersistenceOperation;
    readonly code: AssetPersistenceErrorCode;
    readonly retryable: boolean;
    readonly name = "AssetPersistenceError";
    constructor(operation: AssetPersistenceOperation, code: AssetPersistenceErrorCode, message: string, retryable: boolean, options?: {
        cause?: unknown;
    });
}
interface AssetStore {
    readonly provider: AssetProviderDescriptor;
    list(): Promise<readonly AssetSummary[]>;
    get(id: string): Promise<AssetLoadOutcome>;
    /** `bytes` is separate from JSON metadata and may be a streaming source. */
    put(record: AssetRecord, bytes: AssetByteSource): Promise<void>;
    /** Soft trash only. Missing preconditions are rejected, never guessed. */
    delete(id: string, precondition?: AssetMutationPrecondition): Promise<boolean>;
    /** Optional fixture convenience; filesystem providers need not implement it. */
    seed?(seed: AssetSeed): Promise<void>;
    clear(): Promise<void>;
}
interface AssetMutationPrecondition {
    expectedRevision: number;
    /** Optional provider-wide CAS in addition to mandatory record/folder CAS. */
    expectedMutationToken?: string;
}
interface AssetMetadataPatch {
    fileName?: string;
    folderId?: string | null;
    note?: string;
}
interface AssetFolderPatch {
    name?: string;
    parentId?: string | null;
    index?: number;
}
interface AssetListOptions {
    state?: "active" | "trash" | "all";
    folderId?: string | null;
}
declare const ASSET_VERSIONED_CAPABILITIES: Readonly<{
    readonly folders: true;
    readonly metadata: true;
    readonly replace: true;
    readonly trash: true;
    readonly restore: true;
    readonly exactVersions: true;
    readonly snapshot: true;
    readonly permanentDelete: false;
}>;
interface VersionedAssetStore extends AssetStore {
    readonly capabilities: typeof ASSET_VERSIONED_CAPABILITIES;
    list(options?: AssetListOptions): Promise<readonly AssetSummary[]>;
    snapshot(): Promise<AssetSnapshot>;
    mutationToken(): Promise<string>;
    updateMetadata(id: string, patch: AssetMetadataPatch, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    trash(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    restore(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    createFolder(input: {
        name: string;
        parentId: string | null;
        index?: number;
    }, expectedMutationToken: string): Promise<AssetFolder>;
    updateFolder(id: string, patch: AssetFolderPatch, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    trashFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    restoreFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    /** Reads and verifies retained bytes even when the asset is in trash. */
    resolveVersion(ref: AssetVersionRef): Promise<AssetVersionPin>;
    pinManifest(refs: readonly AssetVersionRef[]): Promise<AssetPinManifest>;
}
interface AssetSeed {
    readonly records: readonly AssetRecord[];
    /** Optional fixture/provider byte payloads keyed by record id. */
    readonly bytes?: Readonly<Record<string, AssetByteSource>>;
}
type AssetRecoveryReason = "invalid" | "future-schema";
interface AssetRecoveryOutcome {
    kind: "quarantined";
    reason: AssetRecoveryReason;
    sourcePreserved: true;
    affectedRecordIds: readonly string[];
    foundSchemaVersion?: number;
    message: string;
}
type AssetInitializationOutcome = {
    status: "ready";
    summaries: readonly AssetSummary[];
} | {
    status: "recovery-required";
    summaries: readonly AssetSummary[];
    recovery: AssetRecoveryOutcome;
} | {
    status: "error";
    error: AssetPersistenceError;
};

interface SafeRootFilesystemOperations {
    mkdir(path: string, options: {
        recursive: true;
    }): Promise<unknown>;
    lstat(path: string): Promise<Stats>;
    realpath(path: string): Promise<string>;
    readdir(path: string, options: {
        withFileTypes: true;
    }): Promise<Dirent[]>;
    open(path: string, flags: number, mode?: number): Promise<FileHandle>;
    rename(oldPath: string, newPath: string): Promise<void>;
    unlink(path: string): Promise<void>;
    rmdir(path: string): Promise<void>;
}

/** One record as it is written: an id plus its already-serialized JSON text. */
interface RecordEnvelope {
    readonly id: string;
    readonly json: string;
}
interface RecordTransactionContext {
    readonly generation: number;
    readonly mutationToken: string;
    readonly records: readonly RecordEnvelope[];
}
/**
 * The complete next state of the domain. A transaction is expressed as the
 * whole record set rather than a diff so before/after graph validation happens
 * on one value, and so the commit has exactly one outcome for every record.
 */
interface RecordTransactionPlan<T> {
    readonly records: readonly RecordEnvelope[];
    readonly result: T;
}
interface RecordTransactionSnapshot {
    readonly schemaVersion: number;
    readonly generation: number;
    readonly mutationToken: string;
    readonly records: readonly RecordEnvelope[];
}
/** Only isolated reproducible generation supplies this; live stores use random tokens. */
type RecordMutationTokenSource = (next: Omit<RecordTransactionSnapshot, "mutationToken"> & {
    readonly previousMutationToken: string;
}) => string;

interface FilesystemContentStoreOptions {
    /** The fixed directory below which every Content record file lives. */
    contentRoot: string;
    /** Test/fault-injection seam. Omitted methods use Node's real filesystem. */
    operations?: Partial<SafeRootFilesystemOperations>;
    /** Test-only random source seam; values must contain only URL-safe characters. */
    randomToken?: () => string;
    /** Only isolated reproducible workspace generation overrides live random tokens. */
    newMutationToken?: RecordMutationTokenSource;
    /** Clock used when a provider-owned operation restamps `updatedAt`. */
    now?: () => string;
}

/** Whole-record transaction capability, independent of a filesystem transport. */
interface RecordTransactionStorage {
    readonly root: string;
    snapshot(): Promise<RecordTransactionSnapshot>;
    mutationToken(): Promise<string>;
    commit<T>(plan: (context: RecordTransactionContext) => Promise<RecordTransactionPlan<T>> | RecordTransactionPlan<T>, options?: {
        expectedMutationToken?: string;
        signal?: AbortSignal;
    }): Promise<T>;
}

interface ContentInitializationFailure {
    id: string;
    status: "invalid" | "future-schema";
    version?: number;
}
interface ContentInitializationScan {
    models: readonly ContentModelSummary[];
    failures: readonly ContentInitializationFailure[];
}
declare class TransactionalContentStore implements ContentStore {
    private readonly records;
    private readonly now;
    readonly provider: {
        readonly id: "content-filesystem";
        readonly label: "Project files";
    };
    readonly transactionScope: "provider";
    protected constructor(records: RecordTransactionStorage, now: () => string);
    static fromRecords(records: RecordTransactionStorage, now?: () => string): Promise<TransactionalContentStore>;
    get root(): string;
    /**
     * Stamp the layout marker on a brand-new store, and refuse an existing one
     * whose marker does not match. Refusing at open is the point: a mismatched
     * store is never partially read, and never quietly re-shaped.
     */
    private open;
    private decode;
    private parse;
    /** Every record must load; a snapshot is all-or-nothing. */
    private strict;
    private read;
    private model;
    private validateSnapshot;
    private assertLocalSchema;
    /**
     * Run one whole mutation.
     *
     * `plan` sees the complete validated before-state and returns the complete
     * after-state. Both halves are validated inside the same commit, so a
     * mutation that would leave an invalid graph — in either direction — writes
     * nothing at all.
     */
    private mutate;
    /** A nested field kind cannot change while a stored entry supplies a value at that path. */
    private assertStoredKindsSurvive;
    /**
     * Identity and creation time are immutable, publication is reserved to
     * activation reconciliation, and every entry that actually changed carries
     * the new mutation token as its generation.
     */
    private stampGenerations;
    readAll(): Promise<ContentSnapshot>;
    listModels(): Promise<readonly ContentModelSummary[]>;
    getModel(id: string): Promise<ContentLoadOutcome<ContentModelRecord>>;
    countEntries(modelId: string): Promise<number>;
    getEntry(id: string): Promise<ContentLoadOutcome<ContentEntryRecord>>;
    pageEntries(modelId: string, options?: ContentPageOptions): Promise<ContentEntryPage>;
    scanEntries(modelId: string): Promise<ContentEntrySnapshot>;
    scanForInitialization(operation?: "initialize" | "list-models"): Promise<ContentInitializationScan>;
    putModel(record: ContentModelRecord): Promise<void>;
    deleteModel(id: string): Promise<boolean>;
    putEntry(record: ContentEntryRecord): Promise<void>;
    deleteEntry(id: string): Promise<boolean>;
    removeField(modelId: string, fieldId: string): Promise<void>;
    seed(seed: ContentSeed): Promise<void>;
    clear(): Promise<void>;
    /** Discards records the scan refused to read, so it never validates them. */
    forceClear(): Promise<void>;
    transact(mutation: ContentMutation): Promise<ContentSnapshot>;
    /**
     * Validate the whole mutation envelope before any state is read, so a
     * malformed batch is rejected without ever reaching the record store — the
     * filesystem analogue of "rejects malformed operations before writes".
     */
    private assertMutationShape;
    /**
     * Apply an activation's publication decisions behind a monotonic fence.
     *
     * The fence is stored with the records it guards, so a late callback from an
     * older activation — including one carrying no reconciliations at all — is
     * write-free rather than merely idempotent, and can never overwrite a newer
     * reconciled lifecycle.
     */
    reconcilePublication(reconciliations: readonly ContentPublicationReconciliation[], activationGeneration: number, signal?: AbortSignal): Promise<ContentSnapshot & {
        activationGeneration: number;
    }>;
    initialize(): Promise<ContentInitializationOutcome>;
    startFresh(): Promise<ContentInitializationOutcome>;
    private clock;
}

declare class FilesystemContentStore extends TransactionalContentStore {
    static create(options: FilesystemContentStoreOptions): Promise<FilesystemContentStore>;
}

interface FilesystemAssetStoreOperations extends SafeRootFilesystemOperations {
    link: typeof link;
}
interface FilesystemAssetStoreOptions {
    /** The host's configured assets directory: `catalog.json` plus private `versions/`. */
    assetsStoreRoot: string;
    /** Test/fault-injection seam. Omitted methods use Node's filesystem. */
    operations?: Partial<FilesystemAssetStoreOperations>;
    /** Used for exclusive temporary names. */
    randomToken?: () => string;
    /** Server-side record-id source. */
    idFactory?: IdFactory;
    /** Clock used for server-created records. */
    now?: () => string;
}
interface AssetUploadInput {
    fileName: string;
    /** Binary signatures determine the persisted type; this is the explicit fallback for supported text kinds. */
    declaredMimeType: string;
    bytes: AssetByteSource;
    signal?: AbortSignal;
    folderId?: string | null;
    note?: string;
    expectedMutationToken?: string;
}
interface AssetReplaceInput {
    bytes: AssetByteSource;
    signal?: AbortSignal;
    declaredMimeType?: string;
}

declare class FilesystemAssetStore implements VersionedAssetStore {
    private readonly filesystem;
    private readonly bytesDirectory;
    private readonly idFactory;
    private readonly now;
    private readonly publishVersion;
    readonly provider: {
        readonly id: "asset-files";
        readonly label: "Project files";
    };
    readonly capabilities: Readonly<{
        readonly folders: true;
        readonly metadata: true;
        readonly replace: true;
        readonly trash: true;
        readonly restore: true;
        readonly exactVersions: true;
        readonly snapshot: true;
        readonly permanentDelete: false;
    }>;
    private constructor();
    static create(options: FilesystemAssetStoreOptions): Promise<FilesystemAssetStore>;
    initialize(): Promise<AssetInitializationOutcome>;
    snapshot(): Promise<AssetSnapshot>;
    mutationToken(): Promise<string>;
    list(options?: AssetListOptions): Promise<readonly AssetSummary[]>;
    get(id: string): Promise<AssetLoadOutcome>;
    upload(input: AssetUploadInput): Promise<AssetRecord>;
    replace(id: string, input: AssetReplaceInput, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    /** Import is create-only, never a replacement bypass. */
    put(record: AssetRecord, bytes: AssetByteSource): Promise<void>;
    updateMetadata(id: string, patch: AssetMetadataPatch, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    trash(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    restore(id: string, precondition: AssetMutationPrecondition): Promise<AssetRecord>;
    delete(id: string, precondition?: AssetMutationPrecondition): Promise<boolean>;
    clear(): Promise<void>;
    createFolder(input: {
        name: string;
        parentId: string | null;
        index?: number;
    }, expectedMutationToken: string): Promise<AssetFolder>;
    updateFolder(id: string, patch: AssetFolderPatch, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    private placeFolder;
    trashFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    restoreFolder(id: string, precondition: AssetMutationPrecondition): Promise<AssetFolder>;
    resolveVersion(ref: AssetVersionRef): Promise<AssetVersionPin>;
    pinManifest(refs: readonly AssetVersionRef[]): Promise<AssetPinManifest>;
    private resolveFromSnapshot;
    private editRecord;
    private editFolder;
    private assertPrecondition;
    private requireRecord;
    private timestamp;
    private bump;
    private mintId;
    private catalogPath;
    private versionPath;
    private assertCatalog;
    private readCatalog;
    /** Kernel O_EXCL serializes cooperating writers across processes. Never steal
     * an existing lock: after a crash verify no writer is running before manual
     * .mutation.lock removal. Reads remain available during lock recovery.
     *
     * The whole catalog is one document, so a mutation touching several records
     * commits with the single rename inside commitDocument or not at all. */
    private mutate;
    private syncDirectory;
    private stageBytes;
    private commitBytes;
    private removeStage;
    private assertDirectories;
    private assertSafeId;
    private verifyBytes;
}

interface FilesystemMappingStoreOptions {
    /** The fixed directory below which every Mapping record file lives. */
    mappingsRoot: string;
    /** Test/fault-injection seam. Omitted methods use Node's real filesystem. */
    operations?: Partial<SafeRootFilesystemOperations>;
    /** Test-only random source seam; values must contain only URL-safe characters. */
    randomToken?: () => string;
    /** Only isolated reproducible workspace generation overrides live random tokens. */
    newMutationToken?: RecordMutationTokenSource;
}

interface MappingInitializationFailure {
    id: string;
    status: "invalid" | "future-schema";
    version?: number;
}
interface MappingInitializationScan {
    summaries: readonly MappingSummary[];
    failures: readonly MappingInitializationFailure[];
}
interface MappingTransactionStep {
    readonly operation: string;
    readonly payload?: unknown;
}
interface MappingTransactionRequest {
    readonly expectedMutationToken?: string;
    readonly steps: readonly MappingTransactionStep[];
}
interface MappingTransactionResult {
    readonly mutationToken: string;
    readonly records: readonly MappingRecord[];
}
declare class TransactionalMappingStore implements MappingStore {
    private readonly records;
    readonly provider: MappingProviderDescriptor;
    protected constructor(records: RecordTransactionStorage);
    static fromRecords(records: RecordTransactionStorage): Promise<TransactionalMappingStore>;
    get root(): string;
    /**
     * Stamp the layout marker on a brand-new store, and refuse an existing one
     * whose marker does not match. Refusing at open is the point: a mismatched
     * store is never partially read, and never quietly re-shaped.
     */
    private open;
    private decode;
    private parse;
    /** Every record must load; a snapshot is all-or-nothing. */
    private strict;
    private envelopes;
    private runCommit;
    /**
     * Run one whole mutation.
     *
     * `plan` sees the complete validated before-state and returns the complete
     * after-state.
     */
    private mutate;
    /**
     * Re-checks the layout marker like every other read, rather than trusting a
     * previous successful read.
     */
    mutationToken(): Promise<string>;
    snapshot(): Promise<{
        mutationToken: string;
        records: readonly MappingRecord[];
    }>;
    readAll(): Promise<readonly MappingRecord[]>;
    list(): Promise<readonly MappingSummary[]>;
    get(id: string): Promise<MappingLoadOutcome>;
    scanForInitialization(operation?: "initialize" | "list"): Promise<MappingInitializationScan>;
    put(record: MappingRecord): Promise<void>;
    delete(id: string): Promise<boolean>;
    seed(seed: MappingSeed): Promise<void>;
    clear(): Promise<void>;
    /** Discards records the scan refused to read, so it never validates them. */
    forceClear(): Promise<void>;
    /**
     * Apply a whole batch of steps as one commit, protected by the record
     * store's own opaque mutation token. Mapping has no atomic batch of its own,
     * so this is what the shared `{expectedMutationToken, steps}` wire envelope
     * drives instead of a bespoke `transact` operation.
     */
    applyTransaction(request: MappingTransactionRequest): Promise<MappingTransactionResult>;
    private applyStep;
    initialize(): Promise<MappingInitializationOutcome>;
    startFresh(): Promise<MappingInitializationOutcome>;
}

declare class FilesystemMappingStore extends TransactionalMappingStore {
    static create(options: FilesystemMappingStoreOptions): Promise<FilesystemMappingStore>;
}

interface FilesystemSitemapStoreOptions {
    /** The fixed directory below which every Sitemap record file lives. */
    sitemapsRoot: string;
    /** Test/fault-injection seam. Omitted methods use Node's real filesystem. */
    operations?: Partial<SafeRootFilesystemOperations>;
    /** Test-only random source seam; values must contain only URL-safe characters. */
    randomToken?: () => string;
    /** Only isolated reproducible workspace generation overrides live random tokens. */
    newMutationToken?: RecordMutationTokenSource;
}

interface SitemapInitializationFailure {
    id: string;
    status: "invalid" | "future-schema";
    version?: number;
}
interface SitemapInitializationScan {
    summaries: readonly SitemapSummary[];
    failures: readonly SitemapInitializationFailure[];
}
interface SitemapTransactionStep {
    readonly operation: string;
    readonly payload?: unknown;
}
interface SitemapTransactionRequest {
    readonly expectedMutationToken?: string;
    readonly steps: readonly SitemapTransactionStep[];
}
interface SitemapTransactionResult {
    readonly mutationToken: string;
    readonly records: readonly SitemapRecord[];
}
declare class TransactionalSitemapStore implements SitemapCollectionStore {
    private readonly records;
    readonly provider: SitemapProviderDescriptor;
    protected constructor(records: RecordTransactionStorage);
    static fromRecords(records: RecordTransactionStorage): Promise<TransactionalSitemapStore>;
    get root(): string;
    /**
     * Stamp the layout marker on a brand-new store, and refuse an existing one
     * whose marker does not match. Refusing at open is the point: a mismatched
     * store is never partially read, and never quietly re-shaped.
     */
    private open;
    /** Re-checks the layout marker on every call — never only at open. */
    private decode;
    private parse;
    /** Every record must load; a snapshot is all-or-nothing. */
    private strict;
    private envelopes;
    private runCommit;
    /**
     * Run one whole mutation. `plan` sees the complete validated before-state and
     * returns the complete after-state.
     */
    private mutate;
    /**
     * Re-checks the layout marker like every other read, rather than trusting a
     * previous successful read.
     */
    mutationToken(): Promise<string>;
    snapshot(): Promise<{
        mutationToken: string;
        records: readonly SitemapRecord[];
    }>;
    readAll(): Promise<readonly SitemapRecord[]>;
    list(): Promise<readonly SitemapSummary[]>;
    get(id: string): Promise<SitemapRecordLoadOutcome>;
    scanForInitialization(operation?: "initialize" | "list"): Promise<SitemapInitializationScan>;
    put(record: SitemapRecord): Promise<void>;
    delete(id: string): Promise<boolean>;
    seed(records: readonly SitemapRecord[]): Promise<void>;
    clear(): Promise<void>;
    /** Discards records the scan refused to read, so it never validates them. */
    forceClear(): Promise<void>;
    /**
     * Apply a whole batch of steps as one commit, protected by the record
     * store's own opaque mutation token. Sitemapper has no atomic batch of its
     * own, so this is what the shared `{expectedMutationToken, steps}` wire
     * envelope drives instead of a bespoke `transact` operation.
     */
    applyTransaction(request: SitemapTransactionRequest): Promise<SitemapTransactionResult>;
    private applyStep;
    initialize(): Promise<SitemapInitializationOutcome>;
    startFresh(): Promise<SitemapInitializationOutcome>;
}

declare class FilesystemSitemapStore extends TransactionalSitemapStore {
    static create(options: FilesystemSitemapStoreOptions): Promise<FilesystemSitemapStore>;
}

/**
 * Browser-produced output for one canonical record. The filesystem core owns
 * every read/write; this payload only carries a pure planner's decision.
 */
type FilesystemDerivedOutputPlan = {
    status: "generated";
    code: string;
} | {
    status: "blocked";
    reason: string;
};
/**
 * One immutable same-provider closure. It crosses the dev-only plugin boundary
 * so the browser can run its manifest-aware pure planner without any callback
 * into list/get while the filesystem root queue is held.
 */
interface FilesystemDerivedOutputRequest {
    records: readonly CompositionRecord[];
    sourceOutcomes: readonly {
        id: string;
        outcome: CompositionLoadOutcome;
    }[];
    targetIds: readonly string[];
}
/**
 * Derived modules are supplied by the browser's pure planner. The optional
 * batch argument is deliberately immutable data, not a store/provider handle.
 * String support retains the direct-core test and embedding seam for ordinary
 * non-linked records.
 */
type CompositionJsxProvider = (record: CompositionRecord, request: FilesystemDerivedOutputRequest) => string | FilesystemDerivedOutputPlan | Promise<string | FilesystemDerivedOutputPlan>;
/** Narrow injectable seam used to exercise filesystem failure recovery. */
type FilesystemStoreOperations = SafeRootFilesystemOperations;
interface FilesystemCompositionStoreOptions {
    /** The fixed directory below which all Composer-owned artifacts live. */
    compositionsRoot: string;
    /** Supplies the exact production output used to repair missing/stale JSX. */
    provideJsx: CompositionJsxProvider;
    /** Test/fault-injection seam. Omitted methods use Node's real filesystem. */
    operations?: Partial<FilesystemStoreOperations>;
    /** Test-only random source seam; values must contain only URL-safe characters. */
    randomToken?: () => string;
    /** Clock used when a provider-owned lifecycle operation changes a record. */
    now?: () => string;
}

interface ReviewedCompositionEdit<T extends object> {
    operationId: string;
    planDigest: string;
    expectedSnapshotToken: string;
    candidate: CompositionRecord;
    jsx: string;
    receipt: T;
}

declare class FilesystemCompositionStore implements CompositionLifecycleStore {
    private readonly filesystem;
    private readonly provideJsx;
    private readonly now;
    readonly provider: {
        readonly id: "files";
        readonly label: "Local files";
        readonly storageLabel: "Development composition files";
    };
    /** Content fingerprint, not a filesystem transaction or notification counter. */
    snapshot(): Promise<{
        mutationToken: string;
        records: readonly CompositionRecord[];
    }>;
    mutationToken(): Promise<string>;
    private constructor();
    private get operations();
    private get realRoot();
    static create(options: FilesystemCompositionStoreOptions): Promise<FilesystemCompositionStore>;
    list(): Promise<readonly CompositionSummary[]>;
    get(id: string): Promise<CompositionLoadOutcome>;
    /**
     * Derived output is planned OUTSIDE the mutation lock, because generating JSX
     * can need a round trip to the browser. Any canonical write that lands inside
     * that window makes `assertClosureUnchanged` reject the plan as a conflict —
     * and the Composer writes on every edit, so a read racing a save is ordinary.
     * Such a plan is stale, not wrong, so read the closure and plan again. Only a
     * closure that never holds still across these attempts is a real conflict.
     */
    private replanningOnStalePlan;
    /**
     * Stores canonical JSON first and derived JSX second. Supplying `jsx`
     * preserves an already-generated exact production result; otherwise the
     * injected provider is called.
     */
    put(record: CompositionRecord, jsx?: string): Promise<CompositionSaveOutcome>;
    delete(id: string): Promise<boolean>;
    /**
     * The root queue serializes every Composer-managed filesystem operation.
     * The binding scan deliberately happens inside that queue and immediately
     * before the source pair is removed, so normal UI saves cannot interleave a
     * new consumer between a helpful preflight and the destructive write.
     */
    deleteWithDependencyCheck(id: string): Promise<CompositionDeleteOutcome>;
    /**
     * Clear only the source role after a final serialized dependency scan. JSX
     * is prepared and replaced before canonical JSON so an injected output
     * failure cannot detach the source record's publication metadata.
     */
    unpublishWithDependencyCheck(id: string): Promise<CompositionUnpublishOutcome>;
    /**
     * A detach must not clear a binding in canonical JSON until its derived JSX
     * has been prepared and durably replaced. A later JSON replacement failure
     * can leave stale derived output, but preserves the old canonical binding;
     * the normal read repair will reconcile that artifact on retry.
     */
    saveLifecycleRecord(record: CompositionRecord): Promise<void>;
    clear(): Promise<void>;
    /**
     * Capture canonical records under the same root queue as atomic writes, so
     * managed saves cannot replace an inode between a snapshot's lstat and open.
     * Release the queue before derived-output planning: the provider may re-enter
     * list/get for a dependency, and holding the queue would deadlock that read.
     */
    private loadDependencyClosure;
    private readDependencyClosure;
    private assertClosureUnchanged;
    private assertBindingTransition;
    private outputTargetsForGet;
    private makeOutputRequest;
    private prepareDerivedOutputs;
    private orderedOutputIds;
    private applyDerivedOutputs;
    private blockDerivedOutput;
    private summarizeDerivedOutputs;
    private run;
    private reviewedJournal;
    reviewedEditReceipt<T extends object = Record<string, unknown>>(operationId: string): Promise<T | undefined>;
    commitReviewedEdit<T extends object>(input: ReviewedCompositionEdit<T>, recheck?: (snapshot: {
        mutationToken: string;
        records: readonly CompositionRecord[];
    }) => Promise<void>): Promise<T>;
    private findDependents;
    private assertSafeId;
    private jsonPath;
    private jsxPath;
    private readCanonical;
    private getProductionJsx;
    private deleteValidatedPair;
}

type WorkspaceProjectMetadata = Omit<SiteProject, "providers"> & {
    providers: {
        [K in keyof SiteProject["providers"]]: readonly {
            id: SiteProject["providers"][K][number]["id"];
        }[];
    };
};
interface WorkspaceRecord {
    schemaVersion: 1;
    id: string;
    mutationToken: number;
    status: "seeding" | "ready";
    metadata: WorkspaceProjectMetadata;
    baselineRevision: string;
    /** Fixed at creation; never replaced by a later injected active source. */
    seed?: SiteProject;
    /** No provider may reseed while an earlier failed attempt is being removed. */
    seedCleanupPending?: true;
    /** A resumed creation cannot bypass its external before-complete guard. */
    requiresBeforeComplete?: true;
}

type WorkspaceToken = string | number;
interface WorkspaceSnapshotSource<T = unknown> {
    id: string;
    token(): Promise<WorkspaceToken>;
    read(): Promise<{
        mutationToken: WorkspaceToken;
        value: T;
    }>;
}

interface FilesystemWorkspaceRegistryOptions {
    /** The fixed directory holding the registry documents, e.g. `<cms>/workspaces`. */
    registryRoot: string;
    /** Test/fault-injection seam. Omitted methods use Node's real filesystem. */
    operations?: Partial<SafeRootFilesystemOperations>;
    /** Test-only random source seam; values must contain only URL-safe characters. */
    randomToken?: () => string;
    /** Only isolated reproducible workspace generation overrides live random tokens. */
    newMutationToken?: RecordMutationTokenSource;
    now?: () => string;
    /** Identity source for `create()`; defaults to `crypto.randomUUID()`. */
    newWorkspaceId?: () => string;
}

interface WorkspaceMetadataPatch {
    name?: string;
    activeSitemap?: SiteProject["activeSitemap"];
    baselineRevision?: string;
    collectionAttachments?: readonly SiteProjectCollectionAttachment[];
}
declare class FilesystemWorkspaceRegistry {
    private readonly records;
    private readonly newWorkspaceId;
    private constructor();
    static create(options: FilesystemWorkspaceRegistryOptions): Promise<FilesystemWorkspaceRegistry>;
    get root(): string;
    /** Stamp the layout marker on a brand-new registry; refuse a mismatched one. */
    private initialize;
    /** Re-checks the layout marker on every call — never only at open. */
    private decode;
    private required;
    private parse;
    /** The document's filename is its identity; a record that disagrees is not repaired. */
    private validate;
    private envelopes;
    /**
     * Run one whole registry mutation. `plan` sees the complete validated
     * before-state and returns the complete after-state, so the workspace set and
     * the selection pointer commit or fail together.
     */
    private mutate;
    private read;
    private advance;
    /** The registry-wide durable generation, advanced by every committed mutation. */
    generation(): Promise<number>;
    list(): Promise<readonly WorkspaceRecord[]>;
    selection(): Promise<string | null>;
    /** Without an id, the selected workspace; `undefined` when none is selected. */
    open(id?: string): Promise<WorkspaceRecord | undefined>;
    findSeeding(project: SiteProject, revision: string): Promise<WorkspaceRecord | undefined>;
    /**
     * The `workspace` capture source, identical to the browser registry's: the
     * durable token is the record's own `mutationToken`, read before and after
     * the snapshot value.
     */
    snapshotSource(id: string): WorkspaceSnapshotSource<WorkspaceRecord>;
    create(project: SiteProject, baselineRevision: string, id?: string, requiresBeforeComplete?: boolean): Promise<WorkspaceRecord>;
    /** Caller holds the workspace initialization lock throughout directory cleanup. */
    markSeedCleanup(id: string, revision: string): Promise<void>;
    /** Remove the exact attempt only after every workspace directory was removed. */
    discardSeeding(id: string, revision: string): Promise<void>;
    complete(id: string, creationValidated?: boolean): Promise<WorkspaceRecord>;
    update(id: string, expectedToken: number, patch: WorkspaceMetadataPatch): Promise<WorkspaceRecord>;
    private owned;
}

interface ResolvedComponentPack {
  /** The config `pack` value, verbatim. */
  specifier: string;
  /** Scope + name, without the export subpath. */
  packageName: string;
  /** Directory of the resolved package. */
  packageRoot: string;
  /** Absolute path of the pack module. */
  entryPath: string;
}

/**
 * Every setting a host may declare. Path settings are relative to the host
 * project root; `pack` is a module specifier.
 *
 * All fields are required. A resolved config always carries the complete table,
 * which is what makes the shallow top-level merge in `composer()` safe: a
 * supplied object replaces the default wholesale rather than leaving holes.
 */
interface ComposerSettings {
    /**
     * Root for the CMS data domains. Changing it re-bases every domain directory
     * below that has not been set explicitly, so a host can move all CMS data
     * with one setting.
     *
     * @default "cms"
     */
    dataDir: string;
    /**
     * Composition JSON, including global templates.
     *
     * @default "cms/compositions"
     */
    compositionsDir: string;
    /**
     * Content-domain JSON.
     *
     * @default "cms/content"
     */
    contentDir: string;
    /**
     * Mapping-domain JSON.
     *
     * @default "cms/mappings"
     */
    mappingsDir: string;
    /**
     * Sitemapper-domain JSON.
     *
     * @default "cms/sitemaps"
     */
    sitemapsDir: string;
    /**
     * Assets content-addressed store: `catalog.json` plus `versions/`.
     *
     * @default "cms/assets"
     */
    assetsDir: string;
    /**
     * Published assets bytes the host commits and serves. Not re-based by
     * `dataDir` — it lives under the host's public directory, not its CMS data.
     *
     * @default "public/uploaded-assets"
     */
    publicAssetsDir: string;
    /**
     * The host's base CSS entry. It is the sole importer of the component pack's
     * CSS and the host's Tailwind `@source` declaration point.
     *
     * @default "styles/base.css"
     */
    styles: string;
    /**
     * Component-pack module specifier — a themeset package
     * (`"@acme/themeset/composer-pack"`) or a host self-reference
     * (`"my-site/components"`, backed by the host's own `exports` map).
     *
     * Required, with no default. zudo-composer never falls back to a bundled
     * provider pack.
     */
    pack: string;
}

/** Explicit host opt-in. Semantic kinds never derive from component names. */
interface NativeEditingConfig {
    source: "workspace";
    paragraph?: {
        componentId: string;
        textProp: string;
    };
    list?: {
        componentId: string;
        itemsProp: string;
    };
    image?: {
        componentId: string;
        srcProp: string;
        altProp: string;
    };
    table?: {
        componentId: string;
        columnsProp: string;
        rowsProp: string;
    };
}

/** Absolute paths derived from the settings. Node-side only, never serialized. */
interface ComposerPaths {
    workspaceRoot: string;
    data: string;
    compositions: string;
    content: string;
    mappings: string;
    sitemaps: string;
    assets: string;
    publicAssets: string;
    styles: string;
}
interface ResolvedComposerConfig {
    nativeEditing: NativeEditingConfig | undefined;
    /** Absolute host project root. Every relative setting resolves against it. */
    workspaceRoot: string;
    /** Absolute path of the host config file, whether or not it exists. */
    configPath: string;
    /** The complete, host-root-relative settings table. Safe to serialize. */
    settings: ComposerSettings;
    /** The same table resolved to absolute paths. */
    paths: ComposerPaths;
}

interface CaptureHostOptions {
    config: ResolvedComposerConfig;
    pack: TrustedComponentPack;
    packIdentity: ResolvedComponentPack;
}
/** Open only existing stores: inspection must never initialize CMS state. */
declare function captureHost(options: CaptureHostOptions): Promise<{
    manifest: ComponentCatalog;
    workspaceId: string;
    workspace: WorkspaceRecord;
    sourceAuthored: boolean;
    stores: {
        registry: FilesystemWorkspaceRegistry;
        compositions: FilesystemCompositionStore;
        sitemaps: FilesystemSitemapStore;
        mappings: FilesystemMappingStore;
        assets: FilesystemAssetStore;
        content: FilesystemContentStore;
    };
    tokens: {
        registry: number;
        compositions: string;
        sitemaps: string;
        mappings: string;
        assets: string;
        content: number;
    };
    records: {
        compositions: readonly CompositionRecord[];
        sitemaps: readonly SitemapRecord[];
        mappings: readonly MappingRecord[];
    };
    assets: AssetSnapshot;
    config: ResolvedComposerConfig;
    pack: TrustedComponentPack;
    packIdentity: ResolvedComponentPack;
}>;
type HostCapture = Awaited<ReturnType<typeof captureHost>>;
interface InspectPageRequest {
    workspaceId: string;
    page: string;
    sitemapId?: string;
}
type NativeKind = Exclude<keyof NativeEditingConfig, "source">;
interface NativeTarget {
    nodeId: string;
    kind: NativeKind;
    ordinal: number;
    componentId: string;
    props: Record<string, unknown>;
}
/** Pure canonical resolution, also used for dependency checks under write barriers. */
declare function resolvePage(capture: HostCapture, request: InspectPageRequest): {
    record: CompositionRecord;
    rootPolicy: RootPolicy;
    targets: NativeTarget[];
    allTargets: {
        reason?: string | undefined;
        nodeId: string;
        componentId: string;
        native: NativeKind | null;
    }[];
    consumers: {
        kind: string;
        sitemapId: string;
        pageId: string;
    }[];
    linkedConsumers: string[];
    mappedConsumers: string[];
    mappedPages: {
        sitemapId: string;
        pageId: string;
    }[];
    mappedDescendants: {
        sitemapId: string;
        pageId: string;
    }[];
    writeBlockers: string[];
    capabilities: Partial<Record<NativeKind, {
        available: boolean;
        componentId: string;
        reason?: string;
    }>>;
    sitemapId: string;
    pageId: string;
    identity: {
        workspaceId: string;
        sitemapId: string;
        pageId: string;
        providerId: string;
        recordId: string;
    };
    grammar: Grammar;
};

declare const editRequestSchema: z.ZodObject<{
    workspaceId: z.ZodString;
    page: z.ZodString;
    sitemapId: z.ZodOptional<z.ZodString>;
    after: z.ZodUnion<readonly [z.ZodObject<{
        nodeId: z.ZodString;
    }, z.core.$strict>, z.ZodObject<{
        kind: z.ZodEnum<{
            list: "list";
            image: "image";
            paragraph: "paragraph";
            table: "table";
        }>;
        ordinal: z.ZodNumber;
    }, z.core.$strict>]>;
    insert: z.ZodDiscriminatedUnion<[z.ZodObject<{
        kind: z.ZodLiteral<"text">;
        text: z.ZodString;
    }, z.core.$strict>, z.ZodObject<{
        kind: z.ZodLiteral<"image">;
        assetId: z.ZodString;
        alt: z.ZodString;
    }, z.core.$strict>, z.ZodObject<{
        kind: z.ZodLiteral<"table">;
        columns: z.ZodArray<z.ZodString>;
        rows: z.ZodArray<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>], "kind">;
}, z.core.$strict>;
type EditRequest = z.infer<typeof editRequestSchema>;
type EditPlan = {
    schemaVersion: 1;
    policy: "native-page-insertion-v1";
    id: string;
    createdAt: string;
    host: string;
    request: EditRequest;
    identity: ReturnType<typeof resolvePage>["identity"];
    generatedId: string;
    before: CompositionRecord;
    candidate: CompositionRecord;
    jsx: string;
    revisions: unknown;
    assetPin: AssetVersionPin | null;
    digest: string;
};
interface EditReceipt {
    schemaVersion: 1;
    operationId: string;
    planId: string;
    reviewDigest: string;
    kind: "applied" | "undone";
    identity: EditPlan["identity"];
    beforeDigest: string;
    afterDigest: string;
    jsxDigest: string;
    committedAt: string;
}
/** Shared deterministic service. Callers supply approval separately from proposals.
 * The digest binds content; the caller, not this service, supplies human authority.
 */
declare function createEditingService$1(options: CaptureHostOptions): {
    inspect(input: unknown): Promise<{
        record: CompositionRecord;
        rootPolicy: RootPolicy;
        targets: NativeTarget[];
        allTargets: {
            reason?: string | undefined;
            nodeId: string;
            componentId: string;
            native: NativeKind | null;
        }[];
        consumers: {
            kind: string;
            sitemapId: string;
            pageId: string;
        }[];
        linkedConsumers: string[];
        mappedConsumers: string[];
        mappedPages: {
            sitemapId: string;
            pageId: string;
        }[];
        mappedDescendants: {
            sitemapId: string;
            pageId: string;
        }[];
        writeBlockers: string[];
        capabilities: Partial<Record<NativeKind, {
            available: boolean;
            componentId: string;
            reason?: string;
        }>>;
        sitemapId: string;
        pageId: string;
        identity: {
            workspaceId: string;
            sitemapId: string;
            pageId: string;
            providerId: string;
            recordId: string;
        };
        grammar: Grammar;
    }>;
    resolve(input: unknown): Promise<{
        identity: {
            workspaceId: string;
            sitemapId: string;
            pageId: string;
            providerId: string;
            recordId: string;
        };
        target: NativeTarget;
        writeBlockers: string[];
    }>;
    plan(input: unknown): Promise<EditPlan>;
    review(input: unknown): Promise<EditPlan>;
    apply(input: unknown): Promise<EditReceipt>;
    receipt(input: unknown): Promise<{
        applied: EditReceipt | null;
        undone: EditReceipt | null;
    }>;
    discard(input: unknown): Promise<{
        planId: string;
        status: string;
    }>;
    supersede(input: unknown): Promise<{
        planId: string;
        status: string;
        replacementPlanId: string;
    }>;
    undo(input: unknown): Promise<EditReceipt>;
};

/** Trusted local authoring adapter; never expose apply/undo to a proposal runner. */
declare function createEditingService(options?: {
    workspaceRoot?: string;
}): Promise<ReturnType<typeof createEditingService$1>>;

export { createEditingService };
export type { EditPlan, EditReceipt, EditRequest };
