// Generated by pnpm build:public. Edit server/public and its source dependencies.
import { JsonValue, ComponentPackManifest, TrustedComponentPack } from '@zudo-composer/component-contract';

/** A persisted record id in its provider's namespace. */
type RecordId = string;

/** A JSON object — the shape of a node's `props`. */
type JsonObject = {
    [key: string]: JsonValue;
};
/** The only Composition document schema version this build understands. */
declare const COMPOSITION_SCHEMA_VERSION: 2;
type CompositionSchemaVersion = typeof COMPOSITION_SCHEMA_VERSION;
/** A single persisted node in a Composition tree. */
interface CompositionNode {
    /** Stable, unique node id (persisted document key). */
    id: string;
    /** Stable component id — looked up in the manifest. */
    componentId: string;
    /** Component schema version this node was authored against. */
    componentVersion: number;
    /** JSON-safe scalar props. */
    props: JsonObject;
    /** Stable slot id → ordered child nodes. */
    slots: Record<string, CompositionNode[]>;
}
/** The real component slot a Global template exposes to its consumers. */
interface GlobalTemplateOutletTarget {
    /** Id of the component node that owns the exposed slot. Never the virtual root. */
    parentId: string;
    /** Stable manifest slot id on `parentId`. */
    slotId: string;
}
/**
 * The single named projection point a Global template exposes in schema v2.
 * `id` is machine-stable; changing the human label or target never reissues it.
 */
interface GlobalTemplateOutlet {
    id: string;
    label: string;
    target: GlobalTemplateOutletTarget;
}
/** Publish this Composition as a live, one-outlet Global template. */
interface GlobalTemplatePublication {
    kind: "global-template";
    outlet: GlobalTemplateOutlet;
}
/** Publish this Composition as a detached-clone Pattern. */
interface PatternPublication {
    kind: "pattern";
}
/**
 * Reuse role persisted on a Composition. Absence means an ordinary local-only
 * Composition. The union deliberately contains no generic reference node.
 */
type CompositionPublication = GlobalTemplatePublication | PatternPublication;
/**
 * A consumer's stable link to one source outlet. Provider identity is omitted:
 * the containing record's active provider supplies that at resolution time.
 */
interface CompositionBinding {
    sourceRecordId: RecordId;
    outletId: string;
}
/** The full persisted Composition document in the current schema. */
interface CompositionDocument {
    schemaVersion: CompositionSchemaVersion;
    id: string;
    name: string;
    /**
     * The virtual root's children. `root` is an insertion slot only — the array
     * itself is NOT a node and has no id/props/component.
     */
    root: CompositionNode[];
    /** Optional reusable-source role. Mutually exclusive with `binding` semantically. */
    publication?: CompositionPublication;
    /** Optional live source binding. The local `root` remains canonical. */
    binding?: CompositionBinding;
}

/** A persisted composition and its storage metadata. */
interface CompositionRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: CompositionDocument;
}
declare const COMPOSITION_PROVIDER_IDS: {
    readonly files: "files";
};
type CompositionProviderId = (typeof COMPOSITION_PROVIDER_IDS)[keyof typeof COMPOSITION_PROVIDER_IDS];
/** A provider-qualified identity. Record ids are unique only inside a provider. */
interface CompositionRecordRef {
    providerId: CompositionProviderId;
    recordId: RecordId;
}

declare const CONTENT_MODEL_SCHEMA_VERSION: 1;
declare const CONTENT_ENTRY_SCHEMA_VERSION: 1;
type ContentModelKind = "collection" | "single";
interface ContentRecordRef {
    providerId: string;
    recordId: RecordId;
}
interface ContentEntryRef extends ContentRecordRef {
    modelId: RecordId;
}
/**
 * Stable authoring identity for a managed asset.
 *
 * Content deliberately does not persist a versionId: the current Asset head
 * may change while a draft is being edited. The provider-qualified shape is
 * shared structurally with AssetAssetRef so release can add an exact version
 * without losing which Asset provider owns the asset.
 */
type ContentAssetRef = {
    providerId: string;
    assetId: string;
};
type ContentAssetUse = {
    kind: "image";
    asset: ContentAssetRef;
    alt: string;
    decorative: boolean;
    caption: string;
} | {
    kind: "link";
    asset: ContentAssetRef;
    label: string;
} | {
    kind: "download";
    asset: ContentAssetRef;
    label: string;
    showSize: boolean;
    showType: boolean;
} | {
    kind: "card";
    asset: ContentAssetRef;
    title: string;
    description: string;
};
type ContentValueSchema = {
    kind: "text" | "long-text" | "markdown" | "number" | "boolean" | "date" | "slug" | "color" | "url";
} | {
    kind: "choice";
    options: {
        value: string;
        label: string;
    }[];
} | {
    kind: "reference";
    target: ContentRecordRef;
} | {
    kind: "reference-list";
    target: ContentRecordRef;
    ordered: boolean;
} | {
    kind: "object";
    fields: ContentFieldDefinition[];
} | {
    kind: "list";
    item: ContentValueSchema;
} | {
    kind: "asset-use";
    use: ContentAssetUse["kind"];
};
type ContentFieldDefinition = {
    id: RecordId;
    key: string;
    label: string;
    required: boolean;
} & ContentValueSchema;
/** Inverses are presentation metadata. Only the named owning field stores edges. */
interface ContentInverseDefinition {
    id: string;
    label: string;
    source: ContentRecordRef;
    fieldId: string;
}
interface ContentPresentation {
    groups: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    views: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    inverses: ContentInverseDefinition[];
}
interface ContentModelDocument {
    schemaVersion: typeof CONTENT_MODEL_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    description: string;
    kind: ContentModelKind;
    fields: ContentFieldDefinition[];
    presentation?: ContentPresentation;
}
interface ContentModelRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: ContentModelDocument;
}
interface ContentEntryRecord {
    schemaVersion: typeof CONTENT_ENTRY_SCHEMA_VERSION;
    id: RecordId;
    modelId: RecordId;
    createdAt: string;
    updatedAt: string;
    values: Record<RecordId, JsonValue>;
    lifecycle: "draft" | "published";
    /** Storage assigns a new generation atomically for every entry mutation. */
    generation: number;
}

interface ContentPublicationReconciliation {
    ref: ContentEntryRef;
    expectedGeneration: number;
    expectedDigest: string;
    lifecycle: ContentEntryRecord["lifecycle"];
}

type ContentPublicationSelection = {
    ref: ContentEntryRef;
    action: "publish" | "delete" | "unpublish";
};

interface ContentModelRef {
    providerId: string;
    recordId: string;
}

declare const MAPPING_SCHEMA_VERSION: 2;
type MappingMode = {
    kind: "single";
} | {
    kind: "collection";
    query: MappingCollectionQuery;
};
type MappingCollectionConditionOperator = "equals" | "not-equals" | "contains" | "exists";
interface MappingCollectionCondition {
    fieldId: RecordId;
    operator: MappingCollectionConditionOperator;
    value?: JsonValue;
}
interface MappingCollectionSort {
    fieldId: RecordId;
    direction: "asc" | "desc";
}
interface MappingCollectionPin {
    providerId: string;
    modelId: RecordId;
    recordId: RecordId;
}
interface MappingCollectionQuery {
    publication: "published-only" | "include-drafts";
    conditions: MappingCollectionCondition[];
    sort: MappingCollectionSort[];
    pins: MappingCollectionPin[];
    limit: number;
}
interface MappingTarget {
    nodeId: string;
    prop: string;
}
type MappingSourceProjection = {
    kind: "value";
} | {
    kind: "object-field";
    fieldIds: readonly RecordId[];
} | {
    kind: "asset-ref";
} | {
    kind: "asset-download";
} | {
    kind: "asset-text";
    field: "alt" | "caption" | "label" | "title" | "description";
} | {
    kind: "reference-id";
} | {
    kind: "reference-list-ids";
} | {
    kind: "route-link";
};
type MappingTransform =
/** Preserve the scalar value exactly when the source and target domains agree. */
{
    kind: "identity";
}
/** Format a canonical Content date string as a medium, UTC-stable display date. */
 | {
    kind: "date-medium";
}
/** Keep 160 Unicode code points from longer Content, then append an ellipsis. */
 | {
    kind: "truncate-160";
}
/** Add a configured label/decorator before string-producing Content. */
 | {
    kind: "prefix";
    prefix: string;
};
interface MappingBinding {
    id: RecordId;
    sourceFieldId: RecordId;
    projection: MappingSourceProjection;
    target: MappingTarget;
    transform: MappingTransform;
}
interface MappingDocument {
    schemaVersion: typeof MAPPING_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    contentModel: ContentModelRef;
    composition: CompositionRecordRef;
    mode: MappingMode;
    bindings: MappingBinding[];
}
interface MappingRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: MappingDocument;
}

/** The only Sitemap document schema version understood by this build. */
declare const SITEMAP_SCHEMA_VERSION: 3;
type SitemapSchemaVersion = typeof SITEMAP_SCHEMA_VERSION;
/** A stable reference to a saved Composer composition. */
interface CompositionRef {
    providerId: string;
    recordId: RecordId;
}
/** A stable reference to a saved Mapping. */
interface MappingRef {
    providerId: string;
    recordId: RecordId;
}
type MappingRoute = {
    kind: "single";
} | {
    kind: "selected-entry";
    entry: SitemapEntryRef;
} | {
    kind: "entry-field";
    fieldId: RecordId;
    titleFieldId?: RecordId;
};
interface SitemapEntryRef {
    providerId: string;
    modelId: string;
    recordId: RecordId;
}
interface SitemapAncestorSelection {
    nodeId: string;
    entry: SitemapEntryRef;
}
type SitemapNavigationDestination = {
    kind: "route";
    nodeId: string;
    entry?: SitemapEntryRef;
    ancestors?: SitemapAncestorSelection[];
} | {
    kind: "external";
    url: string;
};
interface SitemapNavigationItem {
    id: string;
    label: string;
    visible: boolean;
    destination: SitemapNavigationDestination;
}
interface SitemapNavigation {
    primary: SitemapNavigationItem[];
    footer: SitemapNavigationItem[];
}
/** Every authored page has one explicit, persisted source. */
type SitemapPageSource = {
    kind: "unassigned";
} | {
    kind: "composition";
    ref: CompositionRef;
} | {
    kind: "mapping";
    ref: MappingRef;
    route: MappingRoute;
};
/** One authored page in the sitemap tree. Mapping Entries are never persisted here. */
interface SitemapNode {
    id: string;
    title: string;
    slug?: string;
    source: SitemapPageSource;
    notes?: string;
    children: SitemapNode[];
}
/** The complete persisted Sitemap document. */
interface SitemapDocument {
    schemaVersion: SitemapSchemaVersion;
    id: string;
    name: string;
    navigation: SitemapNavigation;
    /** Virtual insertion slot. The array itself is never a page node. */
    root: SitemapNode[];
}

/** A persisted sitemap and its storage metadata. */
interface SitemapRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: SitemapDocument;
}

/**
 * Stable SiteProject provider ids and their current browser-provider ids.
 *
 * Authoring persists to the host project's files, so every domain names its
 * filesystem provider. Keeping the mapping explicit prevents adapters from
 * accepting arbitrary provider strings and leaves the portable contract
 * independent of browser provider construction; the two identities happen to
 * match again today.
 */
declare const SITE_PROJECT_PROVIDER_REGISTRY: Readonly<{
    readonly compositions: Readonly<{
        files: Readonly<{
            logicalId: "files";
            browserProviderId: "files";
        }>;
    }>;
    readonly content: Readonly<{
        "content-filesystem": Readonly<{
            logicalId: "content-filesystem";
            browserProviderId: "content-filesystem";
        }>;
    }>;
    readonly mappings: Readonly<{
        "mapping-filesystem": Readonly<{
            logicalId: "mapping-filesystem";
            browserProviderId: "mapping-filesystem";
        }>;
    }>;
    readonly sitemaps: Readonly<{
        "sitemap-filesystem": Readonly<{
            logicalId: "sitemap-filesystem";
            browserProviderId: "sitemap-filesystem";
        }>;
    }>;
}>;
type SiteProjectDomain = keyof typeof SITE_PROJECT_PROVIDER_REGISTRY;
type SiteProjectProviderId<TDomain extends SiteProjectDomain> = keyof (typeof SITE_PROJECT_PROVIDER_REGISTRY)[TDomain] & string;

declare const SITE_PROJECT_SCHEMA_VERSION: 2;
interface SiteProjectCollectionAttachment {
    id: RecordId;
    /** Deterministic authored ordering across distinct target slots. */
    order: number;
    composition: SiteProjectRecordRef<SiteProjectProviderId<"compositions">>;
    target: {
        nodeId: string;
        slotId: string;
    };
    mapping: SiteProjectRecordRef<SiteProjectProviderId<"mappings">>;
}
interface SiteProjectComponentPackRequirement {
    contractVersion: ComponentPackManifest["contractVersion"];
    packId: string;
    packVersion: string;
}
interface SiteProjectRecordRef<TProviderId extends string = string> {
    providerId: TProviderId;
    recordId: RecordId;
}
interface SiteProjectCompositionProvider {
    id: SiteProjectProviderId<"compositions">;
    records: CompositionRecord[];
}
interface SiteProjectContentProvider {
    id: SiteProjectProviderId<"content">;
    models: ContentModelRecord[];
    entries: ContentEntryRecord[];
}
interface SiteProjectMappingProvider {
    id: SiteProjectProviderId<"mappings">;
    records: MappingRecord[];
}
interface SiteProjectSitemapProvider {
    id: SiteProjectProviderId<"sitemaps">;
    records: SitemapRecord[];
}
interface SiteProjectProviders {
    compositions: SiteProjectCompositionProvider[];
    content: SiteProjectContentProvider[];
    mappings: SiteProjectMappingProvider[];
    sitemaps: SiteProjectSitemapProvider[];
}
/** The portable, JSON-safe whole-site aggregate. */
interface SiteProject {
    schemaVersion: typeof SITE_PROJECT_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    componentPack: SiteProjectComponentPackRequirement;
    providers: SiteProjectProviders;
    activeSitemap: SiteProjectRecordRef<SiteProjectProviderId<"sitemaps">>;
    collectionAttachments: SiteProjectCollectionAttachment[];
}
type SiteProjectDiagnosticSeverity = "error";
type SiteProjectDiagnosticCode = "invalid-project" | "invalid-keys" | "not-json-safe" | "future-schema" | "invalid-schema-version" | "unsafe-id" | "invalid-name" | "invalid-component-pack" | "component-pack-mismatch" | "invalid-provider" | "unknown-provider" | "duplicate-provider" | "duplicate-record" | "malformed-record" | "component-pack-incompatible" | "dangling-composition-binding" | "invalid-composition-binding" | "invalid-active-sitemap" | "dangling-content-model" | "wrong-content-provider" | "dangling-entry-field" | "invalid-entry-value" | "single-content-cardinality" | "dangling-mapping-reference" | "wrong-mapping-provider" | "dangling-mapping-field" | "dangling-mapping-target" | "dangling-sitemap-reference" | "wrong-sitemap-provider" | "dangling-sitemap-route-field" | "dangling-sitemap-title-field" | "invalid-sitemap-title-field" | "invalid-sitemap-selected-entry" | "invalid-collection-attachment" | "duplicate-collection-attachment" | "attachment-composition-not-found" | "attachment-mapping-not-found" | "attachment-mapping-not-collection" | "attachment-target-not-found" | "attachment-slot-not-found" | "attachment-slot-conflict";
interface SiteProjectDiagnostic {
    severity: SiteProjectDiagnosticSeverity;
    code: SiteProjectDiagnosticCode;
    message: string;
    /** Canonical JSONPath into the SiteProject input. */
    path: string;
}

interface NodeInput {
    id?: string;
    componentId: string;
    props?: JsonObject;
    slots?: Record<string, NodeInput[]>;
}
interface TemplateInput {
    id?: string;
    name: string;
    root: NodeInput[];
    outlet: {
        id?: string;
        label?: string;
        target: {
            parentId: string;
            slotId: string;
        };
    };
}
interface Template {
    id: string;
    outlet: GlobalTemplateOutlet;
    record: CompositionRecord;
}
interface PageInput {
    id?: string;
    name: string;
    root: NodeInput[];
    /** Bind this page into a global template's outlet. A detached page (no template) is what a collection mapping needs. */
    template?: Template;
}
interface Page {
    id: string;
    record: CompositionRecord;
}
type FieldInput = {
    key: string;
    label?: string;
    required?: boolean;
} & ({
    kind: "text" | "long-text" | "markdown" | "number" | "boolean" | "date" | "slug" | "color" | "url";
} | {
    kind: "choice";
    options: {
        value: string;
        label: string;
    }[];
} | {
    kind: "reference";
    target: Model;
} | {
    kind: "reference-list";
    target: Model;
    ordered?: boolean;
} | {
    kind: "object";
    fields: FieldInput[];
} | {
    kind: "list";
    item: ContentValueSchema;
} | {
    kind: "asset-use";
    use: "image" | "link" | "download" | "card";
});
interface ModelInput {
    id?: string;
    name: string;
    kind: "single" | "collection";
    description?: string;
    fields: FieldInput[];
}
interface Model {
    id: string;
    record: ContentModelRecord;
    /** Field key → field id, the lookup every entry, mapping and sitemap route uses. */
    fieldId(key: string): string;
}
interface EntryInput {
    id?: string;
    /** Values keyed by field KEY. `reference` / `reference-list` values are `entryRef(...)` objects. */
    values: Record<string, JsonValue>;
    lifecycle?: "draft" | "published";
}
interface Entry {
    id: string;
    modelId: string;
    record: ContentEntryRecord;
}
interface BindingInput {
    field: string;
    nodeId: string;
    prop: string;
    projection?: MappingSourceProjection;
    transform?: MappingTransform;
    id?: string;
}
interface CollectionModeInput {
    kind: "collection";
    sort?: {
        field: string;
        direction: "asc" | "desc";
    }[];
    limit?: number;
    publication?: MappingCollectionQuery["publication"];
    conditions?: {
        field: string;
        operator: MappingCollectionQuery["conditions"][number]["operator"];
        value?: JsonValue;
    }[];
}
interface MappingInput {
    id?: string;
    name: string;
    model: Model;
    composition: Page;
    mode?: {
        kind: "single";
    } | CollectionModeInput;
    bindings: BindingInput[];
}
interface Mapping {
    id: string;
    model: Model;
    composition: Page;
    record: MappingRecord;
}
interface Attachment {
    id: string;
    record: SiteProjectCollectionAttachment;
}
type RouteSource = {
    page: Page;
} | {
    mapping: Mapping;
    route?: "single";
} | {
    mapping: Mapping;
    route: "entry-field";
    field: string;
    titleField?: string;
};
type RouteInput = {
    id?: string;
    title: string;
    slug?: string;
    notes?: string;
    children?: RouteInput[];
} & RouteSource;
interface NavigationRef {
    route: RouteInput;
    label?: string;
    visible?: boolean;
    id?: string;
}
interface SitemapInput {
    id?: string;
    name: string;
    root: RouteInput;
    navigation?: {
        primary?: NavigationRef[];
        footer?: NavigationRef[];
    };
}
interface SiteOptions {
    id: string;
    name: string;
    componentPack: TrustedComponentPack | {
        manifest: ComponentPackManifest;
    };
    timestamp?: string;
}
interface Site {
    readonly id: string;
    readonly name: string;
    readonly manifest: ComponentPackManifest;
    template(input: TemplateInput): Template;
    page(input: PageInput): Page;
    model(input: ModelInput): Model;
    entry(model: Model, input: EntryInput): Entry;
    mapping(input: MappingInput): Mapping;
    /**
     * Materialise a collection mapping's composition once per entry into a named
     * slot of `target.nodeId`. The node's owner composition is found among the
     * pages and templates declared so far; pass `composition` when the node id
     * appears in more than one.
     */
    attach(mapping: Mapping, target: {
        nodeId: string;
        slotId: string;
        composition?: Page | Template;
    }, id?: string): Attachment;
    sitemap(input: SitemapInput): SitemapRecord;
    toSiteProject(): SiteProject;
}

declare const ASSET_TYPES: readonly ["image/png", "image/jpeg", "image/gif", "image/webp", "application/pdf", "application/zip", "text/plain", "text/csv", "application/json"];

type AssetType = (typeof ASSET_TYPES)[number];
/** Stable provider-qualified identity used by authoring references. */
interface AssetAssetRef {
    providerId: string;
    assetId: string;
}
/** Exact immutable version identity used by release/pin operations. */
interface AssetVersionRef extends AssetAssetRef {
    versionId: string;
}
interface AssetVersionPin extends AssetVersionRef {
    checksum: string;
    byteLength: number;
    mimeType: AssetType;
    url: string;
}

interface LockedAssetPin extends AssetVersionPin {
    fileName?: string;
    metadataRevision: number;
    headVersionId: string;
}
interface AssetReferenceLock {
    schemaVersion: 1;
    providerId: string;
    mutationToken: string;
    pins: LockedAssetPin[];
}

type SiteProjectApiErrorCode = "malformed-request" | "unsupported-protocol" | "validation" | "compile-blocked" | "not-found" | "conflict" | "commit-uncertain" | "unavailable" | "internal";
interface SiteProjectActiveSelection {
    projectId: string;
    revision: string;
    buildId: string;
}
/**
 * Exactly which code compiled a release. A component pack is a package, not a
 * Git checkout — a registry themeset and a host self-reference have no commit —
 * so provenance is the specifier the host configured, the dependency spec it
 * was installed by, and a digest of the resolved bytes.
 */
interface ReleaseToolchain {
    compiler: string;
    componentPack: {
        packId: string;
        packVersion: string;
        contractVersion: number;
    };
    /** The config `pack` value, verbatim. */
    packSpecifier: string;
    /** The host's dependency spec for the pack's package, or `"self"`. */
    packSource: string;
    installedPackDigest: string;
    contractDigest: string;
}
interface ReleaseChange {
    domain: string;
    providerId: string;
    recordId: string;
    kind: "added" | "changed" | "removed";
}
interface ReleaseCheck {
    severity: "blocking" | "info";
    code: string;
    message: string;
    path: string;
}
interface ReleaseAffected {
    kind: "route" | "record" | "assets";
    identity: string;
    reason: string;
}
interface ReleasePlan {
    schemaVersion: 2;
    workingProject: SiteProject;
    workingPrecondition: JsonValue;
    candidate: SiteProject;
    selection: ContentPublicationSelection[];
    expectedRevision: string | null;
    expectedActive: SiteProjectActiveSelection | null;
    storeGeneration: number;
    projectRevision: string;
    buildId: string;
    assetLock: AssetReferenceLock | null;
    toolchain: ReleaseToolchain;
    changes: ReleaseChange[];
    checks: ReleaseCheck[];
    affected: ReleaseAffected[];
    publication: ContentPublicationReconciliation[];
    planDigest: string;
}
interface SiteProjectListEntry {
    projectId: string;
    name: string;
    revisions: readonly string[];
    head: string;
    stages: readonly string[];
}
type SiteProjectApiRequest = {
    protocolVersion: 2;
    operation: "describe" | "list" | "active";
} | {
    protocolVersion: 2;
    operation: "get";
    projectId: string;
    revision: string;
} | {
    protocolVersion: 2;
    operation: "plan";
    project: unknown;
    workingPrecondition: JsonValue;
    selection: ContentPublicationSelection[];
    expectedRevision: string | null;
    expectedActive: SiteProjectActiveSelection | null;
} | {
    protocolVersion: 2;
    operation: "apply";
    plan: ReleasePlan;
} | {
    protocolVersion: 2;
    operation: "stage" | "build" | "completed";
    projectId: string;
    buildId: string;
} | {
    protocolVersion: 2;
    operation: "activate";
    projectId: string;
    revision: string;
    buildId: string;
    expectedActive: SiteProjectActiveSelection | null;
} | {
    protocolVersion: 2;
    operation: "discard";
    projectId: string;
    buildId: string;
    expectedStageGeneration: number;
    expectedActive: SiteProjectActiveSelection | null;
};
interface SiteProjectApiError {
    code: SiteProjectApiErrorCode;
    message: string;
    identity?: SiteProjectActiveSelection;
    diagnostics?: readonly JsonValue[];
}
type SiteProjectApiResponse = {
    ok: true;
    result: JsonValue;
} | {
    ok: false;
    error: SiteProjectApiError;
};

export type { Attachment, BindingInput, CollectionModeInput, CompositionNode, CompositionRecord, ContentEntryRecord, ContentFieldDefinition, ContentModelRecord, ContentValueSchema, Entry, EntryInput, FieldInput, GlobalTemplateOutlet, JsonObject, Mapping, MappingBinding, MappingCollectionQuery, MappingInput, MappingRecord, MappingSourceProjection, MappingTransform, Model, ModelInput, NavigationRef, NodeInput, Page, PageInput, ReleasePlan, RouteInput, RouteSource, Site, SiteOptions, SiteProject, SiteProjectActiveSelection, SiteProjectApiRequest, SiteProjectApiResponse, SiteProjectCollectionAttachment, SiteProjectDiagnostic, SiteProjectListEntry, SitemapInput, SitemapNavigationItem, SitemapNode, SitemapRecord, Template, TemplateInput };
