// Generated by pnpm build:public. Edit server/public and its source dependencies.
import { Plugin } from 'vite';
import { JsonValue, TrustedComponentPack, ComponentPackManifest } from '@zudo-composer/component-contract';

declare const APP_ENTRY_MODULE: string;
declare function composerAppHtmlPlugin(): Plugin;

/** A persisted record id in its provider's namespace. */
type RecordId = string;

/** A JSON object — the shape of a node's `props`. */
type JsonObject = {
    [key: string]: JsonValue;
};
/** The only Composition document schema version this build understands. */
declare const COMPOSITION_SCHEMA_VERSION: 2;
type CompositionSchemaVersion = typeof COMPOSITION_SCHEMA_VERSION;
/** A single persisted node in a Composition tree. */
interface CompositionNode {
    /** Stable, unique node id (persisted document key). */
    id: string;
    /** Stable component id — looked up in the manifest. */
    componentId: string;
    /** Component schema version this node was authored against. */
    componentVersion: number;
    /** JSON-safe scalar props. */
    props: JsonObject;
    /** Stable slot id → ordered child nodes. */
    slots: Record<string, CompositionNode[]>;
}
/** The real component slot a Global template exposes to its consumers. */
interface GlobalTemplateOutletTarget {
    /** Id of the component node that owns the exposed slot. Never the virtual root. */
    parentId: string;
    /** Stable manifest slot id on `parentId`. */
    slotId: string;
}
/**
 * The single named projection point a Global template exposes in schema v2.
 * `id` is machine-stable; changing the human label or target never reissues it.
 */
interface GlobalTemplateOutlet {
    id: string;
    label: string;
    target: GlobalTemplateOutletTarget;
}
/** Publish this Composition as a live, one-outlet Global template. */
interface GlobalTemplatePublication {
    kind: "global-template";
    outlet: GlobalTemplateOutlet;
}
/** Publish this Composition as a detached-clone Pattern. */
interface PatternPublication {
    kind: "pattern";
}
/**
 * Reuse role persisted on a Composition. Absence means an ordinary local-only
 * Composition. The union deliberately contains no generic reference node.
 */
type CompositionPublication = GlobalTemplatePublication | PatternPublication;
/**
 * A consumer's stable link to one source outlet. Provider identity is omitted:
 * the containing record's active provider supplies that at resolution time.
 */
interface CompositionBinding {
    sourceRecordId: RecordId;
    outletId: string;
}
/** The full persisted Composition document in the current schema. */
interface CompositionDocument {
    schemaVersion: CompositionSchemaVersion;
    id: string;
    name: string;
    /**
     * The virtual root's children. `root` is an insertion slot only — the array
     * itself is NOT a node and has no id/props/component.
     */
    root: CompositionNode[];
    /** Optional reusable-source role. Mutually exclusive with `binding` semantically. */
    publication?: CompositionPublication;
    /** Optional live source binding. The local `root` remains canonical. */
    binding?: CompositionBinding;
}

/** A persisted composition and its storage metadata. */
interface CompositionRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: CompositionDocument;
}
declare const COMPOSITION_PROVIDER_IDS: {
    readonly files: "files";
};
type CompositionProviderId = (typeof COMPOSITION_PROVIDER_IDS)[keyof typeof COMPOSITION_PROVIDER_IDS];
/** A provider-qualified identity. Record ids are unique only inside a provider. */
interface CompositionRecordRef {
    providerId: CompositionProviderId;
    recordId: RecordId;
}

declare const ASSET_TYPES: readonly ["image/png", "image/jpeg", "image/gif", "image/webp", "application/pdf", "application/zip", "text/plain", "text/csv", "application/json"];

type AssetType = (typeof ASSET_TYPES)[number];
/** Stable provider-qualified identity used by authoring references. */
interface AssetAssetRef {
    providerId: string;
    assetId: string;
}
/** Exact immutable version identity used by release/pin operations. */
interface AssetVersionRef extends AssetAssetRef {
    versionId: string;
}
interface AssetVersionPin extends AssetVersionRef {
    checksum: string;
    byteLength: number;
    mimeType: AssetType;
    url: string;
}

declare function composerFileProviderPlugin(options?: { assetsStoreRoot?: string; compositionsRoot?: string; workspaceRoot?: string }): Plugin;

interface ResolvedComponentPack {
  /** The config `pack` value, verbatim. */
  specifier: string;
  /** Scope + name, without the export subpath. */
  packageName: string;
  /** Directory of the resolved package. */
  packageRoot: string;
  /** Absolute path of the pack module. */
  entryPath: string;
}
declare function resolveComponentPack(workspaceRoot: string, specifier: string): ResolvedComponentPack;
declare function assertPackSourcesResolvable(
  workspaceRoot: string,
  manifest: TrustedComponentPack["manifest"],
  specifier: string,
): void;

declare const CONTENT_MODEL_SCHEMA_VERSION: 1;
declare const CONTENT_ENTRY_SCHEMA_VERSION: 1;
type ContentModelKind = "collection" | "single";
interface ContentRecordRef {
    providerId: string;
    recordId: RecordId;
}
interface ContentEntryRef extends ContentRecordRef {
    modelId: RecordId;
}
/**
 * Stable authoring identity for a managed asset.
 *
 * Content deliberately does not persist a versionId: the current Asset head
 * may change while a draft is being edited. The provider-qualified shape is
 * shared structurally with AssetAssetRef so release can add an exact version
 * without losing which Asset provider owns the asset.
 */
type ContentAssetRef = {
    providerId: string;
    assetId: string;
};
type ContentAssetUse = {
    kind: "image";
    asset: ContentAssetRef;
    alt: string;
    decorative: boolean;
    caption: string;
} | {
    kind: "link";
    asset: ContentAssetRef;
    label: string;
} | {
    kind: "download";
    asset: ContentAssetRef;
    label: string;
    showSize: boolean;
    showType: boolean;
} | {
    kind: "card";
    asset: ContentAssetRef;
    title: string;
    description: string;
};
type ContentValueSchema = {
    kind: "text" | "long-text" | "markdown" | "number" | "boolean" | "date" | "slug" | "color" | "url";
} | {
    kind: "choice";
    options: {
        value: string;
        label: string;
    }[];
} | {
    kind: "reference";
    target: ContentRecordRef;
} | {
    kind: "reference-list";
    target: ContentRecordRef;
    ordered: boolean;
} | {
    kind: "object";
    fields: ContentFieldDefinition[];
} | {
    kind: "list";
    item: ContentValueSchema;
} | {
    kind: "asset-use";
    use: ContentAssetUse["kind"];
};
type ContentFieldDefinition = {
    id: RecordId;
    key: string;
    label: string;
    required: boolean;
} & ContentValueSchema;
/** Inverses are presentation metadata. Only the named owning field stores edges. */
interface ContentInverseDefinition {
    id: string;
    label: string;
    source: ContentRecordRef;
    fieldId: string;
}
interface ContentPresentation {
    groups: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    views: {
        id: string;
        label: string;
        fieldIds: string[];
    }[];
    inverses: ContentInverseDefinition[];
}
interface ContentModelDocument {
    schemaVersion: typeof CONTENT_MODEL_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    description: string;
    kind: ContentModelKind;
    fields: ContentFieldDefinition[];
    presentation?: ContentPresentation;
}
interface ContentModelRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: ContentModelDocument;
}
interface ContentEntryRecord {
    schemaVersion: typeof CONTENT_ENTRY_SCHEMA_VERSION;
    id: RecordId;
    modelId: RecordId;
    createdAt: string;
    updatedAt: string;
    values: Record<RecordId, JsonValue>;
    lifecycle: "draft" | "published";
    /** Storage assigns a new generation atomically for every entry mutation. */
    generation: number;
}

interface ContentPublicationReconciliation {
    ref: ContentEntryRef;
    expectedGeneration: number;
    expectedDigest: string;
    lifecycle: ContentEntryRecord["lifecycle"];
}

interface ContentModelRef {
    providerId: string;
    recordId: string;
}

declare const MAPPING_SCHEMA_VERSION: 2;
type MappingMode = {
    kind: "single";
} | {
    kind: "collection";
    query: MappingCollectionQuery;
};
type MappingCollectionConditionOperator = "equals" | "not-equals" | "contains" | "exists";
interface MappingCollectionCondition {
    fieldId: RecordId;
    operator: MappingCollectionConditionOperator;
    value?: JsonValue;
}
interface MappingCollectionSort {
    fieldId: RecordId;
    direction: "asc" | "desc";
}
interface MappingCollectionPin {
    providerId: string;
    modelId: RecordId;
    recordId: RecordId;
}
interface MappingCollectionQuery {
    publication: "published-only" | "include-drafts";
    conditions: MappingCollectionCondition[];
    sort: MappingCollectionSort[];
    pins: MappingCollectionPin[];
    limit: number;
}
interface MappingTarget {
    nodeId: string;
    prop: string;
}
type MappingSourceProjection = {
    kind: "value";
} | {
    kind: "object-field";
    fieldIds: readonly RecordId[];
} | {
    kind: "asset-ref";
} | {
    kind: "asset-download";
} | {
    kind: "asset-text";
    field: "alt" | "caption" | "label" | "title" | "description";
} | {
    kind: "reference-id";
} | {
    kind: "reference-list-ids";
} | {
    kind: "route-link";
};
type MappingTransform =
/** Preserve the scalar value exactly when the source and target domains agree. */
{
    kind: "identity";
}
/** Format a canonical Content date string as a medium, UTC-stable display date. */
 | {
    kind: "date-medium";
}
/** Keep 160 Unicode code points from longer Content, then append an ellipsis. */
 | {
    kind: "truncate-160";
}
/** Add a configured label/decorator before string-producing Content. */
 | {
    kind: "prefix";
    prefix: string;
};
interface MappingBinding {
    id: RecordId;
    sourceFieldId: RecordId;
    projection: MappingSourceProjection;
    target: MappingTarget;
    transform: MappingTransform;
}
interface MappingDocument {
    schemaVersion: typeof MAPPING_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    contentModel: ContentModelRef;
    composition: CompositionRecordRef;
    mode: MappingMode;
    bindings: MappingBinding[];
}
interface MappingRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: MappingDocument;
}

/** The only Sitemap document schema version understood by this build. */
declare const SITEMAP_SCHEMA_VERSION: 3;
type SitemapSchemaVersion = typeof SITEMAP_SCHEMA_VERSION;
/** A stable reference to a saved Composer composition. */
interface CompositionRef {
    providerId: string;
    recordId: RecordId;
}
/** A stable reference to a saved Mapping. */
interface MappingRef {
    providerId: string;
    recordId: RecordId;
}
type MappingRoute = {
    kind: "single";
} | {
    kind: "selected-entry";
    entry: SitemapEntryRef;
} | {
    kind: "entry-field";
    fieldId: RecordId;
    titleFieldId?: RecordId;
};
interface SitemapEntryRef {
    providerId: string;
    modelId: string;
    recordId: RecordId;
}
interface SitemapAncestorSelection {
    nodeId: string;
    entry: SitemapEntryRef;
}
type SitemapNavigationDestination = {
    kind: "route";
    nodeId: string;
    entry?: SitemapEntryRef;
    ancestors?: SitemapAncestorSelection[];
} | {
    kind: "external";
    url: string;
};
interface SitemapNavigationItem {
    id: string;
    label: string;
    visible: boolean;
    destination: SitemapNavigationDestination;
}
interface SitemapNavigation {
    primary: SitemapNavigationItem[];
    footer: SitemapNavigationItem[];
}
/** Every authored page has one explicit, persisted source. */
type SitemapPageSource = {
    kind: "unassigned";
} | {
    kind: "composition";
    ref: CompositionRef;
} | {
    kind: "mapping";
    ref: MappingRef;
    route: MappingRoute;
};
/** One authored page in the sitemap tree. Mapping Entries are never persisted here. */
interface SitemapNode {
    id: string;
    title: string;
    slug?: string;
    source: SitemapPageSource;
    notes?: string;
    children: SitemapNode[];
}
/** The complete persisted Sitemap document. */
interface SitemapDocument {
    schemaVersion: SitemapSchemaVersion;
    id: string;
    name: string;
    navigation: SitemapNavigation;
    /** Virtual insertion slot. The array itself is never a page node. */
    root: SitemapNode[];
}

/** A persisted sitemap and its storage metadata. */
interface SitemapRecord {
    id: RecordId;
    createdAt: string;
    updatedAt: string;
    document: SitemapDocument;
}

/**
 * Stable SiteProject provider ids and their current browser-provider ids.
 *
 * Authoring persists to the host project's files, so every domain names its
 * filesystem provider. Keeping the mapping explicit prevents adapters from
 * accepting arbitrary provider strings and leaves the portable contract
 * independent of browser provider construction; the two identities happen to
 * match again today.
 */
declare const SITE_PROJECT_PROVIDER_REGISTRY: Readonly<{
    readonly compositions: Readonly<{
        files: Readonly<{
            logicalId: "files";
            browserProviderId: "files";
        }>;
    }>;
    readonly content: Readonly<{
        "content-filesystem": Readonly<{
            logicalId: "content-filesystem";
            browserProviderId: "content-filesystem";
        }>;
    }>;
    readonly mappings: Readonly<{
        "mapping-filesystem": Readonly<{
            logicalId: "mapping-filesystem";
            browserProviderId: "mapping-filesystem";
        }>;
    }>;
    readonly sitemaps: Readonly<{
        "sitemap-filesystem": Readonly<{
            logicalId: "sitemap-filesystem";
            browserProviderId: "sitemap-filesystem";
        }>;
    }>;
}>;
type SiteProjectDomain = keyof typeof SITE_PROJECT_PROVIDER_REGISTRY;
type SiteProjectProviderId<TDomain extends SiteProjectDomain> = keyof (typeof SITE_PROJECT_PROVIDER_REGISTRY)[TDomain] & string;

declare const SITE_PROJECT_SCHEMA_VERSION: 2;
interface SiteProjectCollectionAttachment {
    id: RecordId;
    /** Deterministic authored ordering across distinct target slots. */
    order: number;
    composition: SiteProjectRecordRef<SiteProjectProviderId<"compositions">>;
    target: {
        nodeId: string;
        slotId: string;
    };
    mapping: SiteProjectRecordRef<SiteProjectProviderId<"mappings">>;
}
interface SiteProjectComponentPackRequirement {
    contractVersion: ComponentPackManifest["contractVersion"];
    packId: string;
    packVersion: string;
}
interface SiteProjectRecordRef<TProviderId extends string = string> {
    providerId: TProviderId;
    recordId: RecordId;
}
interface SiteProjectCompositionProvider {
    id: SiteProjectProviderId<"compositions">;
    records: CompositionRecord[];
}
interface SiteProjectContentProvider {
    id: SiteProjectProviderId<"content">;
    models: ContentModelRecord[];
    entries: ContentEntryRecord[];
}
interface SiteProjectMappingProvider {
    id: SiteProjectProviderId<"mappings">;
    records: MappingRecord[];
}
interface SiteProjectSitemapProvider {
    id: SiteProjectProviderId<"sitemaps">;
    records: SitemapRecord[];
}
interface SiteProjectProviders {
    compositions: SiteProjectCompositionProvider[];
    content: SiteProjectContentProvider[];
    mappings: SiteProjectMappingProvider[];
    sitemaps: SiteProjectSitemapProvider[];
}
/** The portable, JSON-safe whole-site aggregate. */
interface SiteProject {
    schemaVersion: typeof SITE_PROJECT_SCHEMA_VERSION;
    id: RecordId;
    name: string;
    componentPack: SiteProjectComponentPackRequirement;
    providers: SiteProjectProviders;
    activeSitemap: SiteProjectRecordRef<SiteProjectProviderId<"sitemaps">>;
    collectionAttachments: SiteProjectCollectionAttachment[];
}

interface LockedAssetPin extends AssetVersionPin {
    fileName?: string;
    metadataRevision: number;
    headVersionId: string;
}
interface AssetReferenceLock {
    schemaVersion: 1;
    providerId: string;
    mutationToken: string;
    pins: LockedAssetPin[];
}

type LinkedJsxModuleKind = "standalone" | "global-template" | "linked-consumer";

interface SitemapRouteAncestor {
    nodeId: string;
    pathname: string;
    displayTitle: string;
    selectedEntry?: SitemapEntryRef;
}

interface ResolvedSitemapNavigationItem {
    id: string;
    label: string;
    href: string;
    external: boolean;
    nodeId?: string;
}
interface SitemapNavigationDiagnostic {
    code: "navigation-stale" | "navigation-ambiguous" | "navigation-unsafe";
    menu: "primary" | "footer";
    itemId: string;
    message: string;
}
interface ResolvedSitemapNavigation {
    primary: ResolvedSitemapNavigationItem[];
    footer: ResolvedSitemapNavigationItem[];
    diagnostics: SitemapNavigationDiagnostic[];
}

interface SiteCompiledModule {
    recordId: string;
    moduleSpecifier: string;
    kind: LinkedJsxModuleKind;
    code: string;
}
interface SiteCompiledRouteSource {
    kind: "composition" | "mapping";
    ref: SiteProjectRecordRef;
}
interface SiteCompiledRouteComposition {
    /** Stable provider-qualified identity of the canonical local Composition. */
    local: SiteProjectRecordRef;
    /** Deterministic route-variant identity used only for source planning. */
    routeRecordId: string;
    /** Evaluated local document. Its canonical source id is deliberately retained. */
    document: CompositionDocument;
    linkedSource?: {
        ref: SiteProjectRecordRef;
        outlet: {
            id: string;
            label: string;
            target: {
                parentId: string;
                slotId: string;
            };
        };
        document: CompositionDocument;
    };
}
interface SiteCompiledRoute {
    materializationSources?: readonly {
        renderedNodeId: string;
        providerId: string;
        recordId: string;
        nodeId: string;
        attachmentId: string;
        entries: readonly {
            providerId: string;
            modelId: string;
            recordId: string;
        }[];
    }[];
    pathname: string;
    /** Plain per-route title resolved during compilation; delivery never infers it from rendered content. */
    displayTitle: string;
    sitemapNode: {
        id: string;
        path: string;
    };
    source: SiteCompiledRouteSource;
    selectedEntry?: SitemapEntryRef;
    ancestors: readonly SitemapRouteAncestor[];
    composition: SiteCompiledRouteComposition;
    modules: readonly SiteCompiledModule[];
}
interface SiteBuildPlan {
    navigation: ResolvedSitemapNavigation;
    projectId: string;
    activeSitemap: SiteProjectRecordRef;
    routes: readonly SiteCompiledRoute[];
    /** Route targets plus code-identical, deduplicated dependency modules. */
    modules: readonly SiteCompiledModule[];
}

interface SiteProjectActiveSelection {
    projectId: string;
    revision: string;
    buildId: string;
}
/**
 * Exactly which code compiled a release. A component pack is a package, not a
 * Git checkout — a registry themeset and a host self-reference have no commit —
 * so provenance is the specifier the host configured, the dependency spec it
 * was installed by, and a digest of the resolved bytes.
 */
interface ReleaseToolchain {
    compiler: string;
    componentPack: {
        packId: string;
        packVersion: string;
        contractVersion: number;
    };
    /** The config `pack` value, verbatim. */
    packSpecifier: string;
    /** The host's dependency spec for the pack's package, or `"self"`. */
    packSource: string;
    installedPackDigest: string;
    contractDigest: string;
}
interface StagedRelease {
    schemaVersion: 2;
    projectId: string;
    revision: string;
    buildId: string;
    assetLock: AssetReferenceLock | null;
    toolchain: ReleaseToolchain;
    planDigest: string;
    publication: ContentPublicationReconciliation[];
}
interface CompletedRelease {
    identity: SiteProjectActiveSelection;
    completionDigest: string;
    files: Record<string, string>;
    build: SiteBuildPlan;
    stage: StagedRelease;
}

interface SiteProjectSourcePluginOptions {
  readDevRelease?: () => Promise<{ project: SiteProject; release: CompletedRelease } | null>;
  readDevAsset?: (pathname: string) => Promise<{ bytes: Uint8Array; mimeType: AssetType; identity: CompletedRelease["identity"] } | null>;
  workspaceRoot?: string;
  packIdentity?: ResolvedComponentPack;
}
declare function siteProjectSourcePlugin(options?: SiteProjectSourcePluginOptions): Plugin;

declare const COMPONENT_PACK_ID = "virtual:zudo-composer-pack";
declare function componentPackPlugin(options: { workspaceRoot: string; pack: string }): Plugin & {
  identity: ResolvedComponentPack;
};

declare const HOST_STYLES_ID = "virtual:zudo-composer-host-styles";
declare function hostStylesPlugin(options: { stylesPath: string; styles: string; configPath: string }): Plugin;

declare const APP_ROOT: string;
declare function fsModuleId(absolutePath: string): string;
declare function appModuleId(relativePath: string): string;
declare function resolveWorkspaceRoot(configured: string | undefined): string;

/**
 * Every setting a host may declare. Path settings are relative to the host
 * project root; `pack` is a module specifier.
 *
 * All fields are required. A resolved config always carries the complete table,
 * which is what makes the shallow top-level merge in `composer()` safe: a
 * supplied object replaces the default wholesale rather than leaving holes.
 */
interface ComposerSettings {
    /**
     * Root for the CMS data domains. Changing it re-bases every domain directory
     * below that has not been set explicitly, so a host can move all CMS data
     * with one setting.
     *
     * @default "cms"
     */
    dataDir: string;
    /**
     * Composition JSON, including global templates.
     *
     * @default "cms/compositions"
     */
    compositionsDir: string;
    /**
     * Content-domain JSON.
     *
     * @default "cms/content"
     */
    contentDir: string;
    /**
     * Mapping-domain JSON.
     *
     * @default "cms/mappings"
     */
    mappingsDir: string;
    /**
     * Sitemapper-domain JSON.
     *
     * @default "cms/sitemaps"
     */
    sitemapsDir: string;
    /**
     * Assets content-addressed store: `catalog.json` plus `versions/`.
     *
     * @default "cms/assets"
     */
    assetsDir: string;
    /**
     * Published assets bytes the host commits and serves. Not re-based by
     * `dataDir` — it lives under the host's public directory, not its CMS data.
     *
     * @default "public/uploaded-assets"
     */
    publicAssetsDir: string;
    /**
     * The host's base CSS entry. It is the sole importer of the component pack's
     * CSS and the host's Tailwind `@source` declaration point.
     *
     * @default "styles/base.css"
     */
    styles: string;
    /**
     * Component-pack module specifier — a themeset package
     * (`"@acme/themeset/composer-pack"`) or a host self-reference
     * (`"my-site/components"`, backed by the host's own `exports` map).
     *
     * Required, with no default. zudo-composer never falls back to a bundled
     * provider pack.
     */
    pack: string;
}

/** Absolute paths derived from the settings. Node-side only, never serialized. */
interface ComposerPaths {
    workspaceRoot: string;
    data: string;
    compositions: string;
    content: string;
    mappings: string;
    sitemaps: string;
    assets: string;
    publicAssets: string;
    styles: string;
}
interface ResolvedComposerConfig {
    /** Absolute host project root. Every relative setting resolves against it. */
    workspaceRoot: string;
    /** Absolute path of the host config file, whether or not it exists. */
    configPath: string;
    /** The complete, host-root-relative settings table. Safe to serialize. */
    settings: ComposerSettings;
    /** The same table resolved to absolute paths. */
    paths: ComposerPaths;
}

interface HostContext {
  composerConfig: ResolvedComposerConfig;
  pack: TrustedComponentPack;
  packIdentity: ResolvedComponentPack;
  workspaceRoot: string;
}

declare function loadHostContext(options?: {
  workspaceRoot?: string;
  env?: Record<string, string | undefined>;
}): Promise<HostContext>;

export { APP_ENTRY_MODULE, APP_ROOT, COMPONENT_PACK_ID, HOST_STYLES_ID, appModuleId, assertPackSourcesResolvable, componentPackPlugin, composerAppHtmlPlugin, composerFileProviderPlugin, fsModuleId, hostStylesPlugin, loadHostContext, resolveComponentPack, resolveWorkspaceRoot, siteProjectSourcePlugin };
export type { HostContext, ResolvedComponentPack };
