import { it, expect, vi } from "vitest";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { runInNewContext } from "node:vm";
import { MessageChannel } from "node:worker_threads";
import { ASSET_AUTHORING_URL_PATTERN, ASSET_CHECKSUM_URL_SOURCE, ASSET_CONTENT_TYPE_BY_EXTENSION, ASSET_IMMUTABLE_CACHE_CONTROL, ASSET_KINDS, ASSET_NOSNIFF } from "../../src/assets/model/asset-kinds.mjs";
it("assets worker reads only the requesting client and fails closed for unrelated uploads", async () => {
  const listeners = new Map<string, (event: unknown) => void>();
  const zipChecksum = "c".repeat(64);
  const zipPath = `/uploaded-assets/sha256-${zipChecksum}.zip`;
  const a = { postMessage(request: { pathname: string }, ports: import("node:worker_threads").MessagePort[]) { ports[0]!.postMessage(request.pathname === zipPath || request.pathname.startsWith("/uploaded-assets/asset-") ? { bytes: new Uint8Array([1, 2, 3]), mimeType: "application/zip", checksum: zipChecksum, byteLength: 3, url: zipPath } : { bytes: new Uint8Array([1, 2, 3]), mimeType: "image/png" }); ports[0]!.close(); } };
  const b = { postMessage(_request: unknown, ports: import("node:worker_threads").MessagePort[]) { ports[0]!.postMessage(null); ports[0]!.close(); } };
  const get = vi.fn(async (id: string) => id === "a" ? a : id === "b" ? b : null);
  const fetch = vi.fn(async () => new Response("seed", { headers: { "content-type": "image/png" } }));
  const seedPath = `/uploaded-assets/sha256-${"a".repeat(64)}.png`;
  const workerSelf = { addEventListener: (name: string, callback: (event: unknown) => void) => listeners.set(name, callback), location: { origin: "https://demo.example" }, clients: { get }, __zudoAssetConfig: { checksumUrlPattern: new RegExp(`^${ASSET_CHECKSUM_URL_SOURCE}$`), authoringUrlPattern: new RegExp(ASSET_AUTHORING_URL_PATTERN.source), contentTypeByExtension: ASSET_CONTENT_TYPE_BY_EXTENSION, kindsByMime: ASSET_KINDS, immutableCacheControl: ASSET_IMMUTABLE_CACHE_CONTROL, nosniff: ASSET_NOSNIFF } };
  runInNewContext(await readFile(resolve("scripts/hosted-demo/assets-worker.js"), "utf8"), { self: workerSelf, bundledAssetPaths: [seedPath], URL, Response, MessageChannel, setTimeout, clearTimeout, fetch });
  async function request(clientId: string, path: string, method = "GET") { let reply: Promise<Response> | undefined; listeners.get("fetch")!({ clientId, request: { url: `https://demo.example${path}`, method }, respondWith(value: Promise<Response>) { reply = value; } }); return reply!; }
  const unknownPath = `/uploaded-assets/sha256-${"b".repeat(64)}.png`;
  expect(new Uint8Array(await (await request("a", unknownPath)).arrayBuffer())).toEqual(new Uint8Array([1, 2, 3]));
  expect((await request("b", unknownPath)).status).toBe(404);
  expect((await request("", unknownPath)).status).toBe(404);
  expect(fetch).not.toHaveBeenCalled();
  expect(await (await request("b", seedPath)).text()).toBe("seed");
  expect(get.mock.calls.map(([id]) => id)).toEqual(["a", "b", "b"]);

  const zipResponse = await request("a", zipPath);
  expect(zipResponse!.headers.get("content-type")).toBe("application/zip");
  expect(zipResponse!.headers.get("content-length")).toBe("3");
  expect(zipResponse!.headers.get("cache-control")).toBe(ASSET_IMMUTABLE_CACHE_CONTROL);
  expect(zipResponse!.headers.get("x-content-type-options")).toBe(ASSET_NOSNIFF);
  expect(zipResponse!.headers.get("content-disposition")).toBe(`attachment; filename="${zipChecksum}.zip"`);
  const zipHead = await request("a", zipPath, "HEAD");
  expect(zipHead!.status).toBe(200);
  expect(zipHead!.headers.get("content-disposition")).toBe(zipResponse!.headers.get("content-disposition"));
  expect((await zipHead!.arrayBuffer()).byteLength).toBe(0);
  const redirect = await request("a", "/uploaded-assets/asset-demo");
  expect(redirect!.status).toBe(307);
  expect(redirect!.headers.get("location")).toBe(zipPath);
});
