import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";
import { ensureDevWorkspace } from "./workspace-bootstrap";

test("ZIP assets download with display names and insert structured download uses", async ({ page }) => {
  test.setTimeout(120_000);
  await ensureDevWorkspace(page);
  const modelId = `download-${Date.now()}`;
  await page.evaluate(async (modelId) => {
    const integrationPath = "/src/app/provider-integration.ts", contentPath = "/src/content/index.ts";
    const { createProductionProviderIntegration } = await import(integrationPath);
    const { createContentModelRecord, createContentEntryRecord } = await import(contentPath);
    const integration = createProductionProviderIntegration();
    await integration.initialization.initialize();
    await integration.contentProvider.store.putModel(createContentModelRecord({ name: modelId, kind: "collection", fields: [{ id: "download", key: "download", label: "Download", required: false, kind: "asset-use", use: "download" }] }, { id: modelId }));
    await integration.contentProvider.store.putEntry(createContentEntryRecord(modelId, {}, { id: modelId + "-entry" }));
  }, modelId);
  await page.goto("/assets");
  const uploadInput = page.locator('.sg-assets-upload input[type="file"]');
  const imageUploaded = page.waitForResponse((response) => response.request().headers()["x-zudo-composer-asset-operation"] === "upload");
  await uploadInput.setInputFiles({ name: "filter-image.png", mimeType: "image/png", buffer: await readFile("scripts/demo-assets/demo-sunrise.png") });
  expect((await imageUploaded).ok()).toBe(true);
  await expect(page.getByRole("button", { name: "Inspect filter-image.png", exact: true })).toBeVisible();
  await expect(uploadInput).toBeEnabled();
  const bytes = await readFile("scripts/demo-assets/demo-archive.zip");
  const name = "Release.v2.zip";
  const uploaded = page.waitForResponse((response) => response.request().headers()["x-zudo-composer-asset-operation"] === "upload");
  await uploadInput.setInputFiles({ name, mimeType: "application/zip", buffer: bytes });
  const response = await uploaded;
  expect(response.ok()).toBe(true);
  const record = (await response.json()).result;
  const url = record.document.versions[0].url as string;
  await page.getByRole("combobox", { name: "Asset type", exact: true }).selectOption("archive");
  await expect(page.getByRole("button", { name: /^Inspect / })).toHaveCount(1);
  await expect(page.locator(".sg-assets-file__label")).toHaveText("ZIP");
  await page.getByRole("button", { name: `Inspect ${name}`, exact: true }).click();
  const inspector = page.getByRole("complementary", { name: "Asset details" });
  await expect(inspector.getByRole("button", { name: /Edit image/ })).toHaveCount(0);
  await inspector.getByRole("button", { name: "Preview", exact: true }).click();
  const preview = page.getByRole("dialog", { name, exact: true });
  const link = preview.getByRole("link", { name: "Download", exact: true });
  await expect(link).toHaveAttribute("download", name);
  await expect(link).toHaveAttribute("href", url);
  const downloading = page.waitForEvent("download");
  await link.click();
  const download = await downloading;
  expect(download.suggestedFilename()).toBe(name);
  expect(await readFile((await download.path())!)).toEqual(bytes);
  const get = await page.request.get(url), head = await page.request.head(url);
  expect(get.headers()["content-type"]).toBe("application/zip");
  expect(get.headers()["content-disposition"]).toContain("attachment");
  for (const key of ["content-type", "content-disposition", "content-length", "cache-control", "x-content-type-options"]) expect(head.headers()[key]).toBe(get.headers()[key]);
  expect(await head.body()).toHaveLength(0);
  await preview.getByRole("button", { name: "Close", exact: true }).click();
  await inspector.getByRole("button", { name: "Use in content", exact: true }).click();
  const picker = page.getByRole("dialog", { name: "Use this asset", exact: true });
  await expect(picker.getByRole("radio", { name: "Download", exact: true })).toBeChecked();
  await expect(picker.getByRole("radio", { name: "Image", exact: true })).toBeDisabled();
  await picker.getByLabel("Content destination").selectOption({ label: `${modelId} / ${modelId}-entry / Download` });
  await picker.getByLabel("Download label", { exact: true }).fill("Release files");
  await picker.getByLabel("Show file size", { exact: true }).check();
  await picker.getByLabel("Show file type", { exact: true }).check();
  await picker.getByRole("button", { name: "Use in content", exact: true }).click();
  await expect(picker).toBeHidden();
  const saved = await page.evaluate(async (modelId) => {
    const path = "/src/app/provider-integration.ts";
    const { createProductionProviderIntegration } = await import(path);
    const integration = createProductionProviderIntegration();
    await integration.initialization.initialize();
    return (await integration.contentProvider.store.getEntry(modelId + "-entry")).record.values.download;
  }, modelId);
  expect(saved).toMatchObject({ kind: "download", asset: { assetId: record.id }, label: "Release files", showSize: true, showType: true });
});
