import "fake-indexeddb/auto";
import { IDBFactory as FDBFactory } from "fake-indexeddb";
import { describe, expect, it } from "vitest";
import { createComponentCatalog } from "../../composer/model/types";
import type { CompositionRecord } from "../../composer/library";
import { createContentCatalog } from "../../content/catalog";
import type { ContentEntryRecord, ContentFieldKind, ContentModelRecord } from "../../content/model";
import { CONTENT_ENTRY_SCHEMA_VERSION, CONTENT_MODEL_SCHEMA_VERSION } from "../../content/model";
import { createCompositionCatalog, createIndexedDbMappingProvider, createMappingCatalog, createMappingRecord, discoverMappingTargets, evaluateMapping, isMappingCompatible, mapMappingOperationalError, MAPPING_DATABASE_NAME, MAPPING_DATABASE_VERSION, MAPPING_META_STORE_NAME, MAPPING_RECORDS_STORE_NAME, MAPPING_SCHEMA_VERSION, MAPPING_UPDATED_AT_INDEX, resolveMappingDefinition, validateMappingRecord } from "..";
import type { MappingBinding, MappingTargetKind, MappingTransform } from "..";

const stamp = "2026-08-29T00:00:00.000Z";
const fields = [
  { id: "title", key: "title", label: "Title", required: true, kind: "text" },
  { id: "date", key: "date", label: "Date", required: false, kind: "date" },
  { id: "tone", key: "tone", label: "Tone", required: false, kind: "slug" },
] as const;
const model: ContentModelRecord = { id: "articles", createdAt: stamp, updatedAt: stamp, document: { schemaVersion: CONTENT_MODEL_SCHEMA_VERSION, id: "articles", name: "Articles", kind: "collection", fields: [...fields] } };
const composition: CompositionRecord = { id: "landing", createdAt: stamp, updatedAt: stamp, document: { schemaVersion: 2, id: "landing", name: "Landing", root: [{ id: "hero", componentId: "hero", componentVersion: 1, props: { title: "Static", subtitle: "Keep", tone: "quiet" }, slots: { body: [{ id: "nested", componentId: "copy", componentVersion: 1, props: { text: "Nested" }, slots: {} }] } }] } };
const manifest = createComponentCatalog({ kind: "zudo-composer/component-pack", contractVersion: 1, packId: "test", packVersion: "1", components: [
  { id: "hero", schemaVersion: 1, title: "Hero", category: "Test", description: "", source: { module: "x", exportKind: "named", exportName: "Hero" }, defaults: {}, fields: [{ kind: "text", prop: "title", label: "Title" }, { kind: "text", prop: "subtitle", label: "Subtitle" }, { kind: "select", prop: "tone", label: "Tone", options: ["quiet", "loud"] }], slots: [{ id: "body", prop: "body", label: "Body", cardinality: "many" }] },
  { id: "copy", schemaVersion: 1, title: "Copy", category: "Test", description: "", source: { module: "x", exportKind: "named", exportName: "Copy" }, defaults: {}, fields: [{ kind: "text", prop: "text", label: "Text" }], slots: [] },
] });

function mapping(bindings: readonly MappingBinding[] = [{ id: "bind-title", sourceFieldId: "title", target: { nodeId: "hero", prop: "title" }, transform: { kind: "identity" } }]) { return createMappingRecord({ id: "article-landing", name: "Article landing", contentModel: { providerId: "content", recordId: "articles" }, composition: { providerId: "indexeddb", recordId: "landing" }, bindings, createdAt: stamp }); }
function catalogs(contentRecord = model, compositionRecord = composition) { return { content: createContentCatalog([{ descriptor: { id: "content", label: "Content" }, store: { listModels: async () => [], getModel: async () => ({ status: "loaded" as const, record: contentRecord }) } }]), compositions: createCompositionCatalog([{ descriptor: { id: "indexeddb", label: "Compositions" }, store: { list: async () => [], get: async () => ({ status: "loaded" as const, record: compositionRecord }) } }]) }; }
function entry(values: ContentEntryRecord["values"]): ContentEntryRecord { return { schemaVersion: CONTENT_ENTRY_SCHEMA_VERSION, id: "entry-one", modelId: "articles", createdAt: stamp, updatedAt: stamp, values }; }

describe("normative compatibility matrix", () => {
  const sources: ContentFieldKind[] = ["text", "long-text", "markdown", "number", "boolean", "date", "slug", "color", "url"];
  const targets: MappingTargetKind[] = ["text", "select", "boolean", "number", "color"];
  const transforms: MappingTransform[] = [{ kind: "identity" }, { kind: "date-medium" }, { kind: "truncate-160" }, { kind: "prefix", prefix: "P" }];
  function expected(source: ContentFieldKind, target: MappingTargetKind, transform: MappingTransform): boolean { const string = ["text", "long-text", "markdown", "date", "slug", "color", "url"].includes(source); if (transform.kind === "date-medium") return source === "date" && target === "text"; if (transform.kind === "truncate-160" || transform.kind === "prefix") return string && target === "text"; return target === "text" ? string : target === "select" ? source === "text" || source === "slug" : target === "color" ? source === "color" : target === "number" ? source === "number" : source === "boolean"; }
  for (const source of sources) for (const target of targets) for (const transform of transforms) it(`${source} -> ${target} via ${transform.kind}`, () => expect(isMappingCompatible(source, target, transform)).toBe(expected(source, target, transform)));
});

describe("Mapping model and resolver", () => {
  it("preserves broken references structurally and reports them semantically", async () => { const record = mapping([{ id: "stale", sourceFieldId: "gone", target: { nodeId: "missing", prop: "old" }, transform: { kind: "identity" } }]); expect(validateMappingRecord(record).ok).toBe(true); const result = await resolveMappingDefinition(record, catalogs(), manifest); expect(result.status).toBe("blocked"); expect(result.diagnostics.map((item) => item.code)).toEqual(["source-field-missing", "target-node-missing"]); });
  it("discovers only recursively manifest-declared scalar targets", () => { const result = discoverMappingTargets(composition.document, manifest); expect(result.targets.map((item) => `${item.target.nodeId}.${item.target.prop}`)).toEqual(["hero.title", "hero.subtitle", "hero.tone", "nested.text"]); expect(result.targets.some((item) => item.target.prop === "undeclared")).toBe(false); });
  it("allows one source to many targets but blocks a duplicate target", async () => { const result = await resolveMappingDefinition(mapping([{ id: "one", sourceFieldId: "title", target: { nodeId: "hero", prop: "title" }, transform: { kind: "identity" } }, { id: "two", sourceFieldId: "title", target: { nodeId: "nested", prop: "text" }, transform: { kind: "truncate-160" } }]), catalogs(), manifest); expect(result.status).toBe("ready"); const duplicate = await resolveMappingDefinition(mapping([{ id: "one", sourceFieldId: "title", target: { nodeId: "hero", prop: "title" }, transform: { kind: "identity" } }, { id: "two", sourceFieldId: "tone", target: { nodeId: "hero", prop: "title" }, transform: { kind: "identity" } }]), catalogs(), manifest); expect(duplicate.diagnostics.map((item) => item.code)).toContain("duplicate-target"); });
  it("reports component version and stale field failures", async () => { const changed = structuredClone(composition); changed.document.root[0]!.componentVersion = 2; const mismatch = await resolveMappingDefinition(mapping(), catalogs(model, changed), manifest); expect(mismatch.diagnostics.map((item) => item.code)).toContain("component-version-mismatch"); const stale = await resolveMappingDefinition(mapping([{ id: "x", sourceFieldId: "title", target: { nodeId: "hero", prop: "gone" }, transform: { kind: "identity" } }]), catalogs(), manifest); expect(stale.diagnostics.map((item) => item.code)).toContain("target-field-missing"); });
  it("evaluates into a detached transient document and keeps static values", async () => { const record = mapping([{ id: "one", sourceFieldId: "title", target: { nodeId: "hero", prop: "title" }, transform: { kind: "identity" } }, { id: "two", sourceFieldId: "date", target: { nodeId: "hero", prop: "subtitle" }, transform: { kind: "date-medium" } }]); const source = entry({ title: "Mapped", date: "2026-08-29" }); const beforeEntry = JSON.stringify(source); const beforeComposition = JSON.stringify(composition); const result = await evaluateMapping(record, source, catalogs(), manifest); expect(result.status).toBe("ready"); expect(result.document?.root[0]?.props).toMatchObject({ title: "Mapped", subtitle: "Aug 29, 2026", tone: "quiet" }); expect(JSON.stringify(source)).toBe(beforeEntry); expect(JSON.stringify(composition)).toBe(beforeComposition); expect(result).toMatchObject({ appliedBindingCount: 2, unchangedStaticCount: 0 }); });
  it("reports optional and required missing independently", async () => { const record = mapping([{ id: "required", sourceFieldId: "title", target: { nodeId: "hero", prop: "title" }, transform: { kind: "identity" } }, { id: "optional", sourceFieldId: "date", target: { nodeId: "hero", prop: "subtitle" }, transform: { kind: "date-medium" } }]); const result = await evaluateMapping(record, entry({}), catalogs(), manifest); expect(result.status).toBe("blocked"); expect(result.entryDiagnostics.map((item) => [item.code, item.severity])).toEqual([["required-value-missing", "blocking"], ["optional-value-missing", "nonblocking"]]); expect(result.document?.root[0]?.props).toMatchObject({ title: "Static", subtitle: "Keep" }); });
  it("uses Content whitespace semantics and treats null as an invalid present value", async () => { const whitespace = await evaluateMapping(mapping(), entry({ title: "  \n" }), catalogs(), manifest); expect(whitespace.entryDiagnostics[0]?.code).toBe("required-value-missing"); const invalid = await evaluateMapping(mapping(), entry({ title: null }), catalogs(), manifest); expect(invalid.entryDiagnostics[0]?.code).toBe("invalid-source-value"); });
  it("validates dates, select options, and Unicode transform limits", async () => { const select = await evaluateMapping(mapping([{ id: "select", sourceFieldId: "tone", target: { nodeId: "hero", prop: "tone" }, transform: { kind: "identity" } }]), entry({ tone: "invalid" }), catalogs(), manifest); expect(select.entryDiagnostics[0]?.code).toBe("select-option-invalid"); const date = await evaluateMapping(mapping([{ id: "date", sourceFieldId: "date", target: { nodeId: "hero", prop: "subtitle" }, transform: { kind: "date-medium" } }]), entry({ date: "2026-02-30" }), catalogs(), manifest); expect(date.entryDiagnostics[0]?.code).toBe("invalid-canonical-date"); const long = "😀".repeat(161); const truncated = await evaluateMapping(mapping([{ id: "unicode", sourceFieldId: "title", target: { nodeId: "hero", prop: "title" }, transform: { kind: "truncate-160" } }]), entry({ title: long }), catalogs(), manifest); expect(Array.from(String(truncated.document?.root[0]?.props.title))).toHaveLength(161); expect(String(truncated.document?.root[0]?.props.title).endsWith("…")).toBe(true); expect(validateMappingRecord({ ...mapping(), document: { ...mapping().document, bindings: [{ id: "x", sourceFieldId: "title", target: { nodeId: "hero", prop: "title" }, transform: { kind: "prefix", prefix: "😀".repeat(81) } }] } }).ok).toBe(false); });
  it("distinguishes missing, invalid, and provider errors", async () => { const missing = createContentCatalog([{ descriptor: { id: "content", label: "Content" }, store: { listModels: async () => [], getModel: async () => ({ status: "not-found" as const, id: "articles" }) } }]); const failed = createCompositionCatalog([{ descriptor: { id: "indexeddb", label: "Compositions" }, store: { list: async () => [], get: async () => { throw new Error("offline"); } } }]); const result = await resolveMappingDefinition(mapping(), { content: missing, compositions: failed }, manifest); expect(result.diagnostics.map((item) => item.code)).toEqual(["content-model-not-found", "composition-provider-error"]); });
});

describe("IndexedDB Mapping provider", () => {
  const request = <T,>(value: IDBRequest<T>) => new Promise<T>((resolve, reject) => { value.onsuccess = () => resolve(value.result); value.onerror = () => reject(value.error); });
  it("creates the exact dedicated schema", async () => { const factory = new FDBFactory(); const provider = createIndexedDbMappingProvider({ idbFactory: factory }); expect(provider.descriptor.id).toBe("mapping-indexeddb"); expect(await provider.initialization.initialize()).toEqual({ status: "ready", summaries: [] }); const db = await request(factory.open(MAPPING_DATABASE_NAME)); expect(db.version).toBe(MAPPING_DATABASE_VERSION); expect([...db.objectStoreNames].sort()).toEqual([MAPPING_META_STORE_NAME, MAPPING_RECORDS_STORE_NAME].sort()); expect([...db.transaction(MAPPING_RECORDS_STORE_NAME).objectStore(MAPPING_RECORDS_STORE_NAME).indexNames]).toEqual([MAPPING_UPDATED_AT_INDEX]); db.close(); });
  it("supports CRUD, deterministic idempotent seed, and startFresh reseeding", async () => { const seeded = mapping(); const provider = createIndexedDbMappingProvider({ idbFactory: new FDBFactory(), seed: { mappings: [seeded] } }); expect(await provider.initialization.initialize()).toMatchObject({ status: "ready", summaries: [{ id: seeded.id }] }); await provider.store.seed({ mappings: [{ ...seeded, document: { ...seeded.document, name: "Changed" } }] }); expect((await provider.store.get(seeded.id))).toMatchObject({ status: "loaded", record: { document: { name: "Article landing" } } }); await provider.store.put({ ...seeded, updatedAt: "2026-08-30T00:00:00.000Z", document: { ...seeded.document, name: "Updated" } }); expect(await provider.store.list()).toMatchObject([{ name: "Updated" }]); expect(await provider.store.delete(seeded.id)).toBe(true); expect(await provider.store.delete(seeded.id)).toBe(false); expect(await provider.initialization.startFresh()).toMatchObject({ status: "ready", summaries: [{ id: seeded.id }] }); });
  it("exposes listed/resolved Mapping catalog outcomes", async () => { const provider = createIndexedDbMappingProvider({ idbFactory: new FDBFactory() }); await provider.initialization.initialize(); await provider.store.put(mapping()); const catalog = createMappingCatalog([{ descriptor: provider.descriptor, store: provider.store }]); expect(await catalog.list()).toMatchObject({ status: "listed", entries: [{ ref: { providerId: "mapping-indexeddb", recordId: "article-landing" } }], failures: [] }); expect(await catalog.resolve({ providerId: "mapping-indexeddb", recordId: "article-landing" })).toMatchObject({ status: "resolved", record: { id: "article-landing" } }); expect(await catalog.resolve({ providerId: "missing", recordId: "article-landing" })).toEqual({ status: "not-found" }); });
  it("quarantines malformed/future records until explicit startFresh", async () => { const factory = new FDBFactory(); const provider = createIndexedDbMappingProvider({ idbFactory: factory }); await provider.initialization.initialize(); const db = await request(factory.open(MAPPING_DATABASE_NAME)); const tx = db.transaction(MAPPING_RECORDS_STORE_NAME, "readwrite"); tx.objectStore(MAPPING_RECORDS_STORE_NAME).put({ id: "bad", createdAt: stamp, updatedAt: stamp, document: { schemaVersion: MAPPING_SCHEMA_VERSION + 1 } }); await new Promise<void>((resolve) => { tx.oncomplete = () => resolve(); }); db.close(); const recovery = await provider.initialization.retry(); expect(recovery).toMatchObject({ status: "recovery-required", recovery: { reason: "future-schema", sourcePreserved: true, affectedRecordIds: ["bad"] } }); await expect(provider.store.list()).rejects.toMatchObject({ code: "validation" }); await expect(provider.store.put(createMappingRecord({ ...mapping().document, id: "bad", createdAt: stamp }))).rejects.toMatchObject({ code: "validation" }); await expect(provider.store.delete("bad")).rejects.toMatchObject({ code: "validation" }); await expect(provider.store.clear()).rejects.toMatchObject({ code: "validation" }); expect(await provider.initialization.startFresh()).toEqual({ status: "ready", summaries: [] }); });
  it("keeps createdAt immutable on update", async () => { const provider = createIndexedDbMappingProvider({ idbFactory: new FDBFactory() }); await provider.initialization.initialize(); const record = mapping(); await provider.store.put(record); await expect(provider.store.put({ ...record, createdAt: "2026-08-30T00:00:00.000Z", updatedAt: "2026-08-30T00:00:00.000Z" })).rejects.toMatchObject({ code: "validation", retryable: false }); });
  it("types unavailable, blocked, abort, newer-version, and versionchange states", async () => { expect(await createIndexedDbMappingProvider({ idbFactory: null }).initialization.initialize()).toMatchObject({ status: "error", error: { code: "unavailable", retryable: true } }); const blockedRequest = {} as IDBOpenDBRequest; const blockedFactory = { open: () => { queueMicrotask(() => blockedRequest.onblocked?.(new Event("blocked") as IDBVersionChangeEvent)); return blockedRequest; } } as unknown as IDBFactory; expect(await createIndexedDbMappingProvider({ idbFactory: blockedFactory }).initialization.initialize()).toMatchObject({ status: "error", error: { code: "blocked", retryable: true } }); expect(mapMappingOperationalError("put", "readwrite", new DOMException("aborted", "AbortError"))).toMatchObject({ code: "transaction-failed", retryable: true }); const newerFactory = new FDBFactory(); const newer = await request(newerFactory.open(MAPPING_DATABASE_NAME, MAPPING_DATABASE_VERSION + 1)); newer.close(); expect(await createIndexedDbMappingProvider({ idbFactory: newerFactory }).initialization.initialize()).toMatchObject({ status: "error", error: { code: "unsupported-version", retryable: false } }); const factory = new FDBFactory(); const provider = createIndexedDbMappingProvider({ idbFactory: factory }); await provider.initialization.initialize(); const upgrade = await request(factory.open(MAPPING_DATABASE_NAME, MAPPING_DATABASE_VERSION + 1)); upgrade.close(); await expect(provider.store.list()).rejects.toMatchObject({ code: "versionchange", retryable: true }); });
});
