import { MAPPING_PROVIDERS, MAPPING_SCHEMA_VERSION, MappingPersistenceError } from "../../model";
import type { MappingInitializationOutcome, MappingPersistenceErrorCode, MappingPersistenceOperation, MappingProvider, MappingRecoveryOutcome } from "../../model";
import { IndexedDbMappingStore } from "./store";
import { MAPPING_DATABASE_NAME, MAPPING_DATABASE_VERSION, MAPPING_META_KEYS, MAPPING_META_STORE_NAME, MAPPING_RECORDS_STORE_NAME, MAPPING_UPDATED_AT_INDEX } from "./types";
import type { IndexedDbMappingProviderOptions, MappingSchemaMeta } from "./types";

export function mappingPersistenceError(operation: MappingPersistenceOperation, code: MappingPersistenceErrorCode, message: string, retryable: boolean, cause?: unknown): MappingPersistenceError { return new MappingPersistenceError(operation, code, message, retryable, { cause }); }
export function requestResult<T>(request: IDBRequest<T>): Promise<T> { return new Promise((resolve, reject) => { request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("IndexedDB request failed.")); }); }
export function transactionComplete(transaction: IDBTransaction): Promise<void> { return new Promise((resolve, reject) => { transaction.oncomplete = () => resolve(); transaction.onabort = () => reject(transaction.error ?? new DOMException("IndexedDB transaction aborted.", "AbortError")); transaction.onerror = () => undefined; }); }
function errorName(value: unknown): string | undefined { return value !== null && typeof value === "object" && "name" in value && typeof value.name === "string" ? value.name : undefined; }
export function mapMappingOperationalError(operation: MappingPersistenceOperation, mode: IDBTransactionMode, error: unknown): MappingPersistenceError { if (error instanceof MappingPersistenceError) return error; const aborted = errorName(error) === "AbortError"; return mappingPersistenceError(operation, aborted ? "transaction-failed" : mode === "readonly" ? "read-failed" : "write-failed", aborted ? `IndexedDB ${operation} transaction was aborted.` : `IndexedDB ${operation} request failed.`, true, error); }
function sameNames(actual: DOMStringList, expected: readonly string[]): boolean { return JSON.stringify([...actual].sort()) === JSON.stringify([...expected].sort()); }
function exactShape(db: IDBDatabase): boolean { if (!sameNames(db.objectStoreNames, [MAPPING_RECORDS_STORE_NAME, MAPPING_META_STORE_NAME])) return false; try { const transaction = db.transaction([MAPPING_RECORDS_STORE_NAME, MAPPING_META_STORE_NAME], "readonly"); const records = transaction.objectStore(MAPPING_RECORDS_STORE_NAME); const meta = transaction.objectStore(MAPPING_META_STORE_NAME); return records.keyPath === "id" && !records.autoIncrement && sameNames(records.indexNames, [MAPPING_UPDATED_AT_INDEX]) && JSON.stringify(records.index(MAPPING_UPDATED_AT_INDEX).keyPath) === JSON.stringify(["updatedAt", "id"]) && !records.index(MAPPING_UPDATED_AT_INDEX).unique && meta.keyPath === "key" && !meta.autoIncrement && meta.indexNames.length === 0; } catch { return false; } }

export class IndexedDbMappingRuntime {
  readonly factory: IDBFactory | null | undefined; private connection: { db: IDBDatabase; invalidated: boolean } | undefined; private opening: Promise<{ db: IDBDatabase; invalidated: boolean }> | undefined;
  constructor(options: IndexedDbMappingProviderOptions) { this.factory = options.idbFactory === undefined ? (globalThis as { indexedDB?: IDBFactory }).indexedDB : options.idbFactory; }
  async open(operation: MappingPersistenceOperation) { if (this.connection) { if (this.connection.invalidated) throw mappingPersistenceError(operation, "versionchange", "Mapping storage was closed because another context changed its database version.", true); return this.connection; } if (!this.factory) throw mappingPersistenceError(operation, "unavailable", "IndexedDB is unavailable in this browser context.", true); this.opening ??= this.openDatabase(); try { return await this.opening; } finally { this.opening = undefined; } }
  prepareRetry(): void { if (this.connection?.invalidated) this.connection = undefined; }
  close(): void { this.connection?.db.close(); this.connection = undefined; }
  private openDatabase(): Promise<{ db: IDBDatabase; invalidated: boolean }> { return new Promise((resolve, reject) => { let request: IDBOpenDBRequest; try { request = this.factory!.open(MAPPING_DATABASE_NAME, MAPPING_DATABASE_VERSION); } catch (error) { reject(mappingPersistenceError("initialize", "unavailable", "Mapping IndexedDB could not be opened.", true, error)); return; } let settled = false; let upgradeFailure: MappingPersistenceError | undefined; request.onupgradeneeded = (event) => { const transaction = request.transaction; try { if (!transaction || event.oldVersion !== 0) throw mappingPersistenceError("initialize", "unsupported-version", `Mapping database version ${event.oldVersion} is unsupported by this clean build.`, false); const records = request.result.createObjectStore(MAPPING_RECORDS_STORE_NAME, { keyPath: "id" }); records.createIndex(MAPPING_UPDATED_AT_INDEX, ["updatedAt", "id"], { unique: false }); const meta = request.result.createObjectStore(MAPPING_META_STORE_NAME, { keyPath: "key" }); meta.put({ key: MAPPING_META_KEYS.schema, databaseVersion: MAPPING_DATABASE_VERSION, mappingRecordSchemaVersion: MAPPING_SCHEMA_VERSION } satisfies MappingSchemaMeta); } catch (error) { upgradeFailure = error instanceof MappingPersistenceError ? error : mappingPersistenceError("initialize", "transaction-failed", "Mapping database initialization failed.", true, error); try { transaction?.abort(); } catch { /* already aborted */ } } }; request.onblocked = () => { if (!settled) { settled = true; reject(mappingPersistenceError("initialize", "blocked", "Mapping storage is blocked by another open context.", true)); } }; request.onerror = () => { if (settled) return; settled = true; if (upgradeFailure) reject(upgradeFailure); else if (request.error?.name === "VersionError") reject(mappingPersistenceError("initialize", "unsupported-version", "This Mapping database was created by a newer application version.", false, request.error)); else reject(mappingPersistenceError("initialize", "transaction-failed", "Mapping database opening failed.", true, request.error)); }; request.onsuccess = () => { const db = request.result; if (settled) { db.close(); return; } if (!exactShape(db)) { settled = true; db.close(); reject(mappingPersistenceError("initialize", "unsupported-version", "Mapping database has an unsupported physical schema.", false)); return; } settled = true; const connection = { db, invalidated: false }; db.onversionchange = () => { connection.invalidated = true; db.close(); }; this.connection = connection; resolve(connection); }; }); }
}

function recovery(failures: readonly { id: string; status: "invalid" | "future-schema"; version?: number }[]): MappingRecoveryOutcome { const future = failures.find((item) => item.status === "future-schema"); return { kind: "quarantined", reason: future ? "future-schema" : "invalid", sourcePreserved: true, affectedRecordIds: failures.map((item) => item.id), ...(future?.version === undefined ? {} : { foundSchemaVersion: future.version }), message: future ? "Mapping storage contains records from a newer schema. The source data was preserved." : "Mapping storage contains malformed records. The source data was preserved." }; }

export function createIndexedDbMappingProvider(options: IndexedDbMappingProviderOptions = {}): MappingProvider { const runtime = new IndexedDbMappingRuntime(options); const store = new IndexedDbMappingStore(runtime); const initialize = async (): Promise<MappingInitializationOutcome> => { try { const scan = await store.scanForInitialization(); if (scan.failures.length) return { status: "recovery-required", summaries: scan.summaries, recovery: recovery(scan.failures) }; if (options.seed) await store.seed(options.seed); return { status: "ready", summaries: await store.list() }; } catch (error) { return { status: "error", error: error instanceof MappingPersistenceError ? error : mappingPersistenceError("initialize", "unknown", "Mapping storage initialization failed.", true, error) }; } }; return { descriptor: MAPPING_PROVIDERS.indexeddb, store, initialization: { initialize, retry: async () => { runtime.prepareRetry(); return initialize(); }, startFresh: async () => { try { await store.forceClear(); if (options.seed) await store.seed(options.seed); return { status: "ready", summaries: await store.list() }; } catch (error) { return { status: "error", error: error instanceof MappingPersistenceError ? error : mappingPersistenceError("clear", "unknown", "Starting fresh Mapping storage failed.", true, error) }; } } } }; }
