import { isSafeRecordId } from "../../../shared";
import { decodeMappingRecord, MAPPING_PROVIDERS, summarizeMapping, validateMappingRecord } from "../../model";
import type { MappingLoadOutcome, MappingRecord, MappingSeed, MappingStore, MappingSummary } from "../../model";
import { mapMappingOperationalError, mappingPersistenceError, requestResult, transactionComplete, type IndexedDbMappingRuntime } from "./provider";
import { MAPPING_META_KEYS, MAPPING_META_STORE_NAME, MAPPING_RECORDS_STORE_NAME } from "./types";

export class IndexedDbMappingStore implements MappingStore {
  readonly provider = MAPPING_PROVIDERS.indexeddb;
  constructor(private readonly runtime: IndexedDbMappingRuntime) {}
  async list(): Promise<readonly MappingSummary[]> { const scan = await this.scanForInitialization("list"); if (scan.failures.length) throw mappingPersistenceError("list", "validation", "Mapping storage contains records that cannot be listed safely.", false); return scan.summaries; }
  async get(id: string): Promise<MappingLoadOutcome> { if (!isSafeRecordId(id)) return { status: "not-found", id }; const connection = await this.runtime.open("get"); try { const transaction = connection.db.transaction(MAPPING_RECORDS_STORE_NAME, "readonly"); const raw = await requestResult(transaction.objectStore(MAPPING_RECORDS_STORE_NAME).get(id)); await transactionComplete(transaction); return raw === undefined ? { status: "not-found", id } : decodeMappingRecord(raw); } catch (error) { throw mapMappingOperationalError("get", "readonly", error); } }
  async put(record: MappingRecord): Promise<void> { const validation = validateMappingRecord(record); if (!validation.ok) throw mappingPersistenceError("put", "validation", validation.issue.message, false); const connection = await this.runtime.open("put"); try { const transaction = connection.db.transaction(MAPPING_RECORDS_STORE_NAME, "readwrite"); transaction.objectStore(MAPPING_RECORDS_STORE_NAME).put(structuredClone(record)); await transactionComplete(transaction); } catch (error) { throw mapMappingOperationalError("put", "readwrite", error); } }
  async delete(id: string): Promise<boolean> { if (!isSafeRecordId(id)) return false; const existing = await this.get(id); if (existing.status === "not-found") return false; if (existing.status !== "loaded") throw mappingPersistenceError("delete", "validation", "Invalid Mapping data was preserved. Use startFresh to discard it explicitly.", false); const connection = await this.runtime.open("delete"); try { const transaction = connection.db.transaction(MAPPING_RECORDS_STORE_NAME, "readwrite"); transaction.objectStore(MAPPING_RECORDS_STORE_NAME).delete(id); await transactionComplete(transaction); return true; } catch (error) { throw mapMappingOperationalError("delete", "readwrite", error); } }
  async seed(seed: MappingSeed): Promise<void> { for (const record of seed.mappings) { const validation = validateMappingRecord(record); if (!validation.ok) throw mappingPersistenceError("seed", "validation", validation.issue.message, false); } const connection = await this.runtime.open("seed"); try { const transaction = connection.db.transaction(MAPPING_RECORDS_STORE_NAME, "readwrite"); const store = transaction.objectStore(MAPPING_RECORDS_STORE_NAME); for (const record of seed.mappings) { const existing = await requestResult(store.get(record.id)); if (existing === undefined) store.put(structuredClone(record)); } await transactionComplete(transaction); } catch (error) { throw mapMappingOperationalError("seed", "readwrite", error); } }
  async clear(): Promise<void> { const scan = await this.scanForInitialization("initialize"); if (scan.failures.length) throw mappingPersistenceError("clear", "validation", "Mapping storage contains invalid data and was preserved. Use startFresh to discard it explicitly.", false); await this.forceClear(); }
  async forceClear(): Promise<void> { const connection = await this.runtime.open("clear"); try { const transaction = connection.db.transaction([MAPPING_RECORDS_STORE_NAME, MAPPING_META_STORE_NAME], "readwrite"); transaction.objectStore(MAPPING_RECORDS_STORE_NAME).clear(); transaction.objectStore(MAPPING_META_STORE_NAME).put({ key: MAPPING_META_KEYS.schema, databaseVersion: 1, mappingRecordSchemaVersion: 1 }); await transactionComplete(transaction); } catch (error) { throw mapMappingOperationalError("clear", "readwrite", error); } }
  async scanForInitialization(operation: "list" | "initialize" = "initialize"): Promise<{ summaries: MappingSummary[]; failures: { id: string; status: "invalid" | "future-schema"; version?: number }[] }> { const connection = await this.runtime.open(operation); try { const transaction = connection.db.transaction([MAPPING_RECORDS_STORE_NAME, MAPPING_META_STORE_NAME], "readonly"); const values = await requestResult(transaction.objectStore(MAPPING_RECORDS_STORE_NAME).getAll()) as unknown[]; const metaRecords = await requestResult(transaction.objectStore(MAPPING_META_STORE_NAME).getAll()) as unknown[]; await transactionComplete(transaction); const meta = metaRecords[0]; if (metaRecords.length !== 1 || !meta || typeof meta !== "object" || Object.keys(meta).sort().join(",") !== "databaseVersion,key,mappingRecordSchemaVersion" || (meta as { key?: unknown }).key !== MAPPING_META_KEYS.schema || (meta as { databaseVersion?: unknown }).databaseVersion !== 1 || (meta as { mappingRecordSchemaVersion?: unknown }).mappingRecordSchemaVersion !== 1) throw mappingPersistenceError(operation, "unsupported-version", "Mapping database schema metadata is missing or unsupported.", false); const summaries: MappingSummary[] = []; const failures: { id: string; status: "invalid" | "future-schema"; version?: number }[] = []; for (let index = 0; index < values.length; index += 1) { const raw = values[index]; const decoded = decodeMappingRecord(raw); if (decoded.status === "loaded") summaries.push(summarizeMapping(decoded.record)); else if (decoded.status !== "not-found") failures.push({ id: raw && typeof raw === "object" && "id" in raw && typeof raw.id === "string" ? raw.id : `unknown-${index + 1}`, status: decoded.status, ...(decoded.status === "future-schema" ? { version: decoded.foundSchemaVersion } : {}) }); } return { summaries: summaries.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt) || a.id.localeCompare(b.id)), failures }; } catch (error) { throw mapMappingOperationalError(operation, "readonly", error); } }
}
